### ISSUE TITLE
change of option.pages doesn't work

### ISSUE THREAD

**Issue by qsimpleq** [roxiness/routify#1]
rollup.config.js

> fileRouter({
		appFile: './src/app/Hello.svelte',
		pages: './src/routes'
	}),

got:
> Error: Could not resolve './src/pages/index.svelte' from generatedRoutes.js`

seems it hardcoded at [/src/files-to-routes.js](https://github.com/jakobrosenberg/svelte-filerouter/blob/dd05e75eb362e716b4d8d8c1ee77295ad7baf517/src/files-to-routes.js#L19)

**Comment by jakobrosenberg** [comment]
You are complete right. Thanks for the headsup!

Just about to have dinner, but I'll have a fix ready right after.

**Comment by jakobrosenberg** [comment]
Fix applied in v1.1.1.
