### ISSUE TITLE
Unknown Prop Warnings When Accessing Pages With Parameters

### ISSUE THREAD

**Issue by tmose1106** [roxiness/routify#100]
Every time I access a route defined with parameters, the pages work perfectly but two warnings are generated. For example, I have a page called `[userId].svelte` and whenever I access this page, the following warnings are generated:

```
<U5BuserIdu5D> was created with unknown prop 'scoped' bundle.js:7676:78
<U5BuserIdu5D> was created with unknown prop 'scopedSync' bundle.js:7676:78
```

Tested this in both Firefox 74 and Chrome 81, both have the same warnings. So I believe this a problem with Routify.

**Comment by rixo** [comment]
What version of Routify are you using?

**Comment by tmose1106** [comment]
My lock file says version `1.0.1-56`.

**Comment by jakobrosenberg** [comment]
Routify doesn't catch and hide prop warnings anymore, so the real question is why those warnings don't show all the time. Might have a look this weekend.

**Comment by jakobrosenberg** [comment]
This has been fixed and will be available in the next release.

**Comment by eriknyk** [comment]
Seems still happening on v1.5.5  -  #159
