### ISSUE TITLE
provide --host option to the cli

### ISSUE THREAD

**Issue by jokin** [roxiness/routify#101]
Sometimes you need to be able to access your development environment from another device(a mobile, a virtual machine, a tv). many dev servers provide the option to use the --host flag to let the server know to which interface bind. 

It just has to pass the parameter to the inner server, For example, In the current example I can modify the start comand to pass the parameter to the sirv server so I can test, but it would be better if I can use the dev server with livereload. 

it's similar to https://github.com/sveltech/routify-starter/pull/13 but with the interface instead of the port.

**Comment by rixo** [comment]
Routify doesn't do any serving and has no dev server. It merely generates routes (and handle them in the browser). This is not a Routify problematic and couldn't be handled by our cli.

With the default starter template, modifying the `start` script is the way to go.

Live reload is independent from the web server, it launches its own server (beside `sirv`, for example) that signals to the browser when it should reload the page. You may need to change the `livereload` plugin's host option... which actually doesn't seem possible, but I may be missing something (see docs of [rollup-plugin-livereload](https://github.com/thgh/rollup-plugin-livereload#options) and [livereload itself](https://www.npmjs.com/package/livereload#server-api)).

Or maybe you can use [HMR instead](https://github.com/rixo/routify-starter/blob/hmr/rollup.config.js)... My [hot plugin](https://github.com/rixo/rollup-plugin-hot) does launch a web server during development, and it does have a `host` option that you can customize. ¯\\\_(ツ)_/¯

**Comment by jokin** [comment]
Ok, maybe it's something to have on the starter template more than on the project, actually, the issue I linked is from the starter project.

**Comment by jakobrosenberg** [comment]
@jokin have you tried rewriting the start script from 
``"start": "sirv dist --single __app.html"``
to
``"start": "sirv dist --single __app.html --host 0.0.0.0"``

**Comment by rixo** [comment]
@jakobrosenberg apparently, that he had solved... Can you manage have livereload working with this?

**Comment by jokin** [comment]
Yeah, I did like that, I was just suggesting if there was a way to passthrough  the parameter when calling from the command line because that was the first thing it came to my mind and how it works in many other cases. the routify command at the end calls the start command, so maybe just a bit of documentation is needed to be clear how to do it. 

The livereload works, now I have another problem with that, because I wan't to run the webapp on some constrained devices which use opera tv (chromium 44) and while the app transpiled to es5 works, livereload doesn't work because it's not transpiled. But that is a horse of different color
