### ISSUE TITLE
1 vulnerability required manual review and could not be updated

### ISSUE THREAD

**Issue by jointoday** [roxiness/routify#103]
Moderate        Regular Expression Denial of Service                          
                                                                                
  Package         acorn                                                         
                                                                                
  Patched in      >=7.1.1                                                       
                                                                                
  Dependency of   @sveltech/routify [dev]                                       
                                                                                
  Path            @sveltech/routify > @sveltech/ssr > jsdom > acorn-globals >   
                  acorn                                                         
                                                                                
  More info       https://npmjs.com/advisories/1488

**Comment by jakobrosenberg** [comment]
Acorn is not a direct dependency of Routify, but JSDOM.

https://github.com/jsdom/jsdom/blob/master/package.json

**Comment by jointoday** [comment]
should be i am worried  about this?

**Comment by jakobrosenberg** [comment]
I wouldn't be.
