### ISSUE TITLE
beforeUrlChange fire twice before return back

### ISSUE THREAD

**Issue by jointoday** [roxiness/routify#104]
I'm using this in my project
```javascript
 import { beforeUrlChange } from "@sveltech/routify";

 $beforeUrlChange(()=> confirm('Are you sure you wish to leave?'))
```
to prevent accidentally 'go back'. It's should do like this:
`home-->product list-->form(beforeUrlChange)`
but when i using this, suddenly its fire twice, 1st **product list** then **form**. I dont what become like this.

what i want to do, only **form** got function beforeUrlChange not **product list**.

**Comment by jakobrosenberg** [comment]
I'll have a look at this. Could be a little while though.

**Comment by jakobrosenberg** [comment]
@jointoday sorry I completely forgot to follow up on this. The bug should be fixed. If not, let me know and I'll reopen it. :)
