### ISSUE TITLE
Simplicity of folder setup: have to skip past 3 folders to get to the "working" ones

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#106]
Related to #105. I am introducing an audience new to Svelte to this folder structure. I am going to tell them to focus on the `src` and `static` folders to work in. But the fact that you have to skip over 3 folders that you won't need until later doesn't scream simple to me.

<img width="1396" alt="Screenshot 2020-03-09 at 19 49 43" src="https://user-images.githubusercontent.com/12690/76247059-2f0c0500-623f-11ea-984b-18f727fafcfa.png">

Just thinking about Svelte + Routify from a teaching perspective. It is easier if the folders are as analog as possible with Sveltejs/template.

Any thoughts welcome. Just passing my thoughts.

**Comment by jakobrosenberg** [comment]
The config folder might be on the way out in favor of a config .env file in the root.

The scripts folder we could possibly generate on demand. Depends on the complexity it adds. (This might veer into framework land)

Dist has to stay as we need a place to output our files. Prerendered pages are generated recursively in the root of this folder, thus we can use Svelte's template approach by using ``public/build`` for generated files.

**Comment by Wolfr** [comment]
Closing due to stale-ness.
