### ISSUE TITLE
No Event Listener

### ISSUE THREAD

**Issue by rjsandman** [roxiness/routify#113]
I am using svelte:window to get the scrollY position.  On Dev mode, everything works but when I build, I do not see event listeners in the chrome dev tools.  Any thoughts?

**Comment by jakobrosenberg** [comment]
Have you got a repo I can try?

**Comment by rjsandman** [comment]
https://github.com/sandman18/Routify-Sosf

**Comment by jakobrosenberg** [comment]
Your app doesn't load after you've built the site. It should though. What you're seeing is just prerendered pages with no app. If you check your network tab, there should be a ``main.js`` for it to work.

Any idea why it doesn't load? I'm gonna see if I can figure it out.

**Comment by rjsandman** [comment]
I have no clue!!

**Comment by jakobrosenberg** [comment]
I think it has to do with your ``__dynamic.html``

Try renaming 
```html
	<script type="module" defer src="https://unpkg.com/dimport@1.0.0/dist/index.mjs?module" data-main="/build/main.js">
	</script>
```
to
```html
	<script type="module" defer src="https://unpkg.com/dimport@1.0.0/dist/index.mjs?module" data-main="/build/main.js"></script>
```

It shouldn't make a difference, but some reason that fixes it for me.

**Comment by jakobrosenberg** [comment]
Just checked again. For some reason that linebreak breaks the import.

**Comment by rjsandman** [comment]
Where is that file getting generated from?  How do you check that it's that line?

**Comment by jakobrosenberg** [comment]
That's in the static folder.

``static/__dynamic.html``

**Comment by rjsandman** [comment]
Oh well.  Going to start from scratch.

**Comment by jakobrosenberg** [comment]
Got solved on Discord.
