### ISSUE TITLE
How to place code after routify-app div?

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#114]
If I want to put some external Javascript scripts after the `routify-app` div,  in my use case for loading external fonts and for an analytics package, how would I do so? 

Example of the problem I am running into: current structure after SSR:

![image](https://user-images.githubusercontent.com/12690/76564161-9ed0f880-64a8-11ea-8194-ef1a199e6438.png)

The Piwik (analytics) and call to TypeNetwork should ideally be -after- the routify app div. If the code of routify inserts the routify-app div at the end of the body, I can't do anything anymore.

Shouldn't we put the routify-app div in the `__bundle.html` template (always) and insert in there, instead of inserting the whole routify-app and the end of the HTML `body` tag?

**Comment by jakobrosenberg** [comment]
Assuming you're using the Routify Starter, you could change the target element: https://github.com/sveltech/routify-starter/blob/master/src/main.js

**Comment by Wolfr** [comment]
Great, noted for the future!
