### ISSUE TITLE
Linking to an anchor seems broken

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#119]
Linking to an anchor on another page (by linking to an id) doesn't seem to work.

E.g. `/route1` links to `/route2#myref` e.g. through a link: <a href="/route2#myref">Link</a> - this then references a <div id="myref"> somewhere in a position you want to scroll to on the other page.

I will provide a reduced test case, just logging the issue here so I don't forget.

**Comment by jakobrosenberg** [comment]
Is scroll enabled in the project? ``--scroll auto|smooth``

**Comment by Wolfr** [comment]
This should work by default in my opinion?

Where would I set this flag?

**Comment by jakobrosenberg** [comment]
Either in the config file or the CLI. ``routify --scroll auto``.

The next release will have scroll set to auto by default.
