### ISSUE TITLE
usage with webpack or parcel

### ISSUE THREAD

**Issue by joshua1** [roxiness/routify#12]
Hi @jakobrosenberg  I am interested in using this router. I see though that it has a devdependency on a rollup plugin , how does that impact usage with svelte webpack or parcel-bundler-svelte ?

**Comment by jakobrosenberg** [comment]
@joshua1 it currently works with Rollup. But I'm hoping to have a universal version ready in the very near future. How urgent is it?

**Comment by joshua1** [comment]
@jakobrosenberg  thanks for the response. Not really urgent. I love the no config approach of parcel and have been using it for my project. I plan to use this library for routing . I will use the rollup template for now . Thanks

**Comment by jakobrosenberg** [comment]
Thanks for your patience. This is currently the top priority.

**Comment by jakobrosenberg** [comment]
@joshua1 
There's a prerelease here which doesn't need rollup.
https://github.com/jakobrosenberg/svelte-filerouter/releases/tag/v1.4.2

**Comment by joshua1** [comment]
This is cool @jakobrosenberg . Thanks

**Comment by joshua1** [comment]
@jakobrosenberg  sorry i have to reopen and ask, with this release, where do i specify the sveltefilerouter options passed into rollup plugins array . i need a way to specify the directory name for pages as well as the dynamicImport option

**Comment by joshua1** [comment]
Ok, i see in the cli.js file that i can pass them as parameters when i call routify. I will try that now . If this is right, it should go in the documentation/ Readme then

**Comment by jakobrosenberg** [comment]
It will. But for now it's only a feature in the prerelease.

**Comment by joshua1** [comment]
on 1.4.2 mentioned, i get this error 
```

🚨  ../web_project/node_modules/svelte-filerouter/lib/files-to-routes.js:1:40: 
Cannot resolve dependency 'rollup-pluginutils'
> 1 | const { makeLegalIdentifier } = require('rollup-pluginutils')
    |                                        ^
  2 | const path = require('path')
  3 | const fsa = require('./utils/fsa')
  4 | 
(node:86835) UnhandledPromiseRejectionWarning: Error: Cannot resolve dependency 'rollup-pluginutils'

```
index.js in the lib directory is an import from *rollup-plugin-svelterouter* which itself requires rollup . 
```
module.exports.fileRouter = require('./rollup-plugin-filerouter')
```

**Comment by jakobrosenberg** [comment]
lib/index.js isn't used unless you manually import it.

I'm perplexed why it can't resolve 'rollup-pluginutils'. It's part of the dependencies.

@rixo Any idea what's going on here?

**Comment by joshua1** [comment]
This is happening when i import Router , which i believe i need to use as holder (slot) for loaded routes /pages 
```
<script>
  import { Router } from "svelte-filerouter";
</script>

<Router />
```

**Comment by jakobrosenberg** [comment]
Your code is correct.

Could you try reinstalling? ``npm i svelte-filerouter@beta``

**Comment by rixo** [comment]
@jakobrosenberg `rollup-pluginutils` has to be in `dependencies`, not [`devDependencies`](https://github.com/jakobrosenberg/svelte-filerouter/blob/37493ec4a714f68735b39afccad8b91d298fe56e/package.json#L18) or it won't get installed when people simply do `npm install -D svelte-filerouter`.

@joshua1 You've probably been misguided by your IDE, that resolved the [`main`](https://github.com/jakobrosenberg/svelte-filerouter/blob/37493ec4a714f68735b39afccad8b91d298fe56e/package.json#L5) field of the `package.json`, but actually it's the [`svelte`](https://github.com/jakobrosenberg/svelte-filerouter/blob/37493ec4a714f68735b39afccad8b91d298fe56e/package.json#L6) that is used in a Svelte project. The error message is the real error.

**Comment by jakobrosenberg** [comment]
@joshua1 moved rollup-pluginutils to dependencies and pushed a new npm. It includes a PR from rixo which I haven't tested, so fingers crossed. Could you try install again?

Thanks @rixo , any idea why the error didn't show earlier?

**Comment by rixo** [comment]
Because we only tested it with linked dev repos is the more probable, I'd say.

**Comment by joshua1** [comment]
Thanks @jakobrosenberg and @rixo i will try this now and let you guys know how it goes
