### ISSUE TITLE
[bug] - Can't find config file

### ISSUE THREAD

**Issue by Olyno** [roxiness/routify#121]
# Description

Hi,
I just updated routify (I think) to ``^1.1.1-0`` and now I can't start my server without get the error below.

# Error:

```
Error: Could not resolve '../tmp/config' from ..\..\node
_modules\@sveltech\routify\runtime\utils.js
    at error (D:\projects\waft\node_modules\rollup\dist\shared\node
-entry.js:5400:30)
    at ModuleLoader.handleResolveId (D:\projects\waft\node_modules\
rollup\dist\shared\node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (D:\projects\waft\node_modules\roll
up\dist\shared\node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (D:\projects\waft\node_modules\rollup\dist\shared\
node-entry.js:38:28)
```

**Comment by jakobrosenberg** [comment]
Can you post your ``package.json`` and do you have repo you can share?

Also, 1.0.6 is the latest release. 1.1.1 is a beta release. (In this case I guess it won't make much difference though)

**Comment by Olyno** [comment]
I think not my ``package.json`` file is usefull here

**Comment by jakobrosenberg** [comment]
Yes, let's speculate.

**Comment by jakobrosenberg** [comment]
Look, you can copy paste the script section of your ``package.json`` or I can cup your landing gear while you cough.

If you don't want to help me help you, there's nothing I can do and I'll have to close this issue.
