### ISSUE TITLE
Init does too much for you

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#131]
The init does everything for you, even running a server.

This way, first time users do not learn that they have to start their project with `npm run dev`.

I think it would be better if init initializs, but does not run the server.

Then, you instruct people to run `npm run dev`.

When there is a compiler error or the server needs to be restarted, the person now knows what to do.

Starting a server on project initialisation is also not expected behavior. Things like CRA (create-react-app) do not function that way either.

**Comment by rixo** [comment]
Agree. Printing the command to run the server instead is better indeed.

**Comment by jakobrosenberg** [comment]
I updated the init script last night, but forgot to reply.

```
Usage: cli init [options]

Options:
  -s, --start-dev   run "npm run dev" automatically
  -f, --no-example  delete the example folder
  -h, --help        output usage information
```

``-f`` should be ``-e``. Will be fixed in next beta.

**Comment by Wolfr** [comment]
Very cool! Thanks for listening to my feedback <3
