### ISSUE TITLE
Double render

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#143]
If I add text to index.svelte, it shows up twice.

See https://codesandbox.io/s/awesome-agnesi-h2rov where I used the “routify 2020” template.

**Comment by jakobrosenberg** [comment]
That's an old experimental template with Rixo's HMR module. Where did you find the template?

**Comment by Wolfr** [comment]
On codesandbox, if you search for Routify. There was a "routify minimal" and a "routify 2020" and some named experiments. So I chose "routify 2020".

I also recommended this template to a commenter here - https://www.reddit.com/r/sveltejs/comments/fuquw5/routify_a_filebased_router_for_svelte/ 
whoops!

**Comment by jakobrosenberg** [comment]
Deprecated the templates. Might create a new one, but I'm not sure if there's a point considering Github import is much better.
