### ISSUE TITLE
Rollup Deprecation Warning

### ISSUE THREAD

**Issue by khuongduybui** [roxiness/routify#144]
I'm seeing this warning when running the latest stable version of `rollup` and `@sveltech/routify`.

```
A plugin is directly adding properties to the bundle object in the "generateBundle" hook.
This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.
```

**Comment by jakobrosenberg** [comment]
Hi @khuongduybui are you using the Routify's Rollup plugin?

**Comment by rixo** [comment]
It's probably not the Routify plugin, since it has no `generateBundle` hook...

By any chance, does Rollup points you to the faulty plugin name?

**Comment by khuongduybui** [comment]
My bad. I commented `routify({})` out and still received that warning.
