### ISSUE TITLE
fatal: 'submodule' on npm install

### ISSUE THREAD

**Issue by frederikhors** [roxiness/routify#147]
Trying to install on Windows 10 (git version 2.26.0.windows.1).

`npm i -D @sveltech/routify`

```
npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!
```

**Comment by jakobrosenberg** [comment]
I just tried running the command but was unable to reproduce the error. (I'm on Windows 10 too)

What do you get if you run ``npm -v`` ?

**Comment by frederikhors** [comment]
6.14.4

**Comment by jakobrosenberg** [comment]
Does ``npx @sveltech/routify init`` work?

**Comment by frederikhors** [comment]
nope, the same

**Comment by jakobrosenberg** [comment]
@rixo any idea what this could be? It doesn't seem related to Routify.

**Comment by rixo** [comment]
Nope... It does look like a git + windows issue. There have been [others](https://github.com/npm/npm/issues/20815).

@frederikhors I'm just shooting in the dark here, but what does it give if you try to run the command yourself?

```bash
git submodule update -q --init --recursive
```

This should probably be run from some specific path though... Any idea what package is trying to run git?

**Comment by frederikhors** [comment]
`fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?`

**Comment by jakobrosenberg** [comment]
It looks like it's your git installation that's broken. I recommend reinstalling it.

Just out of curiosity, what does ``git --version`` return?

**Comment by frederikhors** [comment]
`git version 2.26.0.windows.1`

> It looks like it's your git installation that's broken.

https://stackoverflow.com/a/54677163/10088259

I think we should not rely on git submodule for this package to be installed. Don't you think?

Isn't npm alone enough?

Many people don't use Git at all.

**Comment by jakobrosenberg** [comment]
Are you able to track down the dependency that's producing this error?

**Comment by dominikg** [comment]
might be this one: 

https://github.com/sveltech/ssr/blob/4c1cb49623b80e4581b38c77c66464fd67e5f41b/package.json#L27

**Comment by jakobrosenberg** [comment]
Even though Canvas is listed as optional in JSDOM's documentation, I was at the time of writing SSR required to noop it to avoid missing dependency errors.

If anyone could confirm that it's no longer needed, I'd be happy to remove it or accept a pull request.

**Comment by jakobrosenberg** [comment]
1.8 shouldn't require the Canvas dummy package.
