### ISSUE TITLE
How do I fetch data for pages?

### ISSUE THREAD

**Issue by swyxio** [roxiness/routify#149]
## question

Hi! we are trying to use Routify more as a static site generator (aka Sapper replacement). however the data part is a tough one to figure out. in the starter https://github.com/sveltech/routify-starter you only hardcode the data in a js file. ideally what we want is a way to fetch data in node, that just generates a JSON blob and doesn't run on the clientside.

Is there a way to do this? was talking to @Wolfr but we had no solution for this.

**Comment by jakobrosenberg** [comment]
Hi @sw-yx, do you mean fetching data from an external API?

Documentation
https://routify.dev/docs/helpers#ready

Implementation in the starter template
https://github.com/sveltech/routify-starter/blob/master/src/pages/example/api/%5BshowId%5D.svelte

Live example (refreshing the page will show ``SSR`` in the lower left corner, whereas for the static pages it would show ``Prerendered`` on refresh.
https://netlify.routify.dev/example/api/32

Rehydrating on the client can be disabled. You can make a condition based on``navigator.userAgent.match('jsdom')`` to check if you're running in Node.

If you're making 100% static generator with no app hydration at all, you can disable the script entry in either static/__bundle.html or static/__dynamic.html to disable loading the app.

The Routify 1.5 beta will consolidate the two templates into a single __index.html. It should also have some other features which might benefit you when making a static site generator, like predetermined parameters (think enums).

I hope this somewhat answers it. Feel free to join us on Discord if you want to have a chat. 🙂

**Comment by swyxio** [comment]
ah i think it does! thank you!
