### ISSUE TITLE
Calling onMount() every time a route changes

### ISSUE THREAD

**Issue by dmuharemagic** [roxiness/routify#150]
I am having troubles with setting Routify up. I'm trying to utilize Routify in an existing Svelte project, thus I have tried to follow the [guidelines](https://routify.dev/guide/installation/install-to-existing-project). However, `routify -c` seemed to throw of some kind of an error when using the  script `rollup -c -w`:

````
> rollup -c -w

<function>:484
        ? (await import(url.pathToFileURL(fileName).href)).default

SyntaxError: Expected an operand but found import
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.<anonymous> (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/Desktop/frontend/node_modules/rollup/dist/bin/rollup:23:25)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.<anonymous> (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
````

I resolved it by just running the plain `rollup -c -w` as the dev script, and configured routify in `rollup.config.js` as such:

I'm using the latest Rollup version, v.2.6.0. Is there a certain version of Rollup that we have to use, since I see that most of the dependencies in the starter template are outdated as well?

It works when using the rollup plugin:

```
import routify from '@sveltech/routify/plugins/rollup';
routify({
	singleBuild: production,
	pages: 'src/routes',
	outputDir: 'src/.tmp',
}),
```

Similarly, when accessing nested components, such as from `/posts` to a specific post route `/post/:postId` and returning back to `/posts` onMount() seems to be called (every time). This causes the whole component to reload, thus reloading the data previously fetched. The same issue happens with all of the defined routes.

**Comment by jakobrosenberg** [comment]
Hi @dmuharemagic, a few questions:
1) What version of Routify are you using?
2) Did you run ``routify -c rollup -c -w`` or ``routify -c nameOfRollupTask``
3) In which file is your onMount? `_layout.svelte` or `index.svelte`

**Comment by dmuharemagic** [comment]
Hi @jakobrosenberg , thanks for the quick response. I'm using the latest Routify version (1.4.9).
As for the second question, I modified my scripts to reflect the guidelines:

```
 "dev": "routify -c my-server",
  "my-server": "rollup -c -w"
```

onMount is located in `index.svelte`.

**Comment by jakobrosenberg** [comment]
You should try ``/posts/_layout.svelte`` instead. The URL ``/posts`` is really just an alias for ``/posts/index``, which is a separate page from ``/posts/:id``.

I'm puzzled by the first problem, since all ``-c my-server`` does, is run ``npm run my-server`` for you. I'll have a look at this and see if I can find the cause.

**Comment by Autr** [comment]
Having the same problem using default project. The resultant package.json is really complicated:

```
"scripts": {
    "dev": "run-p routify nollup api sass",
    "dev:ssr": "run-p routify rollup",
    "build": "run-s build:*",
    "build:app": "routify -b && rollup -c",
    "build:static": "spank",
    "serve": "spassr --ssr",
    "rollup": "rollup -cw",
    "nollup": "nollup -c",
    "routify": "routify"
  }
```

**Comment by jakobrosenberg** [comment]
@autr can you give me a description of the error? What you're doing, what is happening and what you want to happen.
