### ISSUE TITLE
Production example

### ISSUE THREAD

**Issue by si3nloong** [roxiness/routify#151]
I’m awared after I npm build, it will generate a folder which contains a preview server, is the preview server mean for production? If no, can we have the details how we can publish the routify app for production.

**Comment by jakobrosenberg** [comment]
Hi @si3nloong 

Routify itself is just a router and as such doesn't handle deployments. We do however have a Starter template with build in deployments.

https://github.com/sveltech/routify-starter

There's a draft on how to do deployments here
https://routify-2020-7uey7wrq2.now.sh/guide/starter-Template/deployment

**Comment by si3nloong** [comment]
@jakobrosenberg thank you for the fast answer
