### ISSUE TITLE
Problem when loading static images in route with params

### ISSUE THREAD

**Issue by abdes-zakari** [roxiness/routify#153]
I use routify for SPA with svelte.

images are located in` "public/images"`

When i load image from _about_ route :`"http://localhost:5000/about"`  link of the image will be `"http://localhost:5000/images/myImage.jpg"`.

The problem now is when i load image from a route that requires a parameter like so` "post/[postId]"`
link of the image will be `"http://localhost:5000/post/images/myImage.jpg"`.

There is any way to get link of image whitout  `"post"`?

**Comment by jakobrosenberg** [comment]
Sounds like you're using a relative URL for your image. Try prefixing the image with ``/`` so it becomes ``src=/path/to/image.jpg``. This should give you an absolute URL instead.

**Comment by abdes-zakari** [comment]
Thanks for your helpful answer.

**Comment by jbixon13** [comment]
I'm trying to resolve a similar issue and absolute paths as suggested above are not working as expected. 

I am trying to reference an image in the static folder with the following code in the ArticleItem component:

```js
<main>
    <a href={$url('/blog/' + article.link)}>
        <img src='/static/images/previews/webdev-year.svg' alt='article preview' />
        <h3>{article.title}</h3>
        <p>{article.subtitle}</p>
    </a>
</main>
```

The ArticleItem component is nested within the ArticleList component as follows: 

```js
<script>
    import { articles } from '../../stores.js';
    import ArticleItem from './ArticleItem.svelte'
</script>

<main>
    <h1>Let's test the ArticleList component:</h1>
    <ul>
	    {#each $articles as article}
            <ArticleItem article={article}/>
	    {/each}
    </ul>
</main>
```

The result I get is as expected for everything besides the img (the alt param shows up but not the image):
![image](https://user-images.githubusercontent.com/32110237/87865070-76697700-c93e-11ea-9079-350dc240b668.png)

For reference, the images are stored with the following file structure: 
![image](https://user-images.githubusercontent.com/32110237/87865080-afa1e700-c93e-11ea-95a9-a0ae79b316e7.png)

**Comment by jakobrosenberg** [comment]
@jbixon13 the static folder is the root of your public path, so `/static/images/previews/webdev-year.svg` is referenced with `/images/previews/webdev-year.svg`.

**Comment by jbixon13** [comment]
That solved it, thank you!
