### ISSUE TITLE
[FR] Server-only hook

### ISSUE THREAD

**Issue by akaufmann** [roxiness/routify#155]
It would be nice if a server-only hook was available, e.g. to fetch data only on the server and synchronize it with the client, so that after hydration the same request (e.g. w/ universal-fetch, Firebase, ...) is not triggered again in the client. Something like:

```js
import { onServerPrefetch, ready } from "@sveltech/routify";

let items = []

onServerPrefetch(async () => {
  items = await getBlogItems()
  $ready()
})

**Comment by jakobrosenberg** [comment]
This seems like a worthwhile feature.

You can restrict loading to the server with ``navigator.userAgent.match('jsdom')``, but that would leave you dry on the client after the app has rehydrated.

**Comment by jakobrosenberg** [comment]
This was partially added with `routify.inBrowser` / `window.routify.inBrowser`.

Preventing rehydration on the client is not possible unless you disable JS entirely on the site.
