### ISSUE TITLE
Not supported by Microsoft Edge

### ISSUE THREAD

**Issue by timoanttila** [roxiness/routify#156]
**Describe the bug**
I have two projects on Routify and one without, but only the project without Routify runs on Microsoft Edge. Edge does not run build.js. Tried to install babel, but no effect.

**Logs**
`SCRIPT1028: Expected identifier, string or number came back.`
(probably Netlify minified and bundle JS)

This came after I managed to fix the first one:
`0: Object doesn't support property or method 'fromEntries'`

Which comes from here:
```
export default {
    paramsHandler: {
        parse: search => Object.fromEntries(new URLSearchParams(search)),
        stringify: params => '?'+(new URLSearchParams(params)).toString()
    }
}
```

**To Reproduce**
Not sure, but I think I just installed a new Svelte rollup project and Routify.

**Expected behavior**
Svelte + Routify projects should run on all modern browsers.

**Information about your Svelte project:**
Example is my company website, very simple one page project. Wanted to use Routify so I could create subpages for references and such. My other project is list of websites which are fetched from API. Both projects are hosted on Netlify.
[Github](https://github.com/timoanttila/tuspe) | [Live](https://tuspe.com/)

**Severity**
Blocking all Microsoft Edge users and it's default browser for all Microsoft Windows users. Pretty severity.

**Comment by eriknyk** [comment]
@timoanttila  why do you closed this issue? I just checked that routes is breaking the app on MS Edge, 

![image](https://user-images.githubusercontent.com/205721/80558464-19de6780-89a0-11ea-9b84-e8ddbd018626.png)


![image](https://user-images.githubusercontent.com/205721/80558484-2d89ce00-89a0-11ea-9564-d316c11b2185.png)


not sure if you discovered something why edge is breaking?
Maybe this issue should be re-opened.

Regards.

**Comment by timoanttila** [comment]
I closed this, because those problems which I described were easily fixed by updating all software. They were already fixed those issues. However, Microsoft Edge needed more than that, but I didn't get any specific error so I didn't know how to tell what's going on.

Check this guide: https://blog.az.sg/posts/svelte-and-ie11/
I managed to run my websites on Edge after installing Babel.

JakeDK from Routify's Discord promised to fix Edge issue later so we don't have to use Babel anymore.

**Comment by Wolfr** [comment]
This is outstanding, does this mean that any Routify site does not work on Microsoft Edge? If so, that is a big issue.

**Comment by ghostdevv** [comment]
Is this still a thing?

**Comment by ghostdevv** [comment]
@timoanttila @jakobrosenberg

**Comment by jakobrosenberg** [comment]
Routify works with Edge browser. For the legacy versions of Edge, you can set compatibility in your bundler.

**Comment by timoanttila** [comment]
I had old version of something which made that problem. Had to use
latest version which were not assessable through normal update. Everything
should be fine now nowadays
