### ISSUE TITLE
Routify export: specify directory

### ISSUE THREAD

**Issue by cslovell** [roxiness/routify#157]
So right now, in the npm scripts, there is an index.html file generated from the "routify export" command and it now goes to a fixed directory, dist.
```
[Routify] Exporting to: dist
[Routify] Generated 1 static pages
[Routify] Export finished
```
It would be great if I can send this to a directory the folder one level below dist or to customize in some way the path and the name it goes to.

**Comment by jakobrosenberg** [comment]
This will probably be added, but just out of curiosity. How come you need to move it down a level?

**Comment by cslovell** [comment]
So I'm adding this on top of an existing app that serves static files from wwwroot, so it would be nice to have everything go there. Like this--as it expects index.html in a wwwroot folder.
```
.
+-- _config.yml
+-- wwwroot
|   +-- index.html
|   +-- global.css
+-- routify_client
|   +-- dist
|   +-- src
+-- other webapi application stuff
```
Though I did manage to modify the existing app to look in the routify dist folder, so that's working.

**Comment by jakobrosenberg** [comment]
@cslovell this has been added to to Routify. 
``routify -r path/to/output`` should do the trick, ``-r`` is shorthand for ``--routify-dir``.

Let me know if this works for you. 🙂
