### ISSUE TITLE
Since $context.route.path does noT exists anymore from v1.5 what is its equivalent?

### ISSUE THREAD

**Issue by eriknyk** [roxiness/routify#158]
Since $context.route.path does not exists anymore from v1.5 what is its equivalent?

Actually I have a url like `/users`, after refresh

I've tried replacing it with: `$contex.layout.path` and `$context.component.path`

however both are pointing to root url `/` and not `/users`

I've tried `$leftover` also, and it is blank :(

this was working fine using `$context.route.path` but after upgrade to v1.5 I cannot find an equiv.

Best regards.

**Comment by jakobrosenberg** [comment]
Hi @eriknyk, sorry about the late reply.

The $layout or $page helper might be what you're looking for.
``import {layout, page} from '@sveltech/routify'``

**Comment by eriknyk** [comment]
$page.path is what I was looking for, Thanks @jakobrosenberg
