### ISSUE TITLE
SSR/Prerender Issue WIth Firebase

### ISSUE THREAD

**Issue by alteredorange** [roxiness/routify#161]
I made a demo repo so you can see the issue: https://github.com/alteredorange/routifyssrissue.git 
If you clone the repo -> npm install -> npm run dev you'll see the SPA mode works fine, but SSR mode on port 5005 throws a ReferenceError: IDBIndex is not defined. It appears it's trying to access something server side that's only available in browser.  I've tried numerous things with the rollup config, but nothing has been able to solve the issue. Any help would be greatly appreciated, thanks!

_I'm aware my firebase credentials are in there, it's a test account, on a test plan, and I'll roll the api key as soon as the issue is resolved. It will make it easier to see the actual error._

**Comment by jakobrosenberg** [comment]
From what I can gather, it seems Firebase doesn't work with prerendering. It should however work with SSR in production. I have no experience Firebase, so I'm only able relay my impressions.

For what it's worth, it sounds like we might get an official Firebase template for Routify.

**Comment by alteredorange** [comment]
An official template would be great! In the meantime is there an easy way to disable prerendering so I could still deploy to Now?

**Comment by jakobrosenberg** [comment]
Have a look here. Brand new.

https://github.com/lpshanley/routify-starter-firebase

**Comment by jakobrosenberg** [comment]
Setting your environment variable PRERENDER to false, should also disable prerendering.

**Comment by alteredorange** [comment]
For now the best/easiest/possibly _only_ way of using all firebase modules (i.e. storage, analytics, messaging, etc.) with Routify is to use the CDN scripts. For future reference, just add them to your static index.html file in the head, like:

`   <script defer src="https://www.gstatic.com/firebasejs/7.14.2/firebase-app.js"></script>
    <script defer src="https://www.gstatic.com/firebasejs/7.14.2/firebase-analytics.js"></script>         <script defer src="./init-firebase.js"></script>`

and anything you need to pass pre-rendering, SSR (i.e. it will be called before firebase is loaded from the CDN), wrap in a   `if (typeof firebase !== "undefined") {} ` statement and you won't have any issues!
