### ISSUE TITLE
@types for hmr

### ISSUE THREAD

**Issue by timeshift92** [roxiness/routify#162]
**First rule of bug posting**
**There are no rules!**

#### With that out of the way, there are a few things that might help us help you faster. You pick and choose what you think is relevant.

**bug description**
Cat exploded in the microwave, but it was expected to dry.

**package.json**
The script section or even just the script you're running.

**version**
Routify, Svelte, etc. whichever you think might be relevant.

**screenshot**
Sometimes they help. Extra points for good memes.

Hello can you add d.ts  for hmr.js?

**Comment by jakobrosenberg** [comment]
Hi @timeshift92 that should be added/fixed in v1.5.13. (Will be released very soon)
