### ISSUE TITLE
SSR and GraphQL: how to avoid the loading state if no javascript is present (async calls rendering)?

### ISSUE THREAD

**Issue by frederikhors** [roxiness/routify#166]
I'm trying SSR (server-side-rendering) for the first time today.

I need to use it with NO-Javascript browsers along with standard ones.

In my Svelte/Sapper app I'm using GraphQL (Apollo, URQL or SVQL doesn't matter).

### QUESTION

Whatever the GraphQL client I choose I can't understand how to manage the loading of the call to the GraphQL endpoint.

I mean that since we are not in an environment where I can use the reactivity to an event to rewrite part of the DOM (I am rendering in the nodejs server) every time a user (or a bot: search engine) browses the site (without javascript) will only see the wait state for the GraphQL call: "Loading todos ...".

Am I brutally wrong?

### CODE EXAMPLE

```svelte
<script>
  import { initClient, query } from '@urql/svelte';

  initClient({ url: "https://0ufyz.sse.codesandbox.io" });

  const todos = query({
    query: `
      query {
        todos {
          id
          text
          complete
        }
      }
    `
  });
</script>

{#if $todos.fetching} <!-- This is the only state I see in my server rendered response -->
  Loading todos...
{:else}
  <ul>
    {#each $todos.data.todos as todo}
      <li>{todo.text}</li>
    {/each}
  </ul>
{/if}
```

Even if I manage to wait for the GraphQL response in the express server and to render the data instead of the loading message, the problem is that the times are much longer (if the GraphQL endpoint is slow) and the user experience is depressing, especially for the standard user with the browser and javascript.

Maybe I am missing something in the reasoning.

But what?

Maybe we can "differentiate" users based on some headers values.

_I was discussing this in Discord with @jakobrosenberg._

**Comment by alteredorange** [comment]
Have you tried node fetch? It should work with SSR.

**Comment by jakobrosenberg** [comment]
As I recall, the issue is about prefetching data for search engines while doing gradual hydration on the client.

**Comment by JustinVoitel** [comment]
@frederikhors I´ve been experimenting with routify & urql/svelte and could achieve good results making a condition if you are currently in node or in the browser of the client as showed in #149 
```javascript
<script>
  import { initClient, query } from '@urql/svelte';

  initClient({ url: "https://0ufyz.sse.codesandbox.io" });

  let todos;

  function getData() {
      return query({
         query: _YOURQUERY_,
      })
   }

  // this is where you check if you are running in node or client browser
  $: todos = !navigator.userAgent.match('jsdom')
    ? todosQuery()
    : readable({ fetching: true }) //initial value of todos

</script>

{#if $todos.fetching}
  Loading todos...
{:else}
  <ul>
    {#each $todos.data.todos as todo}
      <li>{todo.text}</li>
    {/each}
  </ul>
{/if}
```
Tell me if it works for you or if you came to a better approach :D

**Comment by jakobrosenberg** [comment]
The 1.8 beta supports service workers and offline availability. It won't solve the first visit, but all subsequent visits will be served by a service worker.

You can also bypass SSR for humans by editing the the relevant file. Ie. for Vercel, you would edit `scripts/now/api/ssr.js`.

Before
```javascript
module.exports = async (req, res) => {
    const html = await ssr(template, script, req.url)
    res.send(html + '\n<!--ssr rendered-->')
}
```

After
```javascript
module.exports = async (req, res) => {
    const html = ssrCondition ? await ssr(template, script, req.url) : template 
    res.send(html)
}
```
