### ISSUE TITLE
gatsbyjs and sapper comparison

### ISSUE THREAD

**Issue by janat08** [roxiness/routify#173]
Here are features of gatsbyjs, which of these are missing https://github.com/sveltejs/sapper/issues/1093
 Pre-rendered HTML
Automatic Code Splitting
Follows PRPL-pattern
Smart link prefetching
Progressive Images
Plugin architecture
"Bring your own data"
Graphql layer
Incremental builds

**Comment by jakobrosenberg** [comment]
Could you list the features?

**Comment by janat08** [comment]
Updated, but therere bunch of others listed.

**Comment by Wolfr** [comment]
What's the point of this thread? @jakobrosenberg I don't have mod rights but if I had I would close this.

**Comment by janat08** [comment]
I'll indulge you
