### ISSUE TITLE
Route Change prevent scroll to top

### ISSUE THREAD

**Issue by OmG3r** [roxiness/routify#178]
Hello, I have a Route that has 3 non-required parameters to operate
ex: browse/[p1]/[p2]/[p3]

all of the 4 routes (browse/, browse/[p1], browse/[p1]/[p2], browse/[p1]/[p2]/[p3]) operate using one unified component (index.svelte simply imports the components and uses it)

my issue is: when i programmatically change the route by adding one of the parameters, the SPA scrolls to the top even tho am still in the same component. i change the route with `history.replaceState({}, null, newUrl)`

The solution i'd like: is an option to prevent scrolling to the top when the route is updated

**Comment by Wolfr** [comment]
This is an option in Routify but not sure if this still works:

```
<div data-routify="scroll-lock">
   <!-- content you don't want scrolled back to the top -->
</div>
```

We should probably add this to the docs.

**Comment by OmG3r** [comment]
Thank you it worked, and yes please do add it to the documentation.
