### ISSUE TITLE
Ability to set urls to export when running 'yarn export'

### ISSUE THREAD

**Issue by olliecamp** [roxiness/routify#179]
**Is your feature request related to a problem? Please describe.**
Ability to provide a list of urls to export when calling `yarn export`. 

**Describe the solution you'd like**
To be able to specify specific urls to include and/or specific urls to exclude in the exporting process.

**Comment by jakobrosenberg** [comment]
How do you feel about a scope level option like
```
<!-- routify:options prerender=false -->
```

**Comment by jakobrosenberg** [comment]
Closed due to inactivity.
