### ISSUE TITLE
Monorepo - separating the core builder, the rollup plugin and the runtime module

### ISSUE THREAD

**Issue by matthewrobb** [roxiness/routify#18]
I am interested in assisting with this if it's something you'd like to do, please let me know @jakobrosenberg

**Comment by jakobrosenberg** [comment]
Hi Matthew, I'll take any help I can get. 🍻

Can you elaborate on what you mean by separating core builder from the runtime module?

**Comment by matthewrobb** [comment]
Everything in src would likely remain as one package where as the node module as it is currently would make sense split into two modules, one containing the core logic of building the generated routes from input options and the other a light consumer of that module as a rollup-plugin. Should open the door for adding a webpack loader or parcel plugin fairly easily as well.

**Comment by jakobrosenberg** [comment]
Yes, Rollup support is getting either abstracted or removed. Did you mean to abstractions beyond that?

**Comment by jakobrosenberg** [comment]
Closing for now. Will reopen for further discussion if needed.
