### ISSUE TITLE
Multilanguage URI is possible?

### ISSUE THREAD

**Issue by rigu** [roxiness/routify#183]
Hello,
There is a way to have different URL for the same page, something like URI alias?
Will be useful for multi language site

**Comment by alesvaupotic** [comment]
We discussed this yesterday on discord and I have just now found this discussion. Should have been more thorough in my research before asking there. I am not opening another issue, rather support the ideas presented here. Integration with svelte-i18n seems straightforward.

**Comment by ghostdevv** [comment]
Updates on this? @jakobrosenberg

**Comment by jakobrosenberg** [comment]
If we move it to discussions. Aliases is definitely something we should support, one way or another.

The new `$components` helper can be helpful here as well. I Might see if I can create an example that uses `$components`.

**Comment by ulvidamirli** [comment]
Any news on this? @jakobrosenberg

**Comment by jakobrosenberg** [comment]
Not yet, @ulvidamirli .

**Comment by manutheblacker** [comment]
Any news on this?

**Comment by jakobrosenberg** [comment]
My best suggestion is to run `npx stackmix` and select the i18n example for multilanguage URI. The example uses the urlTransform option for localization.

The runtime example above can also be used. Here's a small modification of it that allows regex in the dictionary
```html
<script>
import { Router } from '@roxiness/routify'
import { routes } from '../.routify/routes'

/** Danish dictionary example.
* You would probably want to fetch the dictionary based on browser setting,
* basepath or a root parameter (`/[lang]/some/page.svelte`) */
const dictionary = {
  "^/about$": "/om", //this would translate `/about` => `/om` but not `/store/about`
  "/news": "/nyheder",
  "/contact": "/kontakt",
  "/store/news": "/butik/nyt", //translate based on context
};

const reDict = Object.entries(dictionary).map(([source, target]) => ({
  regex: new RegExp(source, "g"),
  target,
}));

const translateRegex = route => 
  reDict.forEach(({regex, target}) => (route.regex = route.regex.replace(regex, target)))

routes.forEach(translateRegex)
</script>

<Router {routes} />
```
