### ISSUE TITLE
Can `routes` be exported from `@sveltech/routify` instead of `@sveltech/routify/tmp/routes`? 

### ISSUE THREAD

**Issue by ukalwa** [roxiness/routify#184]
Importing routes from a path that has `tmp` (assuming temporary) looks to me like this is an experimental feature and can be removed in the future. Is that the case? or does tmp mean something else other than temporary?

I am using this module in my projects and have seen other people using it in theirs. If this module is experimental or will be removed in the future, I think it would result in a breaking change for me and others using it. And users should be made aware by mentioning about it in the docs.

But if it is part of the stable release, can the source be modified in such a way that it is imported from `@sveltech/routify` or `@sveltech/routify/routes`?

**Comment by jakobrosenberg** [comment]
Hi @ukalwa 

You can change the output folder with the `routifyDir` parameter. Ie. `routify --routify-dir routify` (this would create a routify folder in your current working dir).

The location is called tmp as files in that folder aren't persistent. Ie. They change according to your folder structure. Same way as you have tmp folders in your OS that handle generated files.

In old versions (Svelte-filerouter) the import used to look like this.
```javascript
<script>
  import { Router } from '@sveltech/routify'
</script>

<Router  />
```

But for sake of transparency and control we changed it to this

```javascript
<script>
  import { Router } from '@sveltech/routify'
  import { routes } from '@sveltech/routify/tmp/routes'
</script>

<Router {routes} />
```

Ultimately routes.js is continuously generated, updated and deleted throughout the life-cycle of a project. The `tmp` convention best helps convey that, IMO.

Is there a reason you associate temporary folders with experimental features?

**Comment by ukalwa** [comment]
Ahh, I didn't know that `routes.js` would be continuously updated based on the folder structure. Putting it in `tmp` folders makes sense now. I am not sure if this point is mentioned in the docs but I think it may be a good idea to put it in there.

I don't generally associate temporary folders with experimental features. But I saw this in the  README file and somehow I came to the conclusion that "change and evolve" refers to "experimental" APIs/features 🤷‍♂️ 

> Warning: Routify is a work in progress. Since v1.5 we have a stable release. But this is a relatively young project. You can expect it to change and evolve.

**Comment by jakobrosenberg** [comment]
Great point about the documentation. There's a level of contradiction in that warning.

Routify should be stable. Same goes for documented features. We won't document features unless they're considered stable or marked as experimental.
