### ISSUE TITLE
Initialising and updating dynamic routes

### ISSUE THREAD

**Issue by frantic0** [roxiness/routify#186]
Hello, 

I'm trying to set a dynamic route where segments of the URL are bound to a store

`<li><a href="/tutorial/{$selected chapter_dir}/{$selected.section_dir}/">Tutorial</a></li>`

That store can have objects like this
```
$selected = {
  slug: "basics",
  title: "Basics",
  chapter_dir: "01-basics",
  section_dir: "01-introduction"
}
```

that can change in run time depending on user interaction and that keeps the previous navigation state between navigation to that route.

Everything seems to work well except in the case of initialisation of the program and first navigation.  

In that case the value of `$selected.chapter_dir` and `$selected.section_dir` are `undefined`. 

I tried different ways to set the URL 
`<li><a href="/tutorial/{chapter_dir}/{section_dir}/">Tutorial</a></li>`

```
$selected = { 
  slug: "basics",
  title: "Basics",
  chapter_dir: "01-basics",
  section_dir: "01-introduction"
};

$: chapter_dir = $selected.chapter_dir;
$: section_dir = $selected.section_dir;

onMount( async () => {
    $tutorials = await preload();
    $selected = $tutorials[0];
}
```

I guess that because Routify generates the routes in build time there is something missing here...

How can I initialise that route with hard-coded values but maintain it reactive as it is now? Is there any configuration trick that I'm missing? 

Many thanks

**Comment by frantic0** [comment]
I just tried using the routify's `url` helper but the behaviour is the same 

if I hardcode the params like 
```
<li><a href={$url('/tutorial/:chapter/:section/', {chapter: '01-basics', section: '01-introduction'})}>Tutorial</a></li>
```
I lose maintenance of state

if I make the params dependent on reactive assignments  
```
<li><a href={$url('/tutorial/:chapter/:section/', {chapter: '01-basics', section: '01-introduction'})}>Tutorial</a></li>
```
first navigation gets undefined values on the route...

Any ideas?

**Comment by jakobrosenberg** [comment]
@frantic0 I'm not sure I follow. Do you have a repo you can share?

And could you do a step by step of what you do and what you expect?

Also, onMount has no functionality in Routify.

**Comment by frantic0** [comment]
hi @jakobrosenberg, the repo is here https://github.com/mimic-sussex/sema 

in this project, the navigation routes are in `/client/routes/`. Among the top-level routes in `_layout.svelte` the root element, there is one dynamic route 

```
<li><a href={$url('/tutorial/:chapter/:section/', {chapter: chapter_dir, section: section_dir})}>Tutorial</a></li>
```

The `chapter_dir` and `section_dir` params of that route are reactive and bound to a store, but routify generates the `/tutorial/:chapter/:section/` route with undefined parameter values.

It works well when I navigate between the nested routes (e.g. `http://localhost:8080/tutorial/01-basics/04-widgets/` and `http://localhost:8080/tutorial/01-basics/01-introduction/`).

However, I can't seem to be able to set the param values for the first navigation, when I load the app. 

I would expect to have that route initialised with some default parameters. 

onMount is used to update the params.

**Comment by jakobrosenberg** [comment]
I'm still not sure what the issue is. I tried cloning your repo, but couldn't get it to run. I assume I need to run additional backend services.

Could you provide a small repo and/or a step by step clarification of what the issue is?

**Comment by jakobrosenberg** [comment]
I'm not sure if this is what you're looking for
```javascript
const defaults = {chapter: 'defaultChapter', section: 'defaultSection'}
$url('/tutorial/:chapter/:section/', {...defaults, ...$params})
```

**Comment by frantic0** [comment]
thanks @jakobrosenberg, 

I didn't know we could pass default values to `$url` like so. I gave it a try, but the behaviour is not what I expected... 

Here's a repo with the issue on isolation:
https://github.com/frantic0/routify-select-api.git

There are 3 Tab routes and 2 Tutorial routes. We are testing the different behaviours of the Tutorial routes with the same procedure.

The step-by-step procedure for Tutorial 1:
1. Load the application
2. Click on Tutorial 1
3. Notice that URL is `http://localhost:8081/tutorial/undefined/undefined/` (PROBLEM)
4. Select from Tutorial Content option 3 Machine Learning – Introduction
5. Notice that URL is http://localhost:8081/tutorial/03-machine-learning/01-introduction/
6. Click on Tab 2
7. Click on Tutorial 1 again
8. Notice that URL is http://localhost:8081/tutorial/03-machine-learning/01-introduction/ (DESIRED BEHAVIOUR, State of navigation is maintained)

The step-by-step procedure for Tutorial 2:
1. Reload the application.
2. Click on Tutorial 2
3. Notice that URL is `http://localhost:8081/tutorial/01-introduction/01-basics/` (DESIRED BEHAVIOUR)
4. Select from Tutorial Content option 3 Machine Learning – Introduction
5. Notice that URL is http://localhost:8081/tutorial/03-machine-learning/01-introduction/
6. Click on Tab 2
7. Click on Tutorial 2 again
8. Notice that URL is http://localhost:8081/tutorial/03-machine-learning/01-introduction
(PROBLEM, state of navigation is NOT maintained)

If you have a look to client/pages/_layout.svelte you'll find  

`<li><a href="/tutorial/{$selected.chapter_dir}/{$selected.section_dir}/">Tutorial 1</a></li>`

`<li><a href={ $url('/tutorial/:chapter/:section/', { ...defaults, ...$params } ) }>Tutorial 2</a></li>`

The problem here is that passing defaults makes Tutorial 2 route fixed and everytime it is revisited it has the default. Instead my use case needs to maintain state of navigation which dependent on param values of the last navigation to a certain parameterised subroute, which might be reactive statement or a store.

My question is, is this by design or bug? I there anyway I can have both the desired behaviours above or any possible way to do it?

**Comment by frantic0** [comment]
I found the bug for the first scenario... (－‸ლ)

**Comment by jakobrosenberg** [comment]
This is neither by design or a bug, but simply how reactivity works. $params are the parameters from the URL. As you navigate your site, $params changes to reflect the current URL.

When you navigate to a page with no parameters, $params will be empty. If it weren't it would be broke as it would carry stale data.

In your case, you want it to only update your state when it has the desired parameters - ie. it should only update when you're navigating tutorials.

```javascript
  // set defaults
  let persistentParams = { chapter: '01-introduction', section: '01-basics' }
  // update url parameters only when navigating tutorials
  $: if($params.chapter && $params.section) persistentParams = $params
```

```html
<a href={ $url('/tutorial/:chapter/:section/', persistentParams ) }>Tutorial 2</a>
```

**Comment by frantic0** [comment]
Thank you @jakobrosenberg, it makes sense.
