### ISSUE TITLE
Capture excerpts from files

### ISSUE THREAD

**Issue by jakobrosenberg** [roxiness/routify#190]
![image](https://user-images.githubusercontent.com/4153004/82750988-74f35680-9db4-11ea-858e-1040203e16e5.png)

Captures would be accessible through meta.
Ie. `meta.summary` would return:
```
Welcome to the brand-new Routify blog. This is not just the first blog post on Routify, but also my first ever blog post. Scary. For this cherry-popping first-post, we’re very happy to announce that 1.5 is finally ready. Among the highlights in this version are:

- [Support for meta tags](#meta-tags-and-open-graph)
- [Dynamic basepaths](#dynamic-basepaths)
- [Automatic navigation](#automatic-navigation-with-layout-and-page-helpers)
- [CLI enhancements](#cli-enhancements)
- [Query support](#query-support)
- [Improved starter template](#improved-starter-template)
```

Extract tags
- captures the content above them and saves the content to meta, using the provided name
- are delimiters. So any capture will stop at the next extract tag.
- without a name would be discarded to help reduce bundle size.

**Comment by rixo** [comment]
Interesting idea! Dev docs oriented feature?

I think you should reserve a whole namespace for captures so, instead of `meta.summary`, rather something like `meta.$$.summary` or `meta.capture.summary`.

**Comment by jakobrosenberg** [comment]
The capture idea is aimed for blogs where you want the top part as a summary. However the ability to split a file into multiple chunks and name them is aimed for dev docs. But there could also be situations where you wanted multiple chunks from a markdown file to be included in a summary.

As for name spacing. We could maybe do something like:
```
<!-- routify: extract summary.?part1 -->
```

**Comment by Wolfr** [comment]
This is awesome.

**Comment by jakobrosenberg** [comment]
Someone mentioned on discord that this would be well suited for a plugin, which I agree with.

**Comment by ghostdevv** [comment]
Can this be closed? @jakobrosenberg

**Comment by jakobrosenberg** [comment]
If we move it to discussions instead. This is something I'd still like to do :)

**Comment by ghostdevv** [comment]
Oki
