### ISSUE TITLE
Transition thing

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#194]
https://github.com/sveltech/routify/blob/99c242fc334d99e5f892828e29d045bafc8bbed4/runtime/decorators/BaseTransition.svelte#L51

I was debugging something - had some weird transition issues - and I wondered what the purpose of this line is, is it to hide the thing completely? Because then it should be 100% instead.

I can explain what I ran into later :)

(You can see the bug at 6 seconds in this video http://dropzone.johanronsse.be/video.mp4 )

![image](https://user-images.githubusercontent.com/12690/83303017-a2009880-a1fc-11ea-9a0f-4e656b5bad40.png)

**Comment by Wolfr** [comment]
Also, if the function sets things to fixed, shouldn't the function be called `setFixed`?

**Comment by jakobrosenberg** [comment]
To be honest, I can't remember the logic behind -50% but it looks like we should consider removing it.

It would make sense to rename the function. Originally it used absolute positioning, but it caused too many issues.

**Comment by jakobrosenberg** [comment]
We fixed this, right?

**Comment by Wolfr** [comment]
Well yes and no, you removed the 50% thing which caused a bug, but I didn't test it further. I will log a new issue if I encounter one ;)
