### ISSUE TITLE
Connect to backends written in other languages

### ISSUE THREAD

**Issue by pjebs** [roxiness/routify#195]
Many companies have distinct backend and frontend teams.

My company's backend team uses Go and they have built up a lot of expertise and experience. It's also arguably better than Node.js.

Is it possible to hook up this project so that it can connect to a backend written in a different language for server-based routes?

**Comment by Wolfr** [comment]
Routify is a routing framework. The Routify starter provides a frontend template based on Svelte.

Of course you can connect it to a backend written in any language, but you need a way for the Javascript to receive the data so it can be displayed in the frontend. This is usually done in the form of calls to an intermediary e.g. a REST api.

**Comment by pjebs** [comment]
It's this package hash based routing?

**Comment by Wolfr** [comment]
Routes are based on files in the file system.

**Comment by jakobrosenberg** [comment]
Hi @pjebs, Routify is a frontend library and you can use any backend you like. We do not use hash based routing. Instead hashes are reserved for anchor links.
