### ISSUE TITLE
Nested parameterized routes ignore base

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#2]
pages/ <-- blank page
--> _layout.svelte
--> index.svelte

pages/[org] <-- blank page
--> _layout.svelte
--> index.svelte

pages/[org]/[group] <-- only deepest level is showing
--> _layout.svelte
--> index.svelte

**Comment by tombroens** [comment]
[Error] Error: Route could not be found. Make sure /.svelte or //index.svelte exists. A restart may be required.
	updatePage (bundle.js:822:152)
	navigator (bundle.js:845)
	instance$4 (bundle.js:1377)
	init (bundle.js:288)
	Router (bundle.js:1394)
	create_fragment$5 (bundle.js:1404)
	init (bundle.js:301)
	App (bundle.js:1445)
	(anonymous function) (bundle.js:1450)
	Global Code (bundle.js:1457)

**Comment by jakobrosenberg** [comment]
Hi @tombroens 

Do your _layout.svelte files feature a ``<slot />``?

**Comment by tombroens** [comment]
Yes all have.... It seems that sub-folders without a layout are loaded.

**Comment by jakobrosenberg** [comment]
Did you try a restart ``npm run dev``?

**Comment by tombroens** [comment]
Yes I do that regularly, no fix :-(

**Comment by jakobrosenberg** [comment]
Any chance I can see a repo?

**Comment by jakobrosenberg** [comment]
Also, can you give me a specific example of an URL that doesn't work?

**Comment by tombroens** [comment]
https://github.com/tombroens/sveltefileroutertest

**Comment by jakobrosenberg** [comment]
I was unable to replicate your error.

localhost:5000/microsoft/windows/notepad
https://nimb.ws/czqH1X

What browser do you use?

**Comment by tombroens** [comment]
really?? if you go to root './' you see the layout and it says 'hello from root!'?

http://localhost:5000/ is NOT working
http://localhost:5000/123 is NOT working
http://localhost:5000/123/456 is working
http://localhost:5000/123/456/789 is working

**Comment by jakobrosenberg** [comment]
I had to hit F5 once to see the layout. Probably cause my own projects are cached on localhost:5000

https://nimb.ws/6MnvsA
https://nimb.ws/qJUexF

Is that what it's supposed to look like?

**Comment by tombroens** [comment]
Yes that is what it should look like.... very strange, I can hit F5 or in my case cmd-r whatever I want but it is not showing.... in Chrome and Safari

**Comment by jakobrosenberg** [comment]
Just to try something, how about ``http://127.0.0.1:5000/``?

**Comment by tombroens** [comment]
Nope... still: navigator.js:30 Uncaught Error: Route could not be found. Make sure /.svelte or //index.svelte exists. A restart may be required.
    at updatePage (navigator.js:30)
    at navigator (navigator.js:53)
    at instance$5 (Router.svelte:7)
    at init (index.mjs:1274)
    at new Router (Router.svelte:7)
    at create_fragment$6 (Router.svelte:7)
    at init (index.mjs:1287)
    at new App (Router.svelte:7)
    at main.js:3
    at main.js:6

**Comment by tombroens** [comment]
Could this be a win vs. mac kind of file path issue in the compile?

**Comment by jakobrosenberg** [comment]
That's what I thought at first, but the error is showing the path received from window.location.pathname.

Come to think of it, you have probably have a trailing slash in your URL - iirc there are some technical limitations which forced me to remove trimming of hanging slashes.

I'll have a look at it tomorrow and see if I can reimplement the trimming.

**Comment by jakobrosenberg** [comment]
No, that shouldn't be an issue either. The regex match should work despite trailing slashes.

**Comment by jakobrosenberg** [comment]
Could you add this to a _layout.svelte file and post the results? I'll have a look in the morning then :)

```
<script>
  let sidebar_open = false;
  export let routes
  console.log (routes)
</script>
```

**Comment by jakobrosenberg** [comment]
It should look like this:

```
0: {layouts: Array(1), path: "/index", regex: "^/index", name: "/index", component: ƒ, …}
1: {layouts: Array(2), path: "/[org]/index", paramKeys: Array(1), regex: "^/([^/]+)/index", component: ƒ, …}
2: {layouts: Array(2), path: "/[org]/[group]/index", paramKeys: Array(2), regex: "^/([^/]+)/([^/]+)/index", component: ƒ, …}
3: {layouts: Array(2), path: "/[org]/[group]/[program]/index", paramKeys: Array(3), regex: "^/([^/]+)/([^/]+)/([^/]+)/index", component: ƒ, …}
```

**Comment by tombroens** [comment]
http://localhost:5000/
Route could not be found.

http://localhost:5000/123
Route could not be found.

http://localhost:5000/123/456
```
0: {layouts: Array(2), path: "/[org]/[group]/index", paramKeys: Array(2), regex: "^/([^/]+)/([^/]+)/index", component: ƒ, …}
1: {layouts: Array(2), path: "/[org]/[group]/[program]/index", paramKeys: Array(3), regex: "^/([^/]+)/([^/]+)/([^/]+)/index", component: ƒ, …}
length: 2
```

http://localhost:5000/123/456/789
```
0: {layouts: Array(2), path: "/[org]/[group]/index", paramKeys: Array(2), regex: "^/([^/]+)/([^/]+)/index", component: ƒ, …}
1: {layouts: Array(2), path: "/[org]/[group]/[program]/index", paramKeys: Array(3), regex: "^/([^/]+)/([^/]+)/([^/]+)/index", component: ƒ, …}
length: 2
```

**Comment by jakobrosenberg** [comment]
So it's not a route matching issue. The routes simply aren't there.

For whatever reason the files are not detected while traversing down the tree.  Could it be a ``chown`` or ``chmod`` issue? Can I ask what OS you're on?

**Comment by tombroens** [comment]
macOs

```
drwxrwxr-x   5 tombroens  staff  160 Oct 14 21:12 .
drwxrwxr-x  11 tombroens  staff  352 Oct 14 21:58 ..
-rw-r--r--   1 tombroens  staff   77 Oct 14 21:14 App.svelte
-rw-r--r--   1 tombroens  staff  114 Oct 11 13:34 main.js
drwxr-xr-x   5 tombroens  staff  160 Oct 14 21:38 pages

./pages:
total 16
drwxr-xr-x  5 tombroens  staff   160 Oct 14 21:38 .
drwxrwxr-x  5 tombroens  staff   160 Oct 14 21:12 ..
drwxr-xr-x  5 tombroens  staff   160 Oct 14 21:30 [org]
-rw-r--r--  1 tombroens  staff  1403 Oct 15 08:08 _layout.svelte
-rw-r--r--  1 tombroens  staff    24 Oct 14 21:38 index.svelte

./pages/[org]:
total 16
drwxr-xr-x  5 tombroens  staff  160 Oct 14 21:30 .
drwxr-xr-x  5 tombroens  staff  160 Oct 14 21:38 ..
drwxr-xr-x  4 tombroens  staff  128 Oct 14 21:51 [group]
-rw-r--r--  1 tombroens  staff  307 Oct 15 08:09 _layout.svelte
-rw-r--r--  1 tombroens  staff  112 Oct 14 21:25 index.svelte

./pages/[org]/[group]:
total 8
drwxr-xr-x  4 tombroens  staff  128 Oct 14 21:51 .
drwxr-xr-x  5 tombroens  staff  160 Oct 14 21:30 ..
drwxr-xr-x  3 tombroens  staff   96 Oct 14 21:47 [program]
-rw-r--r--  1 tombroens  staff  107 Oct 14 21:39 index.svelte

./pages/[org]/[group]/[program]:
total 8
drwxr-xr-x  3 tombroens  staff   96 Oct 14 21:47 .
drwxr-xr-x  4 tombroens  staff  128 Oct 14 21:51 ..
-rw-r--r--  1 tombroens  staff  111 Oct 14 21:48 index.svelte
```

**Comment by jakobrosenberg** [comment]
I created a container on PaizaCloud and I'm now able to replica the error.

I'll see if I can pinpoint the issue and release a fix.

**Comment by tombroens** [comment]
Thanks for your help! That would be great. 

It seems the layout is preventing to find the route. If I move the nested layout to other folders, the invisibility of the route moves with it.

**Comment by jakobrosenberg** [comment]
Found the bug. ``npm i -D svelte-filerouter`` should fix it.

The function that sorts files ate the index.svelte if it came after _layout.svelte.

Thanks for pointing out the bug!  👍

**Comment by tombroens** [comment]
Yes, great! Thanks.
