### ISSUE TITLE
params not exactly right for duplicate querystring params

### ISSUE THREAD

**Issue by longrunningprocess** [roxiness/routify#201]
Thank you for loading qs params into `params`, that is quite simple and much appreciated!

**bug description**
duplicated querystrings (`?a=1&a=2&a=3`) are not being loaded into `params` properly

**version**
sveltech/routify@1.7.12 

**example**
```javascript
<script>
import { params } from '@sveltech/routify'
import qs from 'qs'
</script>

<pre>{JSON.stringify($params, null, 2)}</pre>
<pre>{JSON.stringify(qs.parse(location.search), null, 2)}</pre>
```
![image](https://user-images.githubusercontent.com/4412848/83470155-88a35a80-a44f-11ea-810e-9c25263c67e7.png)

**requested fix**
Please load those dupes into an array, thanks!

**Comment by colinbate** [comment]
Looking at the code, I believe you can override this yourself by passing an object to the `<Router />` config param with the key `queryHandler`. That key should reference an object with parse and stringify methods.

```jsx
<Router config={{queryHandler: {parse: qs.parse, stringify: qs.stringify}}} />
```

Not saying this shouldn't be fixed, but this may help in the interim.

**Comment by jakobrosenberg** [comment]
Apologies. I thought the queryHandler was documented. I'll get right on it.

The default queryHandler is meant to be as barebone as possible with no dependencies, hence:
```javascript
queryHandler: {
    parse: search => fromEntries(new URLSearchParams(search)),
    stringify: params => '?' + (new URLSearchParams(params)).toString()
}
```

For more advanced use, you can use a library like [qs.](https://github.com/ljharb/qs)

```javascript
import { parse, stringify } from 'qs'
const queryHandler = { parse, stringify }
```
```html
<Router config={{queryHandler}} />

**Comment by longrunningprocess** [comment]
ok, that's fine...I was appealing to your "batteries included" mentality but I can certainly pull `qs` in to handle it.

fwiw, I'd prefer to see this done in routify either simply by using `URLSearchParams.getAll` or just just using `qs`...otherwise every project is going to be adding @colinbate 's line above...feels very "boilerplate"-y to me.

At any rate, thanks for taking a look and congrats on your all's new **HYPE** 🥇 , please feel free to close if you decide against my request.

**Comment by jakobrosenberg** [comment]
Well, I do have a soft spot for including batteries. 😄 That said, I do try to weigh the potential • complexity, • size, • lock-in and • dependencies against the benefits that each "battery" might bring.

However if you have a proposal for a healthier default queryHandler, I'd be happy to replace the existing one.

**Comment by longrunningprocess** [comment]
:-D I can appreciate that!

a custom implementation is going to look something like this (ref: https://stackoverflow.com/questions/8648892/how-to-convert-url-parameters-to-a-javascript-object#answer-52539264):
```
const groupParamsByKey = (params) => [...params.entries()].reduce((acc, tuple) => {
 // getting the key and value from each tuple
 const [key, val] = tuple;
 if(acc.hasOwnProperty(key)) {
    // if the current key is already an array, we'll add the value to it
    if(Array.isArray(acc[key])) {
      acc[key] = [...acc[key], val]
    } else {
      // if it's not an array, but contains a value, we'll convert it into an array
      // and add the current value to it
      acc[key] = [acc[key], val];
    }
 } else {
  // plain assignment if no special case is present
  acc[key] = val;
 }

return acc;
}, {});

const params = new URLSearchParams('abc=foo&def=%5Basf%5D&xyz=5&def=dude');
const output = groupParamsByKey(params) // {abc: "foo", def: ["[asf]", "dude"], xyz: 5}
```

It's a little complex for my tastes personally but I'd accept it if you weren't willing to give a little on the lock-in for `qs`.  I really like @jakobrosenberg 's solution as a default from `routify` but understand if you don't want a dependency on that library.  FWIW, that thing has been around for a long time and its use is pretty broad, I know we use it on all our projects.  I'd just be sad to see every future project doing that same override...another option would be to suggest it in the docs I suppose but come on man, `qs` lock-in isn't a big deal in my mind ;-)

No need to take anymore of your time, just let me know where you land on it, thanks!

**Comment by jakobrosenberg** [comment]
I brought it up with the team, but the consensus was that there's no strong need to prebundle a library that isn't universally needed and can be added with a oneliner.

``<Router config={{queryHandler: qs}} />``

**Comment by longrunningprocess** [comment]
np, thanks again for the conversation.

**Comment by longrunningprocess** [comment]
for future me's reference:
```
import { parse, stringify } from 'qs'

// added because of this:  https://github.com/sveltech/routify/issues/201
const queryHandler = {
    parse: params => parse(params, {ignoreQueryPrefix: true}),
    stringify
}
</script>

<Router {routes} config={{queryHandler}} />
```
