### ISSUE TITLE
_reset.svelte gets included for pages above it

### ISSUE THREAD

**Issue by happyteque** [roxiness/routify#212]
**bug description**
I have the default example/ folder inside my project, but am not using it. However, all the _reset.svelte template within it are bundled with _my_ pages. For example, src/pages/example/transitions/tabs/_reset.svelte has a body padding of 0

**package.json**
dev:dynamic

**version**
    "@sveltech/routify": "^1.7.12",
    "svelte": "^3.20.1"

**Comment by jakobrosenberg** [comment]
Sorry, I'm not sure I understand the issue Could you expand on it?

**Comment by Wolfr** [comment]
It would help to provide a repo or codesandbox fork to investigate the issue.

**Comment by happyteque** [comment]
I cannot reproduce anymore, closing.
