### ISSUE TITLE
realworld.io example

### ISSUE THREAD

**Issue by benmccann** [roxiness/routify#214]
I'm not sure if you have considered it or if it'd be high enough priority for you to work on, but I think it'd be really cool to see a RealWorld example on http://realworld.io. You could probably copy https://github.com/sveltejs/realworld as a pretty good starting point and update it to use Routify

If you're not familiar with realworld.io it's basically the same Medium clone implemented in a whole bunch of different languages for comparison.

**Comment by jakobrosenberg** [comment]
This sounds like something we should probably pursue. Do you know if they provide a hosted API?

**Comment by benmccann** [comment]
Yes, they do! 

The Sapper example uses it. If you visit https://realworld.svelte.dev/ you sill see a request to https://conduit.productionready.io/api/articles?limit=10&offset=0

E.g. https://github.com/sveltejs/realworld/blob/master/src/routes/article/%5Bslug%5D.svelte imports the `api` which is defined here: https://github.com/sveltejs/realworld/blob/master/src/node_modules/api.js

Hopefully most things could stay close to the same since Routify uses a file-based routing system very similar to Sapper. The main thing to change might be that you'd have to remove the Sapper imports `import { goto, stores } from '@sapper/app';`
