### ISSUE TITLE
Dyanmic paths inside folders for SPA

### ISSUE THREAD

**Issue by happyteque** [roxiness/routify#216]
**bug description**
See https://github.com/happyteque/routify-issue. It's basically the default app with an extra route inside feed/[id]

1. I have created a new project with routify. I run it with `npm run dev`. I navigate to one of the example files, the one using this route src/pages/example/transitions/tabs/feed/[id]/index.svelte
http://localhost:5000/example/transitions/tabs/feed/1/ in a browser. All is good; 1 gets translated to [id]
2. I now create a new file in the folder; [[id]/[name].svelte](https://github.com/happyteque/routify-issue/blob/master/src/pages/example/transitions/tabs/feed/%5Bid%5D/%5Bname%5D.svelte) I navigate to http://localhost:5000/example/transitions/tabs/feed/1/john - the file loads and it understands john -> [name]; however, it doesn't handle the [id] part anymore (if you run the spa, it is undefined)

Am I missing something or is this a bug? Thanks

**Comment by jakobrosenberg** [comment]
A parameterized file or folder accepts is parameter as a prop. To access all props, you need to use `$params`.

https://routify.dev/docs/helpers#params

**Comment by happyteque** [comment]
Oh brilliant, thanks
