### ISSUE TITLE
Support for using metatags outside routify

### ISSUE THREAD

**Issue by benmccann** [roxiness/routify#217]
I've seen a lot of people asking how to use meta tags in Svelte and Sapper. I think it'd be really cool if this were a library like `react-helmet` that you could use independently of Routify. I'd love to be able to point users to it as the de facto solution for meta tags in Svelte generally

**Comment by jakobrosenberg** [comment]
Our internal metatags library could for the most part be abstracted as a standalone package. The biggest problem is figuring which tags take precedence when tags are declared in multiple components. In Routify that's handled by queuing all synchronous meta declarations and sorting them by path lengths of the components applying them, before writing the metadata. I'm not sure how that would be handled outside of Routify.

It could possibly be handled by setting the priority manually. However, I'm not sure I can take on additional projects atm.

**Comment by benmccann** [comment]
I'm not quite sure I understand what components there are. I imagine you might set metatags in a layout or in an individual page that would take precedence. It sounds like you're also taking into account more complicated scenarios though?

Here's another solution I've seen, which seems pretty decoupled from routing: https://github.com/sveltejs/sapper/issues/1264#issuecomment-643709274

**Comment by benmccann** [comment]
I just looked at the implementation. It seems pretty tied to Routify
https://github.com/sveltech/routify/blob/master/lib/middleware/assignMeta.js
