### ISSUE TITLE
Examples aren't linked from docs

### ISSUE THREAD

**Issue by benmccann** [roxiness/routify#219]
When I click "Examples" at the top of the page I don't see anyway to get to https://example.routify.dev/example

**Comment by jakobrosenberg** [comment]
You mean a link to the example app from the main website? If so, that's a great idea.

**Comment by benmccann** [comment]
Yeah. I wouldn't have found it except you had mentioned it in another ticket. I went to the website to try and find it again and couldn't until I went back to the ticket

**Comment by jakobrosenberg** [comment]
I'll see if we can get this fixed.

**Comment by Wolfr** [comment]
Seen this, but still in mega busy times.

**Comment by jakobrosenberg** [comment]
Fixed.
