### ISSUE TITLE
parameters question

### ISSUE THREAD

**Issue by benmccann** [roxiness/routify#220]
I was wondering if you could clarify what a global parameter is? [The docs](https://routify.dev/guide/introduction/parameters) say "To access all parameters from anywhere", but I'm not quite sure what this means

**Comment by kevmodrome** [comment]
It means that you can get all the parameters used on the current route using the `$params` helper - without it you wouldn't be able to get to the parameters from anywhere but the page you're currently on.

**Comment by benmccann** [comment]
Thanks for taking the time to respond! I'm afraid I'm still a little confused. What's the difference between "the current route" and "the page you're currently on"?

**Comment by kevmodrome** [comment]
I see now how that looks extremely confusing, haha! So like this, say you have a modal that you have in a completely different part of your application but you still want it to have access to whatever params are showing - you can use the params helper to display these here, without having to pass them manually to the modal, if that makes sense?

**Comment by kevmodrome** [comment]
Another example might be if you have a component completely separate to your routes that does different things depending on what params are "active"

**Comment by jakobrosenberg** [comment]
Say you have the path `/blog/[category]/[post].svelte` and you visit the page `/blog/kittens/whiskers?page=2`

From any component within Routify you can then do 
```javascript
import {params} from '@sveltech/routify'
console.log($params)
// { category: "kittens", post: "whiskers", page: "2" }
```

This is opposed to `export let post` which is only available in `/blog/[category]/[post].svelte`.

**Comment by benmccann** [comment]
That makes sense. Thanks!!
