### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by happyteque** [roxiness/routify#221]
I have created a project with Routify. When I run `npm run export` I get

UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
Exporting to: dist
(node:73568) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported

The code that seems to cause it is ssr.js

```
    return new Promise(async (resolve, reject) => {
        try {
            const dom = await new JSDOM(template, { runScripts: "outside-only", url: host + url })
            dom.window.scrollTo = () => { }
            dom.window.requestAnimationFrame = () => { }
            dom.window.fetch = fetch
            dom.window.addEventListener(eventName, async () => {
                afterEval(dom)
                const html = dom.serialize()
                dom.window.close()
                resolve(html)
            })
            await beforeEval(dom)
            if (meta) setMeta(dom, meta)
            dom.window.eval(script) <------ THIS LINE
```

**Comment by jakobrosenberg** [comment]
Hi @happyteque, do you know what URL it's trying to resolve?

**Comment by happyteque** [comment]
Nope. I am just running `npm run export` out of the box

**Comment by jakobrosenberg** [comment]
Are you trying to import a `json` or `js` file from your static folder?

**Comment by happyteque** [comment]
Oh yeah I am doing that... is that not possible?

**Comment by jakobrosenberg** [comment]
It is at runtime, but not during build. Other options might available. If you pop by Discord, we'll see if we can find a solution.

**Comment by happyteque** [comment]
As per discord discussion, it looks like there is a (hacky) workaround - surround your .fetch requests with

    if (!navigator.userAgent.match('jsdom')) {
      var blah = await fetch(theURL).then(res => res.json()));
   }

**Comment by jakobrosenberg** [comment]
Just to clarify.

To skip a request in SSR:
```javascript
if (routify.inBrowser)
  fetch(...)
```

To request a local asset in SSR:
```javascript
const data = await import ('<path to static>/file.js')
```
