### ISSUE TITLE
There's no route transition between identical routes with different parameters.

### ISSUE THREAD

**Issue by Evertt** [roxiness/routify#224]
When using `BaseTransition` to create smooth animated transitions between routes, it's currently impossible to create an animated transition when the old and the new route are the same routes except for their parameters.

So when you have `/pages/posts/[id].svelte` and you navigate from `/posts/1` to `/posts/2` then there's no way to make that animate.

It would be really nice to have that fixed.

**Comment by jakobrosenberg** [comment]
@Evertt how would something like this work for you?

```html
<!-- routify:options reload-on-param-change=true -->
```

**Comment by Evertt** [comment]
@jakobrosenberg are you saying that feature already exists? Or is that something you'd be willing to implement?

I imagine that that would work for me yes. :-)

**Comment by jakobrosenberg** [comment]
Doesn't exist yet, but have tried to implement it.

It manages to reload the components, but for some reason there's no transition.

**Comment by Evertt** [comment]
On Discord someone, maybe it was you, gave the tip that you can make a transition work using a weird `{#each}` hack. Something along the lines of:

```html
{#each [$url()] as _ ($url())}
    <div <!-- putting the transition parameters here -->>
        <slot />
    </div>
{/each}
```

Did you try something like that?

**Comment by jakobrosenberg** [comment]
That's most likely @rixo. 

We use a similar approach, where path is the index.
```html
    {#each [$context] as { component, componentFile } (component.path)}
```

**Comment by Grsmto** [comment]
Hey! Sorry to reply on this a year later.
I'm having the same issue, not sure to understand the hack provided, would you mind expanding a bit on how to apply that?

For now I implemented the transition by wrapping my page with a Svelte block (`{#key id /}` to manually trigger the transition when url param changes. But I would rather use the built in `BaseTransition` instead if I can.

Thanks!

**Comment by jakobrosenberg** [comment]
Hi @Grsmto , can you try `param-is-page` or `query-param-is-page`?

example
```html
<!-- routify:options param-is-page -->
```

https://routify.dev/docs/metadata

**Comment by ajl0023** [comment]
I'm experiencing a similar issue, where when i navigate to '/' => '/test' for example, i cant seem to get the send and receive transition to work. I'm trying to replicate something similar to the modal(animated) example, but the transition seems to only work when i use the $context store or `<!-- routify:options preload=true -->`  in the __layout. I've also included both 
`param-is-page` and `query-param-is-page`, but still nothing.
