### ISSUE TITLE
Route could not be found

### ISSUE THREAD

**Issue by Zyles** [roxiness/routify#226]
**bug description**

Trying to use basepath results in a build error.

**package.json**
```
{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
    "dev": "run-p routify rollup",
    "dev:nollup": "run-p routify nollup",
    "dev-dynamic": "cross-env BUNDLING=dynamic npm run dev",
    "build": "npm run routify -- -b && rollup -c",
    "serve": "spassr --serve-spa --serve-ssr",
    "export": "routify export",
    "build:docker": "npm run build && ./scripts/docker/docker-build.sh",
    "deploy:now": "cd scripts/now && npm run deploy",
    "deploy:netlify": "cd scripts/netlify && npm run deploy",
    "rollup": "rollup -cw",
    "nollup": "nollup -c",
    "routify": "routify -D"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^13.0.0",
    "@rollup/plugin-node-resolve": "^8.1.0",
    "concurrently": "^5.2.0",
    "cross-env": "^7.0.2",
    "del": "^5.1.0",
    "nollup": "^0.12.0",
    "npm-run-all": "^4.1.5",
    "rollup": "^2.18.1",
    "rollup-plugin-copy": "^3.3.0",
    "rollup-plugin-hot": "^0.0.31",
    "rollup-plugin-livereload": "^1.3.0",
    "rollup-plugin-svelte": "^5.2.3",
    "rollup-plugin-svelte-hot": "^0.9.2",
    "rollup-plugin-terser": "^6.1.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-replace": "^2.3.3",
    "spassr": "^1.1.2"
  },
  "dependencies": {
    "@sveltech/routify": "^1.8.3",
    "rollup-plugin-workbox": "^5.0.1",
    "svelte": "^3.23.2",
    "workbox": "0.0.0"
  }
}

```

App.svelte:

```
<script>
  import { Router, basepath } from "@sveltech/routify";
  import { routes } from "@sveltech/routify/tmp/routes";

  $: $basepath = '/r'
</script>

<Router {routes} />
```

`npm run build`

Error:

```
[Routify] Exporting to: dist
Error: Uncaught [Error: Route could not be found.]
...
```

Application works in `npm run dev`  on localhost:5000

Error also shows up in dev when going to localhost:5005 without the "/r"

So does it mean there needs to be a index.svelte somewhere for the build to work?

**Comment by jakobrosenberg** [comment]
Hi @Zyles. To export the routes, the exporter needs to know about the basepaths.

`"export": "routify export"` should be `"export": "routify export --basepath =\"r\" "`

https://routify.dev/docs/basepath

**Comment by Zyles** [comment]
I already tried running the npx export command.

Changing the package.json and running `npm run export` I get the same error.

**Comment by jakobrosenberg** [comment]
Do you have a repo you can share?

EDIT: I just realized a `=` had snuck into my previous post. It should only be `--basepath r`.

An even better option might be to set a dynamic basepath like this
```javascript
@basepath = "/(r|)"
```

This would match both `/about` and `/r/about`. Most often that's what you want if deploying to a subfolder.

**Comment by Zyles** [comment]
https://github.com/Zyles/routify-basepath-test

**Comment by Zyles** [comment]
> EDIT: I just realized a `=` had snuck into my previous post. It should only be `--basepath r`.

Ok now it builds.

But hitting `localhost:5005/?foobar=foo` it still throws the error when using `npm run dev`

But maybe that will not be a problem when going live.

**Comment by Zyles** [comment]
Related problem to basepath, after doing a build it does not link properly in the .html file generated which makes it 404.

```
<link rel='icon' type='image/png' href='/favicon.png'>

<link rel='stylesheet' href='/global.css'>
<link rel='stylesheet' href='/build/bundle.css'>

<script defer src="/build/bundle.js"></script>
```

Best practice is to enter my subdir there manually? Is there a way to get the basepath variable automatically into __index.html ?

I can't edit the bundle.js target in __index.html so I guess I need to modify rollup.config.js

Is it possible to make the final build file to be index.html instead of __app.html?

**Comment by Zyles** [comment]
Changing absolute links in `rollup.config.js`:

```
function transform(contents) {
  return contents.toString().replace('__SCRIPT__', useDynamicImports
    ? '<script type="module" defer src="/r/build/main.js"></script>'
    : '<script defer src="/r/build/bundle.js"></script>')
}
```

Breaks the app in `npm run dev`

**Comment by jakobrosenberg** [comment]
The below function might work.

```javascript
function transform(contents) {
  const basepath = !!production ? '/' : ''

  return contents.toString().replace('__SCRIPT__', useDynamicImports
    ? `<script type="module" defer src="${basepath}/build/main.js"></script>`
    : `<script defer src="${basepath}/build/bundle.js"></script>`)
}
```

**Comment by pavelloz** [comment]
Personally as soon as i add `  $basepath =  '/mybase'` export fails with weird error:

> Error: Uncaught [Error: Route could not be found. Make sure /Models/index.svelte or /Models/index/index.svelte exists. A restart may be required.]

Without basepath it build correctly.

of course Models/index.svelte exists and its working without basepath.

@jakobrosenberg above script doesnt seem to work - gets me 404.

Does anyone have working example of basepath feature? Im looking at the tests of it and TBH i have 0% confidence its working at all in standard cases ;)

PS. You can use `./build/bundle.js`

**Comment by jakobrosenberg** [comment]
@pavelloz the export command doesn't know about your basepaths.

You have two options:
A) **Supply a basepath to the export command** `--basepath mybase`
B) **Make the basepath optional** `$basepath = '(/mybase)?'`

**Comment by pavelloz** [comment]
Yup, i tried both, the only difference is that my basepath has `/` in it (`/gui/editor`) which might complicate things internally

**Comment by jakobrosenberg** [comment]
That shouldn't make a difference. Could you try import your project to https://codesandbox.io and send me a link?

**Comment by Wolfr** [comment]
@pavelloz came in with his own question/remark in @Zyles 's thread. Jake asked a question but no response after 2 weeks. Can we close this issue?

**Comment by pavelloz** [comment]
Yes, i just dont use this feature as i cant make it work. But creating separate repo is too time consuming to debug it further - ive spent my budget on fiddling with it long time ago :)

**Comment by Zyles** [comment]
I still have an issue with renaming `__app.html` to `index.html`

I tried in `rollup.config.js`:
`{ src: [`${staticDir}/__index.html`], dest: distDir, rename: 'index.html', transform },`

But when running the build it throws an error:

```
> routify export --basepath r
UnhandledPromiseRejectionWarning: Error: EONOENT: no such file or directory, open 'dist/__app.html'
```

Is this hardcoded?

**Comment by jakobrosenberg** [comment]
Yes, `__app.html` is hardcoded in a few places. Probably should add a config option.

**Comment by Zyles** [comment]
I changed package.json build command... I guess it works for now.

```
"scripts": {
    "build": "npm run routify -- -b && rollup -c && mv dist/__app.html dist/index.html",
  },
```

But a config option would be better.

**Comment by jakobrosenberg** [comment]
I had a look at the occurrences of the entry file and it's used by the prerenderer, the exporter, rollup, spassr etc.

I would like to have it as an option, but if it is has to be configured in multiple places (rollup, spassr, config, runtime config), your approach might be better.

Alternatively a Rollup transform could also handle it.

**Comment by ghostdevv** [comment]
I am assuming this is sorted? If not feel free to reopen
