### ISSUE TITLE
Social media testers can't find metatags

### ISSUE THREAD

**Issue by timoanttila** [roxiness/routify#229]
We talked about this issue on Discord some time ago, but I don't really know how to make my code better.

I'm trying to understand how to get meta tags working correctly. First, Svelte loads index.html and tags which it has. There are some, but the most important ones comes later from pages. However, all social media sharing testers can't read correct data because they load the page too soon before everything is ready or something like that. They seem to see only the content of index.html. I always use builded version (no servers). Browsers loads build.js and metatags without problems, but why sharing is not working?

The website I trying to fix:
[https://timoanttila.com](https://timoanttila.com)

Trying to get right results with this:
[https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)
`ERROR: No card found (Card error)`

All the files and then some:
[https://github.com/timoanttila/timoanttila-svelte](https://github.com/timoanttila/timoanttila-svelte)

Using metatags as recommended (used svelte:head before):
```
import { metatags } from '@sveltech/routify'
let sum = "Lorem"
let img = "Lorem"
metatags.title = "Lorem"
metatags.description = sum
metatags.url = "Url"
metatags.canonical = "Url"
metatags.image = img
metatags["twitter:card"] = "summary_large_image"
metatags["twitter:description"] = sum
metatags["twitter:image"] = img
```

For some unknown reason, https://svelte.school/ works fine. We talked about that too. All my projects give same result as timoanttila.com. Can't find right meta tags. I can't add all the tags to index.html, because I have different kind of content (index, gallery, now profile, tutorials). I really like Svelte and I want to keep doing things with it, but sharing my content right is big issue for me.

**package.json**
[https://github.com/timoanttila/timoanttila-svelte/blob/master/package.json](https://github.com/timoanttila/timoanttila-svelte/blob/master/package.json)

**Comment by jakobrosenberg** [comment]
Right clicking your page and viewing your source code shows that your index.html is empty, meaning that you've only deployed a SPA. You need to deploy a prerendered site and/or include SSR.

**Comment by kevmodrome** [comment]
It does sound like it's a deploy issue, where are you hosting it and what are the steps you are running to get it online?

The implementation used on Svelte School is also used on the Svelte Society websites staging site if you want to take a look at an implementation that for sure works: https://github.com/svelte-society/site/tree/staging

**Comment by timoanttila** [comment]
Yes, I know that index.html does not have much meta tags, but that's the problem. If I have multiple pages and I need different meta tags for those. Can't use same for all the different content. If I put something general into index.html then every page gives same answer when sharing content to social media (same title, image and description).

Isn't it possible to load the right data so that search engines and social media can see more than what index.html offers or slow down the page load until build.js is fully loaded or something like that? This is the only problem I have with Svelte and Routify.

I use Netlify to most of my stuff. I use Svelte, because I don't want to run node servers or anything like that. Just build and go.

Does Svelte Society use Cloudflare's paid services? Workers does something for you before loading the website? If I remember correctly, School does use paid services and maybe that's why those are working fine.

**Comment by jakobrosenberg** [comment]
> Isn't it possible to load the right data so that search engines and social media can see more than what index.html offers or slow down the page load until build.js is fully loaded or something like that? This is the only problem I have with Svelte and Routify.

That's what prerendering and/or SSR does.

```
npx @sveltech/routify init
npm run build
npm run deploy:<provider>
```

That'll give you a site with prerendering and SSR. In fact that's how `example.routify.dev` is deployed.

**Comment by timoanttila** [comment]
Looks like that solved my problem. Thank you very much.
