### ISSUE TITLE
ignore parent layout is it possible?

### ISSUE THREAD

**Issue by sid3r** [roxiness/routify#230]
Hey, thank for the elegant ans simple to use Router, I have a situation where one would like to prevent the child layout to be affected by parent layout, I have the current folder structure:

```
pages
-- _layout.svelte
-- index.svelte
-- about.svelte
-- admin/
---- _layout.svelte
---- index.svelte
---- accounts.svelte
```
the issue I'm facing is that __layout_ in _pages/_ affects __layout_ in the the subfolder _admin/_. any Idea how to re-organise this or prevent the parent to affect all subfolder ?

**Comment by jakobrosenberg** [comment]
Hi @sid3r, you can use `_reset.svelte` instead of `_layout.svelte` to clear inheritance.

https://routify.dev/guide/introduction/structure

**Comment by kevmodrome** [comment]
Worth noting is that the _reset.svelte becomes the layout in that folder :)

**Comment by sid3r** [comment]
@jakobrosenberg I missed that part of the docs, works as expected, thank you.
