### ISSUE TITLE
Fetch request "flashes"/rerenders content in SSR but not in SPA

### ISSUE THREAD

**Issue by flayks** [roxiness/routify#231]
I started developing a website using Routify as I wanted to give it a go from Sapper, and I noticed something odd when fetching an API address from the `_layout.svelte` file (also on `index.svelte`). I based my latest research on a fresh clone of the Routify start template, and when doing a simple `fetch('apiurl')`, it flashes/rerenders the content of the page. Also meaning, it stops my page transitions (called by a javascript function) before they end.
All of this doesn't seem to happen on SPA mode but only on SSR, which makes me think of a possible content cache made by Routify somehow? (no sw enabled so far)

Simple example: I can see 1594657785032 after a super fast change of timestamp right before.

Just to visually expose the issue:
![routify](https://user-images.githubusercontent.com/273716/87330150-644f9900-c538-11ea-9302-3c7107f66132.gif)

### index.svelte
```js
{new Date().getTime()}
```

### _layout.svelte
```js
<script>
    import { ready } from '@sveltech/routify'

    $: loadAPIData()

    // Load data from API
    const loadAPIData = () => {
        fetch('http://api.localhost', {
            method: 'post',
            headers: {
                'Content-Type': 'application/json',
                Authorization: `bearer token`
            },
            body: JSON.stringify(`{ graphql query… }`)
        })
            .then(res => res.json())
            .then(res => {
                const { data } = res
                console.log(data)
            })
           .then($ready)
    }
</script>

<slot />
```

Is it normal? Should I preload my site content another way? It just sounds odd because I use this data loading technique with Sapper and it's not causing any issue.

**Comment by jakobrosenberg** [comment]
Hi @flayks. That's normal, as you suspect.

The page is prerendered and the first timestamp you see is from the prerendered page. Once the app is loaded, it replaces the static prerendered HTML. The timestamp in the app will of course be different.

Normally this happens seamlessly as the live app's HTML is identical to that of the prerender.

**Comment by flayks** [comment]
That makes sense. Although it is not really the desired behavior for animations, what would you reckon regarding this issue? In my case I run an anime.js function which doesn't finishes completely.

**Comment by jakobrosenberg** [comment]
You could make the animations conditional by checking whether you're in a browser. `if (window.routify.inBrowser)` or `if (routify.inBrowser)`.

Another option would be timing the animation to run after `$ready`.

Depending on the type of animation, there may by other options.

**Comment by flayks** [comment]
@jakobrosenberg alright. I'm actually already running my `animationIn()` function in the `onMount` declaration of Svelte, so _technically_ it's not being run by SSR.

A more visual and concrete example of my issue:
![output](https://user-images.githubusercontent.com/273716/87400026-8db00980-c5b8-11ea-9e31-2eb9b2fe1513.gif)

As you can see, the animation runs pretty smoothly but then stops and content is changed (which shouldn't be the case btw - it gets a random word in the description at page load, after the request).
I just find the concepts of Routify a bit complex to understand as opposed to Sapper where it's pretty straight forward 🧐

AFAIK, the transition directive from Svelte runs on a page transition, not when the page is loaded. Unless there is another way to run animations of page load that I don't know of?

#### about.svelte
```js
import { animateIn, animateOut } from 'transitions/about'

...

onMount(() => {
    animateIn()
})
```

#### transitions/about.js
```js
import anime from 'animejs'

/*
** Transition In
*/
export const animateIn = () => {
    const tl = anime.timeline({
        easing: 'easeOutQuart',
        duration: 1400
    })

    // Intro image
    tl.add({
        targets: '.about__introimage',
        height: [0, '100%'],
        translateZ: 0,
        transformOrigin: ['0 0', '0 0 '],
    })
    tl.add({
        targets: '.about__introimage img',
        scale: [1.1, 1],
        translateZ: 0,
    }, 0)
}
```

**Comment by jakobrosenberg** [comment]
There seems to be something else at play. Do you have a repo I can try? It looks like your animation is replaced with new HTML when the random word is loaded.

Also, is there anything I can do to help you with the concepts? I find them much simpler than those of Sapper, so it sounds like our documentation could use improvement.

**Comment by flayks** [comment]
It's a bit hard to reproduce as I have a local API URL to fetch and many other components included, but I tried to create a similar environment with a CodeSandbox: https://codesandbox.io/s/dank-rain-rlneq
The animations seem to run seamlessly on SPA but with more trouble with SSR (port 5005).

**Comment by jakobrosenberg** [comment]
Thanks for Codesandbox link. I have to admit, this case is really interesting.

With SSR, the prerendered HTML page is sent first and then the javascript is loaded. In your case that means the animation won't happen till javascript is loaded.

Since the animation goes from 0 to 1 opacity, the correct approach would be to set the initial style as:
```css
.header__logo, li {  opacity: 0 }
```

**Comment by flayks** [comment]
I had some time to investigate and I think it's not about any fetch or animation but SSR vs client side itself. I tried this kind of same example with Nuxt, Next and Sapper and I sort of have the same results.

Though, how could I do to run the animation only on the client side without having a change of content halfway through? It's kinda obscure to me and I'm not aware of what could be a good solution to avoid this

PS @jakobrosenberg: unfortunately your idea doesn't work because the CSS is "repainted" so makes the logo and menu links transparent due to the opacity. I really feel that something odd happens here and the render is not made properly?

**Comment by jakobrosenberg** [comment]
Strange. I tried the `.header__logo, li {  opacity: 0 }` fix and it worked without a hitch.

https://codesandbox.io/s/suspicious-turing-1i9yu?file=/src/pages/_layout.svelte

**Comment by Wolfr** [comment]
I think there is simply no way to do smooth page transition/intro animations with full animation control when shipping an SSR-enabled page. Either you ship an SPA, and you have full animation control, or you don't and you ship an SSR version.

In the SSR version you could have in-page animations which run after any possible hydration, independent of any route changes, but if you try to combine smooth animations (both intro and page transition) and SSR, you're setting yourself up for a big headache.

**Comment by braebo** [comment]
I actually figured out a fix for this by modifying the Svelte-transition to apply the start opacity (0 in this case) when it initializes:

```js
function flyfix(node, { delay = 0, duration = 400, easing: easing$1 = cubicOut, x = 0, y = 0, opacity = 0 } = {}) {
	const style = getComputedStyle(node);
	const target_opacity = +style.opacity;
	const transform = style.transform === 'none' ? '' : style.transform;
+	node.style.opacity = opacity // set initial opacity
+	node.addEventListener('introend', () => { // set target opacity on introend
+		node.style.opacity = style.opacity
+	}, {once: true})
	const od = target_opacity * (1 - opacity);
	return {
		delay,
		duration,
		easing: easing$1,
		css: (t, u) => `
			transform: ${transform} translate3D(${(1 - t) * x}px, ${(.99 - t) * y}px, 0);
			opacity: ${target_opacity - (od * u)};
		`
	}
};
```

You can see it in action in my repro: https://github.com/FractalHQ/IntroFix

**Comment by jakobrosenberg** [comment]
@FractalHQ I think we should create a new issue for this with a clear description of the problem and how it solves it. The original issue was about the inherent double requests you get with SSR.

**Comment by braebo** [comment]
Ok, good idea!
