### ISSUE TITLE
Support spreading in parameterized routes

### ISSUE THREAD

**Issue by kefahi** [roxiness/routify#232]
**Is your feature request related to a problem? Please describe.**
I'm rendering *posts* fetched from a headless CMS where part of the url should be the *sub-path* to those posts in the cms (e.g. "/posts/category/section/year/"). Using the current parametrized route (e.g. [slug]) only works for one-level folder. 

**Describe the solution you'd like**
It would be nice if spread routes are supported; in such case where [...slug] maps to an arbitrary deep url path string. This is in contrast to the basic parametrized route [slug] represents a place holder for exactly one folder; however there are several practical cases where spreading is desirable. 

**Describe alternatives you've considered**
I considered using the _fallback.svelte in the specific parent folder as  a catch-all and from there read the $leftover and use that sub-path to fetch the respective post and render it.

**Additional context**
Sapper already supports this and here is a direct quote from there ..

_If you don't want to create several folders to capture more than one parameter like [year]/[month]/..., or if the number of parameters is dynamic, you can use a spread route parameter. For example, instead of individually capturing /blog/[slug]/[year]/[month]/[day], you can create a file for /blog/[...slug].svelte and extract the params like so:_

```<!-- src/routes/blog/[...slug].svelte -->
<script context="module">
  export async function preload({ params }) {
    let [slug, year, month, day] = params.slug;
    return { slug, year, month, day };
  }
</script>

**Comment by jakobrosenberg** [comment]
Any thoughts on how this would coexist with `_fallback.svelte`?

I suspect `_fallback.svelte` and `[...params].svelte` would be different names for the same feature.

**Comment by kefahi** [comment]
@jakobrosenberg 
If they are functionally equivalent then there is no urgency (or strong motivation) to support spreading. I was under the impression that _fallback was more of an error handler and my initial solution with it wasn't the "proper" routify way. 
But given your comment I believe we can close this ticket.

Many thanks for your response and for the great framework you helped creating!

**Comment by jakobrosenberg** [comment]
@kefahi thank you for the kind words.

I have often pondered on spreads or arrays in the parameterized routes, so I wouldn't rule this out.

Currently there's a `$leftover` helper which returns the unconsumed part of the address, so `const { slug, year, month, day } = $leftover.split('/')` should be equivalent.

`fallback` has an unfortunate connotation or error handling and I wonder if `_catch.svelte`, or `[...my-params].svelte` would be a better name in Routify 2.
