### ISSUE TITLE
Validation of hash fragment in URL's

### ISSUE THREAD

**Issue by antstanley** [roxiness/routify#233]
**Hash fragment validation**

Routify attempts to scroll to a valid element that matches the hash fragment in the URL. It does not validate that the hash fragment in the url is a valid element ID. 

I'm implementing OpenID Implicit Grant authentication, which returns `id_token` and `access_token` tokens in the hash fragment of the URL, which Routify attempts to scroll to, but throws an error because the very long hash fragment which doesn't meet the requirements of an element id. 

It throws an `index.js:14 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': ` error with about 30 lines of detail in the console. This is using Routify `v1.9.2`

To avoid that it would be good to validate that the hash fragment uses characters that are valid element id characters, before attempting to query it and scroll to it.

I would add a few extra validation lines in the `handleHash` function `runtime/utils/index.js`

The code found here
https://github.com/sveltech/routify/blob/f58046f548ce663f001c1083e4b439b151c67648/runtime/utils/index.js#L9-L16

Something along the lines of this...

```js
export function handleHash () {
  if (navigator.userAgent.includes('jsdom')) return false
  const { hash } = window.location
  if (hash) {
    const validElementId = /^[A-Za-z]+[\w\-\:\.]*$/
    if (validElementId.test(hash)) {
      const el = document.querySelector(hash)
      if (hash && el) el.scrollIntoView()
    }
  }
}
```

I've monkey patched my node_modules version of routify with this change and it works for me. It would be good to see this pushed to the latest publish version.

Thanks for the great work on Routify! I'm a fan.

**Comment by antstanley** [comment]
Oh yes... in the time honored tradition of good development practice. I got the regex from this blog [https://ghostinspector.com/blog/regex-validate-html-id-attribute/](https://ghostinspector.com/blog/regex-validate-html-id-attribute/)

**Comment by jakobrosenberg** [comment]
Hi @antstanley. Thanks for the kind words. Would you be interested in submitting a PR?

``If (hash && el)`` should probably be ``if (el)``.

**Comment by antstanley** [comment]
Perfect! Thank you!
