### ISSUE TITLE
There is no helper to get off the "managed" routing

### ISSUE THREAD

**Issue by GregoireBellon** [roxiness/routify#236]
**Is your feature request related to a problem? Please describe.**
Routify is amazing and can be totally front-end, so we can use another backend, like flask, and let it manage some of the routes. Sadly, there is no way to get off the routify routing.

For exemple, if I create a "/login" route in my backend, and a tag like 
`<a href='/login'></a>`
, I won't be able to reach the flask's route.

**Describe the solution you'd like**
A simple helper that allow to make a "raw" call to the server without any pre-routing by routify.

**Describe alternatives you've considered**
None of the helper can assist me for this, the only alternative is to reload the page after clicking on the link

**Comment by jakobrosenberg** [comment]
This is handled at the level of your server.

You can either run your backend on another port or redirect specific requests.

https://routify.dev/examples/setup-express-server

In the above example, you can add your own routes and Routify will catch all unspecified routes.

**Comment by Wolfr** [comment]
@GregoireBellon Do you consider your question answered?

**Comment by GregoireBellon** [comment]
Thanks for your answer.

> This is handled at the level of your server.
> 
> You can either run your backend on another port or redirect specific requests.
> 
> https://routify.dev/examples/setup-express-server
> 
> In the above example, you can add your own routes and Routify will catch all unspecified routes.

This is right, the problem is , when a relative link doesn't point at a routify's page, an error is threw by routify itself, and there is no request addressed to the server. 

For exemple, if I create a flask backend with two routes : 
"/" and "/login", "/" is served by routify through flask and "/login" is directly served by flask. 

If I call "/", I"ll find my page, provided by routify, if I call "/login", it's gonna work too, and I'l find my page provided by flask.

The problem is if I put a link in "/" pointing at "/login", it will throw a 404.

I found a (poor) workaround, which consist to add target="_blank" at the a tag, it open a new tab and send a new request to the server.

**Comment by jakobrosenberg** [comment]
The official solution is to use `target="_self"`. I've considered adding a custom tag, but at best it would just be syntactical sugar for the existing solution.
