### ISSUE TITLE
Unable to do default browser navigation using anchor href attribute

### ISSUE THREAD

**Issue by aamirshahx** [roxiness/routify#237]
**bug description**
I created an anchor with href that contains the URL that's not part of routify where we need user to go via browser redirect but when I click on the anchor the URL is being pushed to the browser history but there is no navigation, routify throws an error 

> Route could not be found.

How can I redirect to different pages that are not part of svelte/routify application.  the URLs are dynamic therefore I need a way to navigate these dynamic URLs using anchor href.

This is the kind of url i am generating
`<a href="/abc/asda/qeqwe">Anchor</a>`

**version**
Routify: 1.9.4
Svelte: 3.24.0

**Comment by jakobrosenberg** [comment]
Could you try with `<a href="..." target="_self">`. Routify should IIRC ignore all anchors with targets.

This is probably something we should document.

**Comment by aamirshahx** [comment]
Thanks for the reply, I'll try and let you know.

I think this is very useful information, May I open a PR in 'routify-site-2020' to update the 'Navigation' Guide with the above behaviour, so future users can learn about this feature from the docs.

**Comment by Wolfr** [comment]
Yes please, this is something I didn't know and that would be a useful addition to the docs.

**Comment by jakobrosenberg** [comment]
> May I open a PR in 'routify-site-2020' to update the 'Navigation' Guide with the above behaviour

Yes! Would be very appreciated.

**Comment by aamirshahx** [comment]
![image](https://user-images.githubusercontent.com/1303176/88225852-a38e9000-cc84-11ea-9744-789a42a7606b.png)

Does this look good?

**Comment by jakobrosenberg** [comment]
Looks perfect!

The `blank` in the second example might not be needed. Routify only hijacks relative paths, ie. paths within your app.

**Comment by aamirshahx** [comment]
Created [Pull request](https://github.com/sveltech/routify-site-2020/pull/163) 

Thanks for the help @jakobrosenberg
