### ISSUE TITLE
update URL params without triggering re-routing

### ISSUE THREAD

**Issue by OmG3r** [roxiness/routify#240]
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]:
Within the website am currently working on i have a set of filters that will be used to filter a list of items, I am currently adding each filter to the URL as a parameter, however upon each filters update in the URL (using history API) the whole route (component) gets reinitialised, re-running unnecessary Javascript because i already used to to verify the data.

EDIT:
I forgot an important piece of information:
I also happen to have 3 nested variables routes: `/browse/[p1]/[p2]/[p3]&{my params}`
the routes : `/browse`, `/browse/[p1]`, `/browse/[p1]/[p2]`, `/browse/[p1]/[p2]/[p3]`, all are using the same component
so my issue is i can't switch from for example `/browse` to `/browse/[p1]` without it being considered as a new page, because in fact all of the 4 pages have the same display (i preserve the data in each navgiation), i just want the link to be updated for socail media sharing purposes.

A clear and concise description of what you want to happen:
an option to change the URL, at least it's parameters, without triggering a routing update.
A clear and concise description of any alternative solutions or features you've considered:
reducing Javascript from top-level and adding it to events

**Comment by jakobrosenberg** [comment]
I was not able to reproduce the retrigger. Could you provide a repo highlighting this issue?

**Comment by OmG3r** [comment]
Hello, I have updated my request with another piece of information required to reproduce the behaviour.

I would like to note this is a feature request, not a bug or an issue, the library is behaving as intended.

**Comment by jakobrosenberg** [comment]
Can you specify what mean by `routing update`. No page or layout should reload from changing a parameter.

**Comment by OmG3r** [comment]
Sorry, for taking too long to reply.

After taking a step back and looking at the issue again. my idea is to include wildcards to the routing system for example `[**].svelte` to intercept all routes that are not accounted for in the folder.

` _fallback.svelte `already does this, however it does not supply the route params to the `$params` store.

currently I am parsing `window.location.pathname` for the params.

so my feature request would be either to include the route params in `$params` for `_fallback.svelte` or to add `[**].svelte` as a new unique route.

I will be closing this issue thread as it's too vague and open another more detailed one.
