### ISSUE TITLE
Wildcard route.

### ISSUE THREAD

**Issue by OmG3r** [roxiness/routify#242]
**Is your feature request related to a problem? Please describe.**
I have a route within my application that should serve the same component for all paths. currently I am using `_fallback.svelte `to achieve this however, `$params` store is not populated with the route params, my workaround was to manually parse `window.location.pathname`.

**Describe the solution you'd like**

1. have a wildcard file name.
for example `[**].svelte` to match all routes for the folder (`localhost/**`). however we cannot make files with `*` as a character so any other name would suffice.

2. have a wildcard folder name for `localhost/**/edit`
again we can't use `**` as a foldername.

3. The ability to reinitialize the component in each navigation to a `**` route or to keep the same component and just update `$params` store

**Describe alternatives you've considered**
using `_fallback.svelte` and getting the url path manually using `window.location.pathname`

**Additional context**

**Comment by jakobrosenberg** [comment]
Would this be the same as `[...multipleparams]`?

EDIT: Just saw the update on your other issue. It seems this is what you're proposing.

**Comment by OmG3r** [comment]
Yes `[...multipleparams]` would suffice to add the wild card functionality.
as for `localhost/**/edit`, after looking at it again, it's the same as `localhost/[p1]/edit`. we already have that functionality sorry for the confusion.
