### ISSUE TITLE
Not working in IE11 [SOLVED]

### ISSUE THREAD

**Issue by rajeshkannanv** [roxiness/routify#245]
**Description**
We have a project using routify. we have added compiler(babel+core-js) to support legacy browsers. but still it is not working in IE11. If i remove routify and run a svelte app, it is working IE11.
Sample project : [https://github.com/rajeshkannanv/routify-webpack-example](https://github.com/rajeshkannanv/routify-webpack-example)

**Logs**
`SCRIPT5009: 'Proxy' is undefined`

**Which comes from here:**

_File:  runtime/helpers.js_

`
var metatags = new Proxy(_metatags, {
  set: function set(target, name, value, receiver) {
    var props = target.props,
        getOrigin = target.getOrigin;
    if (Reflect.has(target, name)) 
       Reflect.set(target, name, value, receiver);else {
      props[name] = props[name] || {};
      props[name][getOrigin()] = value;
    }
    if (window['routify'].appLoaded) 
      target.batchedUpdate();
    return true;
  }
});
`

**How to reproduce**

I have created sample project with routify+webpack+babel.
[https://github.com/rajeshkannanv/routify-webpack-example](https://github.com/rajeshkannanv/routify-webpack-example)

Does routify support in IE11? 
Do we have any work around for this issue?

**Comment by jakobrosenberg** [comment]
You will need a compiler like Babel for legacy browsers.

https://github.com/rollup/plugins/tree/master/packages/babel

**Comment by rajeshkannanv** [comment]
@jakobrosenberg Thanks for your quick response,  we are using webpack with babel, still it is not working. I have updated the issue details with [sample project](https://github.com/rollup/plugins/tree/master/packages/babel).  where this issue can be reproduce able.

**Comment by jakobrosenberg** [comment]
I'm all thumbs when it comes to Webpack. 😳

Is this of any use?
https://github.com/sveltejs/svelte/issues/3388

**Comment by rajeshkannanv** [comment]
By adding `proxy-polyfill` for IE11. I have solved the issue.

**Comment by jakobrosenberg** [comment]
Thanks @rajeshkannanv 

I hope this can save others some time in the future.
