### ISSUE TITLE
replace helper

### ISSUE THREAD

**Issue by konyee95** [roxiness/routify#247]
**Scenario**

In my application I have 2 pages. `/home` and `/test`. The `/test` page is configured to accept parameters.

So in an ideal scenario the user would travel from `/home` to `/test` to `/test?param=123`. I would like the user to come back from `/test?param=123` to `/home` directly.

However, the `location.replace` doesn't seem to work as the router still brings me back to `/test/` from `/test?param=123`

**Comment by jakobrosenberg** [comment]
You can use `$goto` or `$redirect`.

https://routify.dev/docs/helpers#goto

**Comment by konyee95** [comment]
@jakobrosenberg Please have a look at my updated question! Thanks!

**Comment by jakobrosenberg** [comment]
Did you try `$redirect('/home')`?

**Comment by konyee95** [comment]
Actually what I mean is that is there a way for me to replace`/test` to `/test?param123` in browser history stack? So that when I click browser back button, it will just go back to `/home`.

**Comment by jakobrosenberg** [comment]
In that case:
```javascript
$redirect('./', {param:123})
```
or 
```javascript
$redirect(null, {param: 123})
```

**Comment by ghostdevv** [comment]
@konyee95 can this be closed?
