### ISSUE TITLE
JSX element type 'Router' does not have any construct or call signatures.ts(2604)

### ISSUE THREAD

**Issue by acim** [roxiness/routify#248]
**bug description**

I followed the instructions to [install Routify to existing project](https://routify.dev/guide/installation/install-to-existing-project), which is Svelte with (official) TypeScript and in VSCode I get the following error under Router component:

```txt
JSX element type 'Router' does not have any construct or call signatures.ts(2604)
```
_npm run dev_ runs just fine and reports no errors. Same is for _npm run build_.

**package.json**

```
    "build": "routify -b && rollup -c",
    "dev": "routify -c svelte-dev",
    "svelte-dev": "rollup -c -w",
    "start": "sirv public --single",
    "validate": "svelte-check"
```

**version**

Routify 1.9.7
Svelte 3.24.1

**App.svelte**

```
<script type="ts">
  import { Router } from "@sveltech/routify";
  import { routes } from "@sveltech/routify/tmp/routes";
</script>

<Router {routes} />
```

**Comment by jakobrosenberg** [comment]
This is caused by the `svelte` field in package.json. For some reason imported components don't work with Typescript.

You can fix it by either of the following:
- A) Omit `type="ts"` from `App.svelte`
- B) import Router from `@sveltech/routify/runtime/Router.svelte`
- C) Use Routify 2 `@roxi/routify` (this has not been tested)

**Comment by acim** [comment]
OK, thank you. By the way, just the first solution worked.

**Comment by Tommertom** [comment]
Hi,

Option A is a workaround and works obviously because one is disabling typscript for that component
Option B does not work on my end - circular reference given
![image](https://user-images.githubusercontent.com/16119174/92321620-a6bebf00-f02b-11ea-823a-6cb97789e7e5.png)

Option C: does not solve the issue. (tested against routify 2.0.0)

**Comment by jakobrosenberg** [comment]
@Tommertom could you try 
```javascript
import Router from '@sveltech/routify/runtime/Router.svelte'
```

You're destructuring `Router.svelte` in your example, which won't work.

**Comment by Tommertom** [comment]
![image](https://user-images.githubusercontent.com/16119174/92359450-8ce4b100-f0eb-11ea-80e8-014671fb5349.png)

JSX element class does not support attributes because it does not have a '$$prop_def' property.ts(2607)

Ain't getting any better here....

**Comment by jakobrosenberg** [comment]
@Tommertom what version of Routify are you using? Also, you're using quotes around your `"{routes}"` object. I don't know if that could cause issues.

**Comment by Tommertom** [comment]
> @Tommertom what version of Routify are you using? Also, you're using quotes around your `"{routes}"` object. I don't know if that could cause issues.

Hi, using  "@roxi/routify": "^2.0.0"  and the removing the quotes to `<Router {routes}>` keeps the error. The other syntax is because there is this Typescript option to disallow shortHand.

I think here there something that needs to be done in the package, or maybe you want to experiment with my repo as earlier posted? I am kind-of not really eager to experiment this way any more... sorry if that is not ok with you.

**Comment by jakobrosenberg** [comment]
Could you try `^2.1.2`. I can't tell if that's already what you have installed.

**Comment by Tommertom** [comment]
> Could you try `^2.1.2`. I can't tell if that's already what you have installed.

No joy. See https://github.com/Tommertom/svelte-ionic-app 

Can you try with my repo please?

**Comment by jakobrosenberg** [comment]
Not sure if my VSCode is not configured correctly, but I'm not getting any errors.

![image](https://user-images.githubusercontent.com/4153004/92366200-206eaf80-f0f5-11ea-9d13-2e793c39d8d3.png)
![image](https://user-images.githubusercontent.com/4153004/92366245-2d8b9e80-f0f5-11ea-8231-e509a6b2b256.png)
![image](https://user-images.githubusercontent.com/4153004/92366266-37ad9d00-f0f5-11ea-8a1d-9fde4c71f2b5.png)

**Comment by Tommertom** [comment]
> Not sure if my VSCode is not configured correctly, but I'm not getting any errors.

Thx for trying. Maybe you can make a deliberate typescript error and see how vscode responds?

`let stuff:number="ERROR";`

![image](https://user-images.githubusercontent.com/16119174/92366844-f669bd00-f0f5-11ea-9bb7-d234adfda5c1.png)

**Comment by jakobrosenberg** [comment]
Same error as you if I assign wrong type. I also have an error for this one.

![image](https://user-images.githubusercontent.com/4153004/92369680-98d76f80-f0f9-11ea-8d5d-24f22094da7d.png)

No errors related to Routify though.

Looking at your previous post, it seems the error is for `Router.svelte` and not `routes`. The error would suggest that `Router` is not a Svelte component. `element class does not support attributes`.

**Comment by Tommertom** [comment]
> Looking at your previous post, it seems the error is for `Router.svelte` and not `routes`. The error would suggest that `Router` is not a Svelte component. `element class does not support attributes`.

Ok. Will do some thinking and learning.

**Comment by godefroi** [comment]
I see the same issue, and similarly B) did not solve it. A) did, and is acceptable, I guess, but certainly not idea. Is Routify 2 production-ready, which would make C) a valid option?

**Comment by jakobrosenberg** [comment]
@godefroi Routify `^2.1.3` should be production ready. At this point, the main thing holding back a release is getting documentation up to date.

**Comment by Egnus** [comment]
Any update regarding this? it is still happening with `@roxi/routify: 2.7.3`

**Comment by jakobrosenberg** [comment]
@Egnus do you get the error if you import Router directly? `import Router from '@roxi/routify/runtime/Router.svelte`

**Comment by Egnus** [comment]
I was going to comment your reply with what I found to work but you already edited it.
Yes, finally `import Router from '@roxi/routify/runtime/Router.svelte'` solves the issue, thanks

**Comment by jakobrosenberg** [comment]
@Egnus I think the issue is outside of Routify.

For some reason it's not possible to have this (simplified):
```javascript
// routify.js
export { default as Router } from './Router.svelte'
```

```javascript
import { Router } from 'routify'
```

but it's possible to do

```javascript
import Router from 'routify/Router.svelte'
```

In plain JS, it's not a problem, but with TS you get a warning. Either method is fine, so I suspect it's a bug in the Svelte's TS implementation.

**Comment by mateuszlewko** [comment]
I just wanted to mention that it's probably worth including `import Router from '@roxi/routify/runtime/Router.svelte'` in the default routify template.

**Comment by gustavopch** [comment]
@jakobrosenberg What about changing the `index.d.ts` file like this?
```diff
-  export const Router: import('svelte/internal').SvelteComponent
+  export const Router: typeof import('./runtime/Router.svelte').default
```
It seems to work well.

**Comment by jakobrosenberg** [comment]
Great idea @gustavopch. Interested in doing a PR?

**Comment by gustavopch** [comment]
@jakobrosenberg There it is.

**Comment by jakobrosenberg** [comment]
Thanks @gustavopch. Your PR should be available in the latest release.

**Comment by risalfajar** [comment]
![image](https://user-images.githubusercontent.com/28381124/131931473-9021f270-e774-4779-be33-8be8ca2be148.png)

Still exist on 2.18.3
