### ISSUE TITLE
Redirect feature

### ISSUE THREAD

**Issue by umaryusuf** [roxiness/routify#25]
Not sure if there's a redirect feature or way to programmatically navigate to another route.

**Comment by jakobrosenberg** [comment]
Hi @umaryusuf 

There's ``window.location.href = 'google.com'`` to simulator mouse click and ``window.location.replace('google.com')`` to simulate a redirect.

For redirects within the app, there's ``history.pushState({}, null, '/frontpage')``

V2, which we hope to release very soon, will have a ``goto('/frontpage')`` helper which is shorthand for the history.pushState.

**Comment by umaryusuf** [comment]
Thanks for your feedback @jakobrosenberg

It will be very helpful if you can add that to the documentation.

**Comment by eriknyk** [comment]
Hi, I'm using version:

and a _layout.svelte like this:

```
<script>
  import { goto } from '@sveltech/routify'
  import { user } from '../store.js'

  if (user === null) {
    $goto('/login')
  }
</script>

{#if user !== null}
  <h2 data-focus>Home yeah!</h2>
{/if}
```

However, I can see that it redirect into url as expected to `/login` *but* it does not re-rendering the /login page contents, so the result is a blank page.

Any thought?

Regards.

**Comment by jakobrosenberg** [comment]
@umaryusuf 

There's a new ``goto`` helper which I think would suit you.

https://routify.now.sh/docs/helpers

The starter template has a few examples.

**Comment by mizzao** [comment]
@jakobrosenberg it seems that I can't use `goto` outside of components. Any way to achieve that? 

![image](https://user-images.githubusercontent.com/2080084/112391395-39743200-8cce-11eb-91bc-2c6e660fd660.png)

**Comment by eriknyk** [comment]
@mizzao in general you cannot use any feature like routing outside of any svelte component, 
I've faced with similar issue with my api layer that is not a svelete component it is only a js lib, and when the session expires or token is expired it should redirect to login, in the end I just used location.href = '/login' in that that case.

**Comment by jakobrosenberg** [comment]
@mizzao you can try something like this
```html
<!-- root _layout.svelte -->
<script>
  import { goto } from '@roxi/routify'
  import someFile from './someFile.js'
  someFile($goto)
</script>
```

```javascript
// someFile.js
export default function ($goto){
  if(...)
    $goto(...)
}
```

**Comment by ghostdevv** [comment]
You can always make your own helper file that updates the browser history and redirects you if what jake suggested doesn't work

**Comment by yuliankarapetkov** [comment]
I ended up doing this:

```
// store.js 
export const globalGoto = writable(null);

// _layout.svelte - the root layout
import { globalGoto } from "./store";
import { goto } from "@roxi/routify";

globalGoto.set($goto);

// something.js
import { globalGoto } from "./store";
import { get } from "svelte/store";

function doSomething() {
  const $globalGoto = get(globalGoto);

  $globalGoto("/path");
}
```

**Comment by jakobrosenberg** [comment]
@yuliankarapetkov, nice. Is that for R2 or R3?

**Comment by yuliankarapetkov** [comment]
@jakobrosenberg didn't see your comment, sorry! I'm using R2.
