### ISSUE TITLE
Links served by the same svelte file do not update the rendered page.

### ISSUE THREAD

**Issue by kefahi** [roxiness/routify#251]
A simple _fallack.svelte setup under a folder called "links" is like this 
```
<script>
import {leftover} from "@sveltech/routify";

console.log("Leftover: ", $leftover);
</script>
<a href={$url("/links/sub1")} /> sub link 1 </a>
<a href={$url("/links/sub2")} /> sub link 2 </a>

<h2> {$leftover} </h2>
```
When clicking on any of the two links in that page, nothing happens. 

The expected behaviour is for the clicks to cause the page to be properly updated.

A work-around is to add `target="_self"` to the anchor tag which causes the whole page to load on every click.

When there is a link that is resolved /served by another svelte file the click works just fine.

(I tried with routify 1.9.9 and 1.9.7)

**Comment by jakobrosenberg** [comment]
Routify 2 has a meta option `param-is-page` which reloads the component if its parameter changes. Would this work for you?
```
<!-- routify:options param-is-page=true -->
```

**Comment by kefahi** [comment]
Thanks!

I can confirm that the issue is resolved and the following code is working fine (routify 2.1)

```
<!-- routify:options param-is-page=true -->

<script>
  import { afterPageLoad, url, leftover } from '@roxi/routify';
  $afterPageLoad((event) => {
	console.log("left: ", $leftover);
  });
</script>

<div>
	<a href={$url("/links/xyz")}> xyz </a>
	<a href={$url("/links/abc")}> abc </a>
	<h2> {$leftover} </h2>
</div>
```
