### ISSUE TITLE
Goto not working as expected

### ISSUE THREAD

**Issue by Taha-Firoz** [roxiness/routify#252]
**bug description**
Using `$goto `within HTML region to redirect users according to authguard in `_layout` file leads to the webapp just crashing. Using it within script tag seems to work but if the user goes to a path that is not allowed by the auth guard the url changes but the HTML in the slot doesn't update. 

**package.json**
```
{
  "name": "FF-Website",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c",
    "dev": "routify -c server",
    "server": "rollup -c -w",
    "start": "sirv public --single",
    "validate": "svelte-check"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^12.0.0",
    "@rollup/plugin-node-resolve": "^8.0.0",
    "@rollup/plugin-typescript": "^4.0.0",
    "@sveltech/routify": "^1.9.7",
    "@tsconfig/svelte": "^1.0.0",
    "rollup": "^2.3.4",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^5.1.2",
    "svelte": "^3.0.0",
    "svelte-check": "^1.0.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^3.9.3",
    "firebase": "^7.18.0"
  },
  "dependencies": {
    "sirv-cli": "^1.0.0",
    "smelte": "^1.0.15"
  }
}
```

**screenshot**
Sometimes they help. Extra points for good memes.

**Comment by jakobrosenberg** [comment]
Is it possible you have an infinite loops of redirects?

**Comment by Taha-Firoz** [comment]
No, not really since it works when the `$goto`'s are in the script tag. I'll give a minimal example of how it was implemented initially and the other issues I came across.

```
/*_layout.svelte*/

{#if auth === null}
    <Loading Image Spinner>

{:else if auth === true}
    {$goto('home')}

{:else}
    {$goto('login')}
{/if}

<slot>
```

Since this wasn't working I changed it up a bit

```
/*_layout.svelte*/
<script>
    let auth = null;
    function authenticate(){
        ....
        if (is_authenticated){
              auth = true;
              $goto('home');
        }
        else {
              $goto('login');
        }
    }
</script>
{#if auth === null}
    <Loading Image Spinner>
{:else}
    <slot>
{/if}
```
This works but I kept getting this weird bug, where after I've logged in and signed out from the home page and I try to log in again, the URL changes to `home` but the HTML loaded remains to that of the login page.

**Comment by jakobrosenberg** [comment]
Would you be able to share a minimal reproducible example?

**Comment by Taha-Firoz** [comment]
working on it

**Comment by ghostdevv** [comment]
@Taha-Firoz is this still an issue?

**Comment by sinedie** [comment]
Hey there, Idk if it belongs here... I'm having this issue, when I use goto(url) everything is fine, but if I want to stay in the same page it does not work.

```
<script>
    import { goto } from '@roxi/routify'
    import { authorize } from "../../utils/authorization";
</script>

{#await authorize()}
    Checking credentials
{:then authorized}
    {#if authorized}
        <slot />
    {:else}
        {$goto('/login', {}, true)}        //         {$goto('/login')} works
    {/if}
{:catch}
    {$goto('/login', {}, true)}            //         {$goto('/login')} works
{/await}


```

**Comment by rraihansaputra** [comment]
> Hey there, Idk if it belongs here... I'm having this issue, when I use goto(url) everything is fine, but if I want to stay in the same page it does not work.
> 
> ```
> <script>
>     import { goto } from '@roxi/routify'
>     import { authorize } from "../../utils/authorization";
> </script>
> 
> {#await authorize()}
>     Checking credentials
> {:then authorized}
>     {#if authorized}
>         <slot />
>     {:else}
>         {$goto('/login', {}, true)}        //         {$goto('/login')} works
>     {/if}
> {:catch}
>     {$goto('/login', {}, true)}            //         {$goto('/login')} works
> {/await}
> ```

@sinedie I just had a problem with this, and to navigate to the current route you need to do `$goto(null, {}, true)` instead of putting the current route in the function

**Comment by jakobrosenberg** [comment]
@sinedie that looks like a different issue. If `null` works, but `/actual/path` doesn't, it sounds like a bug.

**Comment by sinedie** [comment]
Maybe i wasn't clear, my bad.

Im trying to go to `/login`, but keep the route in `/home` or whatever route im protecting. This way I can see if the user is logged and if not send him/her to login page and when get logged again it returns to `/home` and not to `/`

**Comment by ghostdevv** [comment]
@sinedie I may have misunderstood, you want it so if a user isn't logged in they are taken to `/login` and then once logged in redirected to the path the were previously at?

**Comment by jakobrosenberg** [comment]
I think @sinedie wants the login screen to show on the `/home` url if the user isn't logged in. Correct?

**Comment by sinedie** [comment]
Exactly. Sry for the late reply.

When try to use `$goto('/login', {}, true}` in component initialization, it breaks... I guess i'll use `$goto{'/login'}` for the moment. Could be good to have that feature tho.
