### ISSUE TITLE
Get title from <svelte:head><title>

### ISSUE THREAD

**Issue by tv42** [roxiness/routify#253]
I'm used to https://svelte.dev/docs#svelte_head

```
<svelte:head>
  <title>Foo</title>
</svelte:head>
```

and it works great.

Routify, however, tells me to do (https://routify.dev/guide/metadata)

```
import { metatags } from '@sveltech/routify'
metatags.title = 'Foo'
```

And then *Routify* creates a `<title>` for me from that.

Could Routify please deviate less from mainstream Svelte usage?  
Could it extract the title from `<svelte:head>`?

**Comment by jakobrosenberg** [comment]
The metatags option is optional. You can still use `<svelte:head>`.

`metatags` is intended for dynamic meta data, templates and Open Graph.

**Comment by tv42** [comment]
It would be very neat to access this in the automatic routing.

**Comment by jakobrosenberg** [comment]
Is this what you have in mind? That's from root layout of http://routify.dev

```javascript
  import { metatags, page } from "@sveltech/routify";
  const capitalize = str => str.charAt(0).toUpperCase() + str.slice(1);
  metatags.template("title", title => `${title ? ` ${title} - ` : ""}Routify`); // sets a template for the title prop
  $: metatags.title = capitalize($page.title); // updates title on page change
```
