### ISSUE TITLE
Pages are passed unwanted & undocumented prop `index`

### ISSUE THREAD

**Issue by tv42** [roxiness/routify#255]
```
$ cat src/pages/test/foo.svelte 
<h1>hello, world</h1>
```

Accessing that in browser leads to console warning:

```
index.js:72 <Foo> was created with unknown prop 'index'
```

Adding `export let index` and a `console.log` says it's a string "/test/foo".

Since Svelte complains about unhandled props, this seems quite undesirable.  
The string value doesn't seem very useful, either.  
The prop is also undocumented.

**Comment by jakobrosenberg** [comment]
I've never seen this before. Either you have an `[index]` folder or `[index].svelte` file or there's a bug in Routify. Could you share your project?

**Comment by tv42** [comment]
This is proving tough to reproduce outside of a larger project. I'll try to chip away at the difference. My codebase has no mention of `index` so I can't explain it away either.

**Comment by tv42** [comment]
Stack trace leads to this in routify/runtime/Route.svelte:

```
{#if $context}
  {#if $context.component.isLayout === false}
    {#each [$context] as { component, componentFile } (getIndex(component))}
      <svelte:component
        this={componentFile}
        let:scoped={scopeToChild}
        let:decorator
**        index={getIndex(component)}  ***
        {scoped}
        {scopedSync}
        {...layout.param || {}} />
```

https://github.com/roxiness/routify/blob/v2.1.0/runtime/Route.svelte#L124

**Comment by tv42** [comment]
https://github.com/roxiness/routify/commit/1e7bf2c23b9eb6b1678a6a832650fd5183761506

**Comment by jakobrosenberg** [comment]
Thanks for catching that. That shouldn't be in there.

**Comment by ghostdevv** [comment]
@jakobrosenberg can this be closed?
