### ISSUE TITLE
Be consistent between [slug] and :slug in URLs

### ISSUE THREAD

**Issue by tv42** [roxiness/routify#256]
Documentation mostly talks about [slug] and since file names expose that usage, well, that's what the library should use. However, when you start looking deeper into things, you start seeing some :slug style usage too, for example `$layout.children[0].path` looks like `/documents/:slug/blah`, not `/documents/[slug]/blah`.

**Comment by jakobrosenberg** [comment]
`/document/:slug` has long been the convention for URLs, but since colons are illegal characters in Windows and we try to follow the file structure scheme of Sapper, we use `/document/[slug].svelte`.

Most URL libraries follow the same `/document/:slug` scheme.

**Comment by ghostdevv** [comment]
Can this be closed @tv42 @jakobrosenberg
