### ISSUE TITLE
$layout.children[0].path is undocumented, unexplained, unnecessarily magic

### ISSUE THREAD

**Issue by tv42** [roxiness/routify#257]
It seems for `src/pages/test/[slug]/foo.svelte` when visiting `/test/quux/foo`, the corresponding `$layout.children` entry will contain `path=="/test/:slug/foo"`

1. I expected it to contain `/test/quux/foo`, and would find that a lot easier to deal with. Why must I as the consumer sprinkle `$url` everywhere, when I could just be handed actual, working, URLs. Having concrete URLs would also decrease the magic; it is very unclear where `$url` populates the parameters from, and that just seems unnecessary.

2. This behavior seems completely undocumented.

I decided to file this here and not in https://github.com/roxiness/routify-site-2020 because I was hoping for an actual code behavior change, not just documentation.

**Comment by jakobrosenberg** [comment]
What you're looking for is `location.pathname`

`/blog/:slug` is the static path, same way as `/blog/[foo].svelte` is the physical path. It allows you to access nodes in the AST at runtime.

https://routify.dev/docs/helpers#url

**Comment by ghostdevv** [comment]
Is this solved? @tv42
