### ISSUE TITLE
Treats Unix pathnames as if they were Windows pathnames

### ISSUE THREAD

**Issue by tv42** [roxiness/routify#259]
`lib/middleware/generateFileTree.js` has this line of code:

```
const absolutePath = path.resolve(absoluteDir, filename).replace(/\\/g, '/')
```

That means it's doing Windows-style backslash-to-slash conversion even on non-Windows platforms. That's confusing and unexpected.

This also seems inadequate for Windows, if the `pages` config variable looks like "D:\some\path". Which is kind of a weird thing to do, but nothing says it has to be a relative path either.

Node.js `path` library isn't hugely helpful here, but `path.sep` and `path.posix` might apply.
https://nodejs.org/api/path.html#path_path_sep  
https://nodejs.org/api/path.html#path_path_posix

**Comment by jakobrosenberg** [comment]
Would you be interested in doing a PR?

**Comment by Wolfr** [comment]
Just out of curiosity, who would write backslashes in their paths? Where is this common?

**Comment by tv42** [comment]
@Wolfr It's more a question of not doing something confusing and wrong when weird things happen.

**Comment by ghostdevv** [comment]
This doesn't seem to be a issue really, so will close. Feel free to comment if you disagree
