### ISSUE TITLE
Decrease delay between content and page title updates

### ISSUE THREAD

**Issue by manvankaliber** [roxiness/routify#263]
**bug description**
When switching between routes when using a chromium based browser, in the worst case scenario,  there is a 3s delay between the `<title></title>` and `<body></body>` updating. You see this on every site build using Sapper. It also happens on https://routify.dev/blog

Please see my issue here for screen recordings and more information: https://github.com/sveltejs/sapper/issues/1181

**version**
The one used on routify.dev

**screenshot**
Again, see my original issue: https://github.com/sveltejs/sapper/issues/1181

**Comment by jakobrosenberg** [comment]
Have you tried logging the text of <title> programmatically?

**Comment by manvankaliber** [comment]
> Have you tried logging the text of <title> programmatically?

Do you mean logging the right before and after navigation?

**Comment by jakobrosenberg** [comment]
Yes. Right after should be enough.

**Comment by Wolfr** [comment]
Like in your Sapper issue, I don't experience the delay you are talking about when testing page changes.

**Comment by manvankaliber** [comment]
After testing it seems to just be a chromium browser limitation. Have not tested firefox or other browsers.
Other frameworks experience the exact same issues. There is not much that can be done about this so i'm closing the issue for now.
