### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Tommertom** [roxiness/routify#264]
**Is your feature request related to a problem? Please describe.**
Getting Typescript error  `JSX element type 'Router' does not have any construct or call signatures.ts(2604)`

![image](https://user-images.githubusercontent.com/16119174/92276819-0618b400-eef2-11ea-818f-c81b4ce55a4f.png)

**Describe the solution you'd like**
No error

**Describe alternatives you've considered**
None

**Additional context**
Since svelte has official Typescript support typescript definitions may be needed?

**Comment by jakobrosenberg** [comment]
Hi @Tommertom, please have a look here. Would be happy to know if your experience is the same. 🙂
https://github.com/roxiness/routify/issues/248

**Comment by Tommertom** [comment]
Hi,tx. Will respond in the mentioned issue.
