### ISSUE TITLE
Invalid tags after build

### ISSUE THREAD

**Issue by timoanttila** [roxiness/routify#265]
This is not really critical bug, but we devs often want to make our projects as well as we can and errors like these are not nice to have. Routify renders two invalid tags automatically while using build command (`npm run build`). Type can't be module if there is defer and meta needs some kind of content or name to be valid. The first line is without prerendering too (`npm run dev`). Using `@sveltech/ssr` for builds.

```
<script type="module" defer="" src="/build/main.js"></script>
<meta data-render="prerendered">
```
https://pasteboard.co/JpGZ3Fy.png

My sources: https://github.com/timoanttila/tuspe

**Comment by jakobrosenberg** [comment]
Thanks @timoanttila. I'll get on this. Any suggestions for handling the meta tag?

**Comment by timoanttila** [comment]
> Any suggestions for handling the meta tag?

The "module" should be like this:
`<script src="/build/main.js" defer></script>`

But why defer? Why not async and execute it soon as possible? Need to be sure that whole html is ready before that can be done?

Is the content from Routify or @sveltech/ssr, because there is only link to another file. I would like to preload the right file, but it's randomly named file and it changes everytime when Netlify uses npm run build. But I guess it starts checking the right file too if that is preloaded.

```
export{A as default}from"./main-d61fb164.js";
//# sourceMappingURL=main.js.map
```
The prerendered could be something like this (why we even need this one):
`<meta name="render" data-render="prerendered">`

**Comment by jakobrosenberg** [comment]
`defer` is an old leftover, it shouldn't be there. As for `type="module"`, that's required dynamic imports IIRC.

The meta tag was created for the app to be able to tell if it was prerendered. in hindsight, this could be done with JS. Not sure which is cleaner though.

**Comment by ghostdevv** [comment]
Is this still a thing? @jakobrosenberg

**Comment by jakobrosenberg** [comment]
They should be fixed IIRC.
