### ISSUE TITLE
MIgration Guide not sufficient to migrate to 2.0.0

### ISSUE THREAD

**Issue by Tommertom** [roxiness/routify#266]
**bug description**
I followed the migration guide https://routify.dev/blog/routify-2#migration-guide to migrate my sveltech/routify 1.9.9 to roxio. But what followed was a picture of something I nothing designed..... App breaking (to summarise)

**package.json**
```
{
    "name": "svelte-app",
    "version": "1.0.0",
    "scripts": {
        "build": "rollup -c",
        "dev": "run-p watch:routify watch:rollup",
        "watch:rollup": "rollup -c -w",
        "rollup": "rollup -cw",
        "watch:routify": "routify -D",
        "start": "sirv public --single",
        "validate": "svelte-check"
    },
    "devDependencies": {
        "@capacitor/core": "^2.4.0",
        "@ionic/core": "^5.3.2",
        "@rollup/plugin-commonjs": "^14.0.0",
        "@rollup/plugin-node-resolve": "^8.0.0",
        "@rollup/plugin-typescript": "^4.0.0",
        "@sveltech/routify": "^1.9.9",
        "@tsconfig/svelte": "^1.0.0",
        "cupertino-pane": "^1.1.81",
        "firebase": "^7.19.1",
        "localforage": "^1.9.0",
        "npm-run-all": "^4.1.5",
        "prettier": "^2.0.5",
        "prettier-plugin-svelte": "^1.2.0",
        "rollup": "^2.3.4",
        "rollup-plugin-copy": "^3.3.0",
        "rollup-plugin-delete": "^2.0.0",
        "rollup-plugin-livereload": "^2.0.0",
        "rollup-plugin-svelte": "^6.0.0",
        "rollup-plugin-terser": "^7.0.0",
        "rxjs": "^6.6.2",
        "svelte": "^3.0.0",
        "svelte-check": "^1.0.0",
        "svelte-custom-elements": "^1.0.2",
        "svelte-preprocess": "^4.0.0",
        "tslib": "^2.0.0",
        "typescript": "^3.9.3"
    },
    "dependencies": {
        "sirv-cli": "^1.0.0"
    }
}

```
Not using the rollup plugin
Repo:  https://github.com/Tommertom/svelte-ionic-app

**version**
See package.json

**screenshot**
My app was `virused` by Routify - no longer my own pretty design.

![image](https://user-images.githubusercontent.com/16119174/92321997-d9b68200-f02e-11ea-8b17-47bd6eab4eed.png)

**Comment by flayks** [comment]
I went through the same issue switching from 1.9.9 to 2.x and basically, I fixed it using the routes generated by Routify using this line on the [routify-starter](https://github.com/roxiness/routify-starter/blob/master/src/App.svelte#L3) template:
```javascript
import { routes } from "../.routify/routes";
```

**Comment by Tommertom** [comment]
Thx,
that was the issue indeed.
I opted to configure the output dir in package.json to go for a different location.
Maybe the guide can be updated by the owner to reflect this issues and give kudos to @flayks ?
Regards
Tom

**Comment by Tommertom** [comment]
Oops. Keeping open until response from owner. He can choose.

**Comment by jakobrosenberg** [comment]
Thanks for bringing this up.

Fixed here. https://github.com/roxiness/routify-site-2020/commit/03719c82726164a51297487ec5df14db844f77fa
