### ISSUE TITLE
routify export srcPath not configurable

### ISSUE THREAD

**Issue by qwertasyx** [roxiness/routify#267]
Hi,

routify export looks for the bundled files in the distDir not the buildDir

https://github.com/roxiness/routify/blob/3ffea96dfa827e954a109d39345cfed816549909/lib/services/exporter.js#L13

**Comment by Easy-Cloud-in** [comment]
How to configure  3rd-party dependencies and put 

 external: [''xxxxxxxxx'],
  globals:

in rollup.config.js

**Comment by jakobrosenberg** [comment]
@qwertasyx sorry about the slow reply. Routify's export function will soon be deprecated in favor of [spank](https://github.com/roxiness/spank).

It should be very easy to install and run. If not, let me know. 😉

**Comment by ghostdevv** [comment]
It's been a few months so assuming this is ok, feel free to reopen if it's not
