### ISSUE TITLE
No way to change the ports

### ISSUE THREAD

**Issue by NetOpWibby** [roxiness/routify#268]
Since routify uses spassr under the hood I thought `--ssr-port` would work but sadly that is not the case.

**Comment by jakobrosenberg** [comment]
Spassr is part of the starter template, not Routify itself. You can modify the arguments for Spassr here:
https://github.com/roxiness/routify-starter/blob/master/scripts/base.config.js#L22

**Comment by NetOpWibby** [comment]
Ah, thanks!
