### ISSUE TITLE
Question - run-p

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#27]
What does the `run-p` command refer to? I was trying to use this router but got stuck on the installation. First on having to install `sirv` (should it not be a devDependency?) and then on 

````
> run-p watch:routify watch:rollup

sh: run-p: command not found
````

Does this refer to this project? https://github.com/mysticatea/npm-run-all

@jakobrosenberg - It looks like you have some local setup that I do not have.

**Comment by Wolfr** [comment]
I got it working by installing `sirv-cli` globally. That might be one for the docs?

**Comment by jakobrosenberg** [comment]
Hi @Wolfr 

It's listed under devDependencies, but I'll add install instructions as well.

If you prefer, you can install it locally instead.
