### ISSUE TITLE
Issue with Typescript

### ISSUE THREAD

**Issue by MirrorBytes** [roxiness/routify#271]
**bug description**
```Could not find a declaration file for module '@sveltech/routify/hmr'.```

Now this could be an issue with my TS config, so I'll provide that as well.

**tsconfig.json**
```
{
  "compilerOptions": {
		"module": "esnext",
		"moduleResolution": "node",
		"target": "esnext",
		"typeRoots": [ "@types", "typings" ],
		"rootDir": "./src",
		"esModuleInterop": true,
		"noUnusedParameters": true,
		"noUnusedLocals": true,
		"noImplicitReturns": true,
		"strict": true,
		"downlevelIteration": true,
		"resolveJsonModule": true,
		"allowSyntheticDefaultImports": true,
		"noEmit": true,
	},
	"include": [ "src", "@types", "typings" ]
}
```

**package.json**
```
"scripts": {
		"dev": "NODE_ENV=development routify -c rollup -cw",
		"build": "NODE_ENV=production routify -b && rollup -c",
		"start": "sirv public -H 0.0.0.0"
	},
```

**version**
Svelte: ^3.24.0
Routify: ^1.9.9

**Comment by jakobrosenberg** [comment]
There should be a definition in `@sveltech/routify/typings/hmr.dts`, but I can't say why it's not found in your project.

**Comment by MirrorBytes** [comment]
I located it. I figured the only way to bypass was the good 'ol ```/* @ts-ignore */```

**Comment by jakobrosenberg** [comment]
I'm closing this for now. Will reopen if needed.

**Comment by madeleineostoja** [comment]
I also ran into this FWIW, nothing funky in my tsconfig, just can't find the declaration for the `hmr` module

**Comment by MirrorBytes** [comment]
It looks as if Typescript isn't looking at the `@roxi/routify/typings` directory if it's not required in a root type declaration file. It's an odd problem.

Again, /* @ts-ignore */ fixed it (even though it shouldn't require that) without breaking anything else.

**Comment by jakobrosenberg** [comment]
@MirrorBytes would you be interested in a PR? 🙂

**Comment by MirrorBytes** [comment]
Sure, but I'm thinking how to resolve the issue without using /* @ts-ignore */. I know removing the declarationDir, or converting the entire project to TS will work. But I'm not sure how willing you'd be to either of those options considering removing declarationDir would make it messy, and a conversion would take a little bit to implement.

**Comment by jakobrosenberg** [comment]
@MirrorBytes would you check if this is fixed in `2.2.1@next-major`.

**Comment by MirrorBytes** [comment]
@jakobrosenberg It did not fix it sadly.

**Comment by jakobrosenberg** [comment]
Strange, I was hoping this would fix it. https://github.com/roxiness/routify/commit/38b352604146c23fb7dbb25d0f43afe3e00c8c5b

**Comment by MirrorBytes** [comment]
It's as if it doesn't see the declaration in the file

**Comment by MirrorBytes** [comment]
I got it to recognize it by adding "@roxi/routify" to types in my tsconfig. However, new error:

```Type 'typeof import("... /node_modules/@roxi/routify/typings/hmr")' has no call signatures.```

**Comment by MirrorBytes** [comment]
Fixed it.

```typescript
declare module '@roxi/routify/hmr' {
  import HMR from '@roxi/routify/typings/hmr'
  export default HMR
}
```

**Comment by jakobrosenberg** [comment]
Won't that cause bugs in an ambient declaration file?

**Comment by MirrorBytes** [comment]
I believe as of TS 2.9 you're able to import type declarations, both global and scoped, without issue.

But you could do this as well:

```typescript
declare module '@roxi/routify/hmr' {
  let hmr: typeof import('./typings/hmr').default
  export default hmr
}
```

**Comment by MirrorBytes** [comment]
To be clear, this is my current tsconfig:

```json
{
  "compilerOptions": {
		"module": "esnext",
		"moduleResolution": "node",
		"target": "esnext",
		"types": [ "svelte", "@roxi/routify" ],
		"rootDir": "./src",
		"esModuleInterop": true,
		"noUnusedParameters": true,
		"noUnusedLocals": true,
		"noImplicitReturns": true,
		"strict": true,
		"downlevelIteration": true,
		"resolveJsonModule": true,
		"allowSyntheticDefaultImports": true,
		"noEmit": true,
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
	},
}
```

And modifying your existing ```index.d.ts``` in "2.2.1@next-major" to include the ```.default``` is what fixed the issue for me.

**Comment by jakobrosenberg** [comment]
Thanks, completely missed the default. Pushed a new release.
