### ISSUE TITLE
Route could not be found for ""

### ISSUE THREAD

**Issue by MirrorBytes** [roxiness/routify#272]
**bug description**
With a ```_layout.svelte``` file, the first route that appears in the ```_tree.children``` array doesn't render and throws this error.

**version**
Routify: ^2.0.0
Svelte: ^3.24.0

**screenshot**

![Screenshot 2020-09-16 230126](https://user-images.githubusercontent.com/22119469/93415031-9818a900-f870-11ea-97b2-517a671243c4.png)
![Screenshot 2020-09-16 230057](https://user-images.githubusercontent.com/22119469/93415032-9818a900-f870-11ea-8565-cf978fc55381.png)

**Comment by jakobrosenberg** [comment]
Could you try `2.1.3@next-major`

**Comment by MirrorBytes** [comment]
Worked like a charm! No other change needed.
