### ISSUE TITLE
Svelte/ Routify Error “missing global variable name”

### ISSUE THREAD

**Issue by vishalisakar** [roxiness/routify#277]
When I am importing  "AmazonCognitoIdentity" in my Routify project  I am getting "missing global variable name" error.

Error Message:

```
bundles src/main.js ÔåÆ dist\build\bundle.js...
LiveReload enabled
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
/js/amazon-cognito-identity.min.js (imported by src\pages\_components\Login.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
/js/amazon-cognito-identity.min.js (guessing 'amazonCognitoIdentity_min_js')
created dist\build\bundle.js in 2.7s
bundles src/sw.js ÔåÆ dist\sw.js...
created dist\sw.js in 1.6s
```

Following is my code

`import { AmazonCognitoIdentity } from "/js/amazon-cognito-identity.min.js";`

```
const authenticationData = {
    Username: userName,
    Password: password,
  };
  const authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails(
    authenticationData
  );
  console.log(authenticationDetails);
  const poolData = {       
    UserPoolId: "xxxx”
    ClientId: "xxxxxxx", 
  };
  const userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
  const userData = {
    Username: userName,
    Pool: userPool,
  };
  console.log(userData);
  const cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);

  cognitoUser.authenticateUser(authenticationDetails, {
    onSuccess: function (result) {
      const accessToken = result.getAccessToken().getJwtToken();
      console.log(`on sucess: ${accessToken}`);
    },

    onFailure: function (err) {
      console.log(`onfailure: ${err}`);
      console.log(err);
    },
  });
```

and also I’ve linked the following file in _index.html

```
<script src="./js/amazon-cognito-identity.min.js"></script>
<script src="./js/amazon-cognito-auth.min.js"></script>
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js"></script>
```

And the same process in working good in normal Html ad JavaScript files.

**Comment by jakobrosenberg** [comment]
Routify doesn't touch your dependencies, so I expect this is a bundler issue. Any chance this is relevant? https://github.com/sveltejs/rollup-plugin-svelte/issues/54

**Comment by elimisteve** [comment]
Elsewhere I read that the filesystem path in

    import { AmazonCognitoIdentity } from "/js/amazon-cognito-identity.min.js";

should begin with a period (and thus look more like `./js/amazon-cognito-identity.min.js`) because importing from `/js/...` means it's trying to import from the absolute path `/js/...` on your local system, _not_ the root of your project, which is probably what you meant!

**Comment by jakobrosenberg** [comment]
Good catch @elimisteve. I'm closing this for now.

**Comment by elimisteve** [comment]
@vishalisakar And unless you're writing an Electron app, then

    <script src="./js/amazon-cognito-identity.min.js"></script>

should begin with `/js/...`; that is, start with a `/` (which is a _URL_ path, not a filesystem path, since that code is running in the browser) and thus probably be

    <script src="/js/amazon-cognito-identity.min.js"></script>
