### ISSUE TITLE
Test project with tabs - contains Webpack equivalent of build commands

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#28]
I tried a simple project where one would have 4 links that would lead to 4 tabs.

App.svelte needs the following content

````
<script>
  import { Router } from "@sveltech/routify";
  import { routes } from "@sveltech/routify/tmp/routes";
</script>

<Router {routes} />
````

Then, every route should be .svelte file in pages; with a possibility of inheriting a global layout (`_layout.svelte`) and a specific template for the 404 (`_fallback.svelte`).

Now, be careful, because the `scripts` in package.json also need to be updated:

Use this if you use rollup:

````
  "scripts": {
    "build": "rollup -c",
    "dev": "run-p watch:routify watch:rollup",
    "watch:rollup": "rollup -c -w",
    "watch:routify": "routify",
    "start": "sirv public --single"
  },
````

Use this for webpack:

````  "scripts": {
    "build": "cross-env NODE_ENV=production webpack",
    "dev": "run-p watch:routify watch:webpack",
    "watch:webpack": "webpack-dev-server --content-base public",
    "watch:routify": "routify"
  },
````

You can find my project at https://github.com/Wolfr/routify-tabs .

There's no issue with it, I wanted to make an issue, but then I solved the problem myself.

Just wanted to show some activity ;) and appreciation for building a file-based router.

**Comment by jakobrosenberg** [comment]
If you add a ``<slot />`` to _layout.svelte and create an ``index.svelte``, the tabs will be shown in your layout and you'll be able to keep the links on all pages.
