### ISSUE TITLE
$goto / $redirect broken on _fallback with $leftover

### ISSUE THREAD

**Issue by lalilaloe** [roxiness/routify#283]
While trying to replicate the CRUD example from the example repo, actually building it from scratch i'm encountering the following problem.

**bug description**
Using a _fallback page, where _fallback is located in admin folder (for CRUD). Going to the url:
admin/User/select > Show select component to select user you want to edit
admin/User/123 > (id) Show edit component loaded with id from url
```
const [type, identifier] = $leftover.split("/");
```
type here is 'User', 'Group' etc. (the model to do CRUD with)
identifier is an id or 'select', 'list', 'create'

Based on these input the correct component is loaded. But when a user is selected and $goto the edit screen it changes the url but does not navigate to the page. This either a bug or a feature, but from my point of view i want it to navigate tot the page. With a refresh the page is loaded. Also urls that go back or to another page do work with $goto or $redirect.

**repo**
I created a little repo with the code setup the way i use it loading components dynamicly based on $leftover value, maybe that has something to do with it.

[https://gitlab.com/lalilaloe/routify-bug-test](https://gitlab.com/lalilaloe/routify-bug-test)

**version**
```
"@sveltech/routify": "^1.9.9",
"svelte": "^3.29.4"
```

**screenshot**
![demo](https://user-images.githubusercontent.com/9057622/97804338-6ce6ef00-1c4f-11eb-875d-38aaa705f100.gif)

**Comment by jakobrosenberg** [comment]
Would you try `2.5.1`?

**Comment by lalilaloe** [comment]
I did, same results [lalilaloe/routify-bug-test#2.5.1](https://gitlab.com/lalilaloe/routify-bug-test/-/tree/2.5.1)

**Comment by jakobrosenberg** [comment]
I recently added `param-is-page` and `query-params-is-page`. It's possible I could add a third option `url-is-page`. That would reload on any URL change.

Before I add it to the todolist, would you check if `<!-- routify:options query-params-is-page -->` could solve your problem? Adding it to a layout or page, will reload the component if parameters change.

**Comment by lalilaloe** [comment]
When i add ```<!-- routify:options query-params-is-page -->``` i get the following error and the routes are not being build.

![image](https://user-images.githubusercontent.com/9057622/98271884-b48fb280-1f90-11eb-8265-40b95d960432.png)

**Comment by jakobrosenberg** [comment]
Sorry my mistake. It should be 
```
<!-- routify:options query-params-is-page=true -->
```

**Comment by lalilaloe** [comment]
Aha no problem, the same behavior occurs. No changes there, if i added correctly above the scripttag?
![image](https://user-images.githubusercontent.com/9057622/98272312-3f70ad00-1f91-11eb-8e75-f64bcd13d4ab.png)

**Comment by jakobrosenberg** [comment]
Placement shouldn't matter, but it seems it hasn't picked up on the `=true`

**Comment by lalilaloe** [comment]
It did build though

**Comment by jakobrosenberg** [comment]
@lalilaloe I rewrote a bit of metadata code, so that `=true` is implied if omitted.

I'm closing this for now, but will reopen if issue persists.
