### ISSUE TITLE
Promise error when waiting api response

### ISSUE THREAD

**Issue by timeshift92** [roxiness/routify#285]
**First rule of bug posting**
**There are no rules!**

#### With that out of the way, there are a few things that might help us help you faster. You pick and choose what you think is relevant.

**bug description**
when sending a request, probably because of a long wait or I do not know why this error occurs, it is still possible graphql endpoint

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read property 'createElement' of undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**package.json**
```
{
   "name": "svelte-app",
   "version": "1.0.0",
   "@comments scripts": {
      "dev": "develop with blazing fast rebuilds",
      "dev:features": "develop with features like SSR and serviceworker enabled",
      "build": "run build scripts below",
      "build:app": "build single page application (SPA)",
      "build:static": "Generate static pages",
      "serve": "serve content in 'dist' folder",
      "rollup": "run the rollup bundler",
      "nollup": "run the nollup no-bundler",
      "routify": "run routify"
   },
   "scripts": {
      "dev": "run-p routify nollup",
      "dev:ssr": "run-p routify rollup",
      "build": "run-s build:*",
      "build:app": "routify -b && rollup -c",
      "build:static": "spank",
      "serve": "spassr --ssr",
      "rollup": "rollup -cw",
      "nollup": "nollup -c",
      "routify": "routify",
      "validate": "svelte-check"
   },
   "devDependencies": {
      "@rollup/plugin-commonjs": "^15.0.0",
      "@rollup/plugin-node-resolve": "^10.0.0",
      "@rollup/plugin-typescript": "^6.1.0",
      "@roxi/routify": "^2.7.3",
      "@tsconfig/svelte": "^1.0.10",
      "cross-env": "^7.0.2",
      "fs-extra": "^9.0.1",
      "nollup": "^0.13.13",
      "npm-run-all": "^4.1.5",
      "postcss": "^8.1.7",
      "postcss-import": "^13.0.0",
      "rollup": "^2.33.2",
      "rollup-plugin-hot": "^0.1.1",
      "rollup-plugin-livereload": "^2.0.0",
      "rollup-plugin-svelte": "^6.1.0",
      "rollup-plugin-svelte-hot": "^0.11.1",
      "rollup-plugin-terser": "^7.0.2",
      "rollup-plugin-workbox": "^5.2.1",
      "spank": "^1.4.0",
      "spassr": "^2.1.6",
      "svelte": "^3.29.7",
      "svelte-check": "^1.1.12",
      "svelte-preprocess": "^4.5.2",
      "tossr": "^1.3.1",
      "tslib": "^2.0.3",
      "typescript": "^4.0.5"
   },
   "dependencies": {
      "graphql-svelte": "^1.2.3",
      "hasura-orm": "^0.1.8"
    },
   "routify": {
      "extensions": "svelte,html,svx,md"
   },
   "spassr": {
      "assetsDir": [
         "dist",
         "assets"
      ],
      "script": "dist/build/main.js",
      "ssrOptions": {
         "inlineDynamicImports": true
      }
   },
   "spank": {
      "blacklist": [
         "/example/modal/basic/4"
      ]
   }
}


```

**version**
Routify - 2.7.3, Svelte 3.29.7, etc. whichever you think might be relevant.

**screenshot**

![Screenshot from 2020-11-15 17-50-31](https://user-images.githubusercontent.com/13614530/99185369-3343d700-276b-11eb-8568-3dfa285354f2.png)

**Comment by jakobrosenberg** [comment]
I'm guessing you have an async call resolving after JSDOM has closed the current page while prerendering pages.

Async code can be handled by either skipping it on the server by checking `window.routify.inBrowser` or by letting Routify and JSDOM know when the page is ready, by calling the `$ready()` helper at the end of your async code.

https://routify.dev/docs/helpers#ready

**Comment by timeshift92** [comment]
Thanks, i will change change timeout on tossr library (before 5000 ms after 10000ms)
