### ISSUE TITLE
url() empty on _fallback page

### ISSUE THREAD

**Issue by mathiasrw** [roxiness/routify#292]
**What did you experience**
`url()` returns nothing when used on a _fallback.svelte page. 

**What did you expect**
I was expecting to get the url requested by the user.

**package.json**
`yarn dev`

**version**
Latest of everything

**Comment by jakobrosenberg** [comment]
Hi @mathiasrw. The `url` helper uses paths relative to the file system, not the current URL.

If your `_fallback.svelte` is in the root, then `$url()` will return the root path. However, if your `_fallback.svelte` is located in a subfolder, it would be a bug for `$url` to return empty.

**Comment by mathiasrw** [comment]
Ohh - ok. 

I guess its not a bug then. Its giving me an empty string = root path `/` but as the first '/' is always stripped from the beginning of what url() returns. 

I guess I was just confused about the name. Sounds like "file path" would be more specific. All good. Just learning my way around this beauty.

**Comment by jakobrosenberg** [comment]
No problem. It's a common misconception. I guess the semantic name would be `relativeFilepathToAbsoluteUrl`.

While that name is too verbose, it does explain what the helper does. `url` could then be the syntactic sugar.
