### ISSUE TITLE
#each $layout.children fails

### ISSUE THREAD

**Issue by mathiasrw** [roxiness/routify#293]
With the latest version on svelte and routify we get an error trying to generate a navigation 

```
<script>
  import {layout} from "@roxi/routify";
</script>

{#each $layout.children as node}
  {node.title}
{/each}
```

![image](https://user-images.githubusercontent.com/1063454/101505985-3484b000-3975-11eb-8725-36ff51c86fae.png)

**Comment by mathiasrw** [comment]
Turns out you need a _layout.svelte file to access $layout

**Comment by jakobrosenberg** [comment]
@mathiasrw which version of Routify are you on? IIRC $layout was recently fixed to also work outside of `_layout.svelte`.

**Comment by mathiasrw** [comment]
I have `^2.5.1-next-major` in my package.json

I simply followed the steps to install from the website yesterday. 

![image](https://user-images.githubusercontent.com/1063454/101622375-41f27680-3a17-11eb-9391-3076e7a40373.png)

**Comment by jakobrosenberg** [comment]
Could you try 2.7.3 (stable) or 2.7.5-next?

**Comment by mathiasrw** [comment]
It works with 2.7.3 :)
