### ISSUE TITLE
How to define a generic fallback?

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#3]
In case some url is not hit by a file.

**Comment by jakobrosenberg** [comment]
Good question. I guess we could add a 404.svelte in the main folder. I think that's what Sapper does.

**Comment by tombroens** [comment]
Or call it _fallback.svelte or _default.svelte as it can also be wanted functionality. Probably its not always a 404?

Would it be useful to use the folder traversal tree and seperate _defaults? Something like below, or too difficult to be usefull?

/path1
-> _default.svelte (hence if no index.svelte is present this is also the index)
/path1/path2
-> _default.svelte (hence if no index.svelte is present this is also the index)

/path1/path2/path3
-> nothing present -> visiting this url reverts to /path1/path2/_default.svelte

**Comment by jakobrosenberg** [comment]
I like the idea of _fallback. _default could cause some confusion.

We're on the same track with the traversal. I'm thinking of including layouts with the _fallback.

In case someone doesn't want to use layouts, there's always the option of ``style="position:fixed; left:0; right:0; top:0; bottom:0"``

Somewhat off topic, but would a skip-parent-layouts syntax make sense? Kind of like standalone modules that doesn't feature parent navigational bars etc. Kind of like a login screen or a 404.

**Comment by jakobrosenberg** [comment]
_fallback.svelte support added to v1.2.0

**Comment by tombroens** [comment]
> Somewhat off topic, but would a skip-parent-layouts syntax make sense? Kind of like standalone modules that doesn't feature parent navigational bars etc. Kind of like a login screen or a 404.

Yes that would be useful I think. Probably there are use-cases where you want to keep working in a certain path but want to divert from the generic styling. Maybe by adding a _customlayout.svelte that is used as the sole layout for the files in that folder?
