### ISSUE TITLE
how to use routify with meteor

### ISSUE THREAD

**Issue by freeseamew** [roxiness/routify#300]
Now I'm trying to use a meteor and a svelte together.

We're already using "routify" in our exclusive project.

Is there any way to use "routify" in the meteor-svelte environment?

**Comment by jakobrosenberg** [comment]
Yes. You can use Routify anywhere you use Svelte.

Npm install Routify to your project and import the routes: 

 ```html

        <!-- src/App.svelte -->
        <script>
          import { Router } from "@roxi/routify";
          import { routes } from "../.routify/routes";
        </script>

        <Router {routes} />
      
```

Make sure to run `routify` in development mode and `routify --build` for production.

**Comment by freeseamew** [comment]
I couldn't find the path if I used the default import when I ran 'meteor'. So it was used as follows.
```
import { Router } from "@roxi/routify";
import { routes } from "@roxi/routify/tmp/routes";
```

At this time, 'routify' is recognized, but only the following messages appear on the screen to see if 'pages' path is not found.

```
Generating routes...

Your app should probably have loaded by now

This is likely caused by routifyDir not matching the routes import path in app.svelte
```

For your information, the structure of 'meteor' has been tried both ways to use it in 'meteor' and to create and use a src folder, but the results are the same as above.
```
meteor-svelte
meteor-svelte
├── .meteor
├── imports
    └── ui
         ├── pages 
         │    ├── home.svelte
         │    ├── post.svelte
         │    └── about.svelte
         ├── App.svelte
         └── main.js
```

```
meteor-svelte
├── .meteor
├── src
     ├── pages 
     │    ├── home.svelte
     │    ├── post.svelte
     │    └── about.svelte
     ├── App.svelte
     └── main.js
```

I understand that people who use 'meteor' are also interested in 'svelte'.

So if 'routify' works in 'meteor', I think it will be loved by many people.

If you know how to operate 'routify' from 'meteor', please give me a hint.

**Comment by jakobrosenberg** [comment]
Which version of Routify have you installed?

Also, make sure your `pages` path is correct. Ie. `routify --pages src/pages`.

**Comment by freeseamew** [comment]
routify is "@roxi/routify": "^2.7.3"

and meteor version is METEOR@1.11.1

If meteorjs was used, the src/pages path could not be used.

If you specify the path like this, an error occurs in the next part of main.js.

```
new App({
  target: document.getElementById('app')
});
```

The error content is "document is not defined" and occurs in the server.

So, when you put it under the imports folder like "imports/src/pages" and run it, the following message appears.

```
Generating routes...

Your app should probably have loaded by now

This is likely caused by routifyDir not matching the routes import path in app.svelte
```

**Comment by jakobrosenberg** [comment]
Going by this example
```
meteor-svelte
meteor-svelte
├── .meteor
├── imports
    └── ui
         ├── pages 
         │    ├── home.svelte
         │    ├── post.svelte
         │    └── about.svelte
         ├── App.svelte
         └── main.js
```

1. Verify project is working without Routify
2. Install Routify `npm install routify`
3. Run `routify --pages imports/ui/pages`
4. In App.svelte, import the generated routes from `../../.routify/routes.js`.

If you have a link to your template or guide, I might be able to get Routify to auto configure itself.

**Comment by freeseamew** [comment]
This is sample url link.

[https://github.com/freeseamew/meteor-svelte-routify-test](https://github.com/freeseamew/meteor-svelte-routify-test)

How to use is as follows.

1. after downloading from git
2. npm i
3. meteor run

If you download it from git and run this way, you can see that svelte is running in the meteor environment.

and In `App.svelte`, do the following to activate routify.

```
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "@roxi/routify/tmp/routes";
  // import { routes } from "../../.routify/routes.js";
</script>

<Router {routes} />


<!-- <script>
  import About from './pages/about.svelte'
  import Posts from './pages/posts.svelte'
</script>

<About />
<Posts /> -->
```
Then you can check the error message above.

**Comment by ghostdevv** [comment]
Are you still having issues? @freeseamew if so I can take a look

**Comment by freeseamew** [comment]
There are still issues. If you know how you can use meteor with routify, please let me know.

**Comment by ghostdevv** [comment]
@freeseamew I cloned the repo you linked above and had no issue generating routes with `routify --pages imports/ui/pages`

**Comment by freeseamew** [comment]
it's mean  to enter the routify --pages imports/ui/pages command into the terminal?

Currently, I run meteor run. However, the following error appears in the browser.

```
Generating routes...

Your app should probably have loaded by now

This is likely caused by **routifyDir** not matching the routes import path in **app.svelte**
```

**Comment by ghostdevv** [comment]
Either set the routifyDir to the one your importing or import the routes from .routify

**Comment by jakobrosenberg** [comment]
I wanted to post a config for this last week, but I couldn't get Meteor to build. It was taking hours everytime. Could be caused by pnpm.

If `imports/ui/` is the default path for Meteor projects, we could set that as the default path in Routify's configent config.

**Comment by ghostdevv** [comment]
@jakobrosenberg I didn't try running meteor but from the config he sent he is using the tmp dir in the routify package but his routes are generating to .routify so if he changes that it will work?

**Comment by jakobrosenberg** [comment]
I would assume so. I might have another go at it, but it could be a week or two from now.

**Comment by freeseamew** [comment]
Have you tested in'meteor'? If you've tried it, please share the operational setting method.

**Comment by jakobrosenberg** [comment]
What's the normal install time for a `meteor create myapp`?

I ran the command and it's been stuck for ages. SSD is an ADATA SX8200 Pro with 3500/3000MB read/write.

**Comment by jakobrosenberg** [comment]
Finally got Meteor to create an app.

1. Update Routify to `^2.10.0`
2. Update App.svelte:
```svelte
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../routify/routes.js";
</script>

<Router {routes} />
```

---

Note: version `2.10.0` detects Meteor and automatically applies the following config:
```json
{
  "pages": "imports/ui/pages",
  "routifyDir": "imports/routify"
}
```

**Comment by freeseamew** [comment]
Thank you for the config modification. 
However, there is still an error even if you set it up in the way I told you.

Currently, I updated it as follows.

```
{
  "name": "meteor-install-test",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@babel/runtime": "^7.11.2",
    "meteor-node-stubs": "^1.0.1",
    "svelte": "^3.31.2"
  },
  "devDependencies": {
    "@roxi/routify": "^2.10.1"
  }
}
```
/imports/ui/App.svelte was also set as follows: 

```
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../routify/routes.js";
</script>

<Router {routes} />
```
and The page files were placed in the exports/ui/pages folder.

However, the browser is getting the following error.

```
modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232 Uncaught Error: Cannot find module '../routify/routes.js'
    at makeMissingError (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232)
    at Module.resolve (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:238)
    at Module.moduleLink [as link] (modules.js?hash=a4623935f5f01291aad5464c3442b264b0ed25f0:296)
    at module (app.js?hash=11d713fa900798d25282cbefb5bc5b66ce7b604f:64)
    at fileEvaluate (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:346)
    at Module.require (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:248)
    at Module.moduleLink [as link] (modules.js?hash=a4623935f5f01291aad5464c3442b264b0ed25f0:303)
    at module (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:346)
    at Module.require (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:248)
```

**Comment by jakobrosenberg** [comment]
You need to run Routify in parallel as it monitors your file structure and uses it to rebuild routes.js on changes.

**Comment by jakobrosenberg** [comment]
Forgot to share this repo. You can see how to run Routify in parallel in package.json.

https://github.com/roxiness/meteor-routify

**Comment by freeseamew** [comment]
I checked that it runs with 'meteor npm start.'

Thank you!!
