### ISSUE TITLE
Using $goto inside a decorator throws build error

### ISSUE THREAD

**Issue by www-chique** [roxiness/routify#302]
### Description
I'm trying to use a **$goto** inside a decorator, to be used as an AuthGuard. Even though "npm run dev" is working as expected, the "npm run build" throws out the following error.
To debug the issue, I reproduced it in a default Routify installation, with only 2 minimal components specifically reproducing the issue.
```
Exporting 1 of 1 /indexD:\routify\node_modules\jsdom\lib\jsdom\browser\Window.js:256
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);
                                                                              ^
TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (D:\routify\node_modules\jsdom\lib\jsdom\browser\Window.js:256:79)
    at window.routify.stopAutoReady.t.page (eval at <anonymous> (D:\routify\node_modules\tossr\tossr.js:68:24), <anonymous>:7:17302)
    at eval (eval at <anonymous> (D:\routify\node_modules\tossr\tossr.js:68:24), <anonymous>:7:17621)
```

**My Setup**

```
<!-- src/pages/_layout.svelte -->
<script>
	import decorator from "./_AuthGuard.svelte";
</script>

<slot {decorator} />
```

```
<!-- src/pages/_AuthGuard -->
<script>
	import { goto } from "@roxi/routify";
	$goto("/"); //The line which is causing the error
</script>

<slot />
```

If I comment out the $goto line, the build process completes successfully.
Any help is appreciated.

**version**
Routify 2.7.3

**Comment by jakobrosenberg** [comment]
A) Can you verify that there's not an infinite loop?
B) What happens if you put the `$goto` in `_layout.svelte` instead?

It's possible that the code is looking for `window` after the instance has been destroyed.

**Comment by www-chique** [comment]
You are absolutely right!
It was indeed an infinite loop problem. 
Good to know, I learn from these mistakes.
Thank you so much for helping out always.

**Comment by jakobrosenberg** [comment]
Slightly off-topic, but I would bypass auth on the server and instead treat all SSR requests as unauthorized.

**Comment by www-chique** [comment]
If you're still talking about my redirection, it's purely cosmetic for the front-end experience.
The Routify app will communicate using REST API with the server, which in turn uses JWT Auth.
I appreciate the heads-up. 👍
