### ISSUE TITLE
Access to target route component in $beforeUrlChange

### ISSUE THREAD

**Issue by www-chique** [roxiness/routify#303]
**The problem**
I am implementing an Auth-guard using a decorator.
Currently, when the user needs to be restricted, the user needs to visit the restricted path, where the authentication check happens, and then redirected back. However in this approach,it adds a History entry to the restricted page in the browser.

**Solution I'd like**
It would be amazing to somehow access the target / next component inside $beforeUrlChange.
Specifically for my case, I'd like to access the Metadata of the target (next URL).
I want to do some conditional checks inside $beforeUrlChange, and prevent the page from navigating away in the first place.

**Additional context**
I'm pasting a conversation with Jake down here, might provide further technicalities
_JakeDKToday at 9:18 PM_
```
isn't the component passed to the beforeUrlChange function?
actually, it seems it isn't
I think I need to create a allComponents helper or similar

```

**Comment by jakobrosenberg** [comment]
Added this in `2.8.0`. `route` is the incoming page component and `url` contains the target URL.


```javascript
$beforeUrlChange((event, route, {url}) => {
  
})
```
