### ISSUE TITLE
Navigation pushes same URL again and again in history even if the navigation url is the same as current

### ISSUE THREAD

**Issue by DhyeyMoliya** [roxiness/routify#304]
**bug description**
When navigating to routes, if we click same navigation link multiple times, the navigation handling mechanism pushes the same url in history again and again. So, when we go back using back button of browser, it will go to the same URL until the URL is removed from the history state.

**package.json**
*Script* : `"dev": "run-p routify nollup"`

**version**
`"@roxi/routify": "^2.5.1-next-major"`
`"svelte": "^3.29.4"`

**screenshot**
-

**Comment by jakobrosenberg** [comment]
Thanks @DhyeyMoliya. This has been fixed in `2.8.1`.

https://github.com/roxiness/routify/releases/tag/v2.8.1
