### ISSUE TITLE
Using Cyrillic in paths breaks routing.

### ISSUE THREAD

**Issue by quentincaffeino** [roxiness/routify#305]
**bug description**
I'm creating an app where I need to use Cyrillic words in my routes, but since urls are limited to a certain characters browsers encode Cyrillic to percent encoded characters which for word `рецепт` produces `%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82`. The routing produced by routify is correct and has initial word but since browser provides it with this percent encoded gibberish it is unable to find matching route. After a little investigation I found out that it is enough to add one line:
```diff
// urlToRoute.js

  export function urlToRoute(url) {
+     url = decodeURIComponent(url)
      url = config.urlTransform.remove(url)
```

Tho I'm not sure that this won't break something else.

Hope this issue could be resolved asap. Awesome package, thanks for all your work and happy holidays!

**Comment by ghostdevv** [comment]
I don't see why this would break anything as it shouldn't effect allowed chars in the url, definitely could use some testing though

**Comment by quentincaffeino** [comment]
Sorry for my english. So when you enter something using Cyrillic characters in your browser, it encodes it and js code gets encoded version, which isn't equal to the original word.
`'%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82' == 'рецепт' // false`, unless
`decodeURIComponent('%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82') == 'рецепт' // true`
This is why routing doesn't work.

**Comment by ghostdevv** [comment]
Yea I get what you mean

**Comment by jakobrosenberg** [comment]
@quentincaffeino I don't think this will break anything, but I'm not sure. I have however discovered some potential bugs which need to be ironed out first.

In the meantime you can try this:

```html
<!-- src/App.svelte -->
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../.routify/routes";

  const config = {
    urlTransform: {
      remove: url => decodeURIComponent(url),
    },
  };
</script>

<Router {routes} {config} />
```

**Comment by jakobrosenberg** [comment]
I think I got the bug fixed, but I'm still uneasy about transforming the url. Any thoughts on potential pros/cons?

**Comment by quentincaffeino** [comment]
Sorry can't test proposed solution right now, but if it works I'm fine using it cause i understand that this may decrease router speed. Atleast now it is documented in the issues so if somebody comes across the same problem there is a solution.
