### ISSUE TITLE
$goto not work when component not change

### ISSUE THREAD

**Issue by Arstman** [roxiness/routify#306]
hi, 

sorry i am newbie here, 

i just got a problem with $goto help,

say I have a route  with component `/p/[page].svelte`, when i was in page 1 like `/p/1`, i want to change to page 2 `/p/2`,

i have a button to click and the bind function like this:

```javascript
 function changePage(e) {
        $goto('/p/'+e.detail.page)
    }
```

i see the url changes in the browsers bar, but everyting in this page stay same, nothing  else changes.

i guess this because the svelte itself, which keep less rerende as possible,  anything i can do with this?

pleas help, thanks

**Comment by jakobrosenberg** [comment]
You can use `<!-- routify-options param-is-page -->`
 https://routify.dev/docs/metadata

I would also change the code to `$goto('/p/:page', {page: e.detail.page})`, but that's pure OCD.

**Comment by ghostdevv** [comment]
@Arstman ^

**Comment by Arstman** [comment]
@jakobrosenberg  @ghostdevv  

thanks you guys, it works.

:)

**Comment by ghostdevv** [comment]
No problem
