### ISSUE TITLE
Logout issue in Routify Auth example

### ISSUE THREAD

**Issue by catchspider2002** [roxiness/routify#309]
The routify auth example (https://auth-example.routify.dev/) does not return back to the page https://auth-example.routify.dev/admin#signout on signing out. It remains in the page https://routify.eu.auth0.com/v2/logout?client_id=xxxxxxxxxx&auth0Client=xxxxxxxxxx.

**Comment by jakobrosenberg** [comment]
Thanks @catchspider2002 . Nice catch.

Interested in doing a PR?

**Comment by ghostdevv** [comment]
Will be fixed with new routify templates coming soon and should be made [here](https://github.com/roxiness/routify-starter)
