### ISSUE TITLE
Mix of anchors and routes

### ISSUE THREAD

**Issue by jameswoodley** [roxiness/routify#311]
I currently have a main navigation that includes both anchors and new pages, something like

Features -> #features
Contact -> #contact
My Account -> /account

Currently I'm having to put a target="_self" on the anchors to get them to scroll down, but of course when on the /account route I lose the ability to go back. I therefore made them /#features for example, but that then reloads and loses the routify fun.

Is this just something I have to put up with, or is there a way I could use a named route alongside the anchor, something like

Features -> home#features
Contact -> home#contact
My Account -> account

Would be perfect here?

**Comment by jakobrosenberg** [comment]
Hi @jameswoodley 

Wouldn't a plain `<a href="#features">Features</a>` work?

Kinda like what we have here: https://routify.dev/docs/helpers#page

**Comment by jameswoodley** [comment]
Yup if I were on the "home" page which is where the # links are, but once I head to /account then I lose the targets, as they were on the original page.

Live example on https://castily.co if it helps

**Comment by jakobrosenberg** [comment]
What happens if you leave the links as is and remove `target="_self"`? That seems to work for me if I edit the HTML on the page.

**Comment by jameswoodley** [comment]
Yup that works fine thanks. So when I was using the named route "home", so my link was "home#features" it wasn't working.. but just using "/#features" does the trick.

Cheers!

**Comment by jameswoodley** [comment]
Related side note, is there something in routify I can do to make it scroll down nicely to the anchor, or is that outside the routify scope?

**Comment by jakobrosenberg** [comment]
@jameswoodley try this
```css
html {
  scroll-behavior: smooth;
}
```

I'm reopening this cause named routes with anchors does sound like something we should support.

**Comment by jameswoodley** [comment]
Actually something weird is happening.. if you click on My Account, then Contact, it will shoot to the homepage but not to the contact anchor. Platform & Features do seem to work, and even more strangely, if you click Features before Contact, then Contact works

**Comment by jakobrosenberg** [comment]
That is strange. It wasn't doing that when I removed the `target="_self"` manually.

**Comment by jameswoodley** [comment]
Actually none of them are working when coming back from the My Account page, I got confused I think as Platform is high enough to be in view, so it's just shooting back to the page and not firing the anchor

**Comment by jakobrosenberg** [comment]
Any chance I can see the repo?

**Comment by jameswoodley** [comment]
Another symptom here, if you load the link with the anchor, it doesn't go. e.g. https://castily.co/#features

**Comment by jameswoodley** [comment]
I've invited you to the Org, it's the Web repo

**Comment by jakobrosenberg** [comment]
I was hoping to spot the cause in the source, but it looks like it all checks out.

Could it be that the scroll to anchor action happens before the anchor has been rendered? 🤔

**Comment by jameswoodley** [comment]
As in the smooth scroll, or the browser is being too efficient?

**Comment by jakobrosenberg** [comment]
Could you try this in your root layout?
```javascript
import { afterPageLoad } from "@roxi/routify"
$afterPageLoad(page => document.getElementById(location.hash)?.scrollIntoView();)
```

**Comment by jakobrosenberg** [comment]
Using `onMount` should also work.

**Comment by jameswoodley** [comment]
In my App.svelte? I'm giving this a go and document.getElementById(location.hash) is returning null. I'll try it in the actual layout page

**Comment by jakobrosenberg** [comment]
In your `src/pages/_layout.svelte`

**Comment by jameswoodley** [comment]
Worked it out, location.hash includes the `#`. So changed your code to `document.getElementById(location.hash.substring(1))` and seems to be working...

Small irritation, it always scrolls to the top before flitting down. Is that expected behaviour? Go from #features to #contact for example

**Comment by jakobrosenberg** [comment]
If you remove the `afterPageLoad` and move the script to `src/pages/index.svelte` I think it should work.

**Comment by jameswoodley** [comment]
Same, jumps to the top then scrolls down

**Comment by jakobrosenberg** [comment]
This happens when you navigate between anchors within the same page?

**Comment by jameswoodley** [comment]
Yeah, on the homepage go to features, then go to contact, it jumps up then scrolls:

https://castily.co

**Comment by ghostdevv** [comment]
Did you end up finding a solution to this? @jameswoodley

**Comment by jameswoodley** [comment]
Unfortunately not, it still jumps to the top 1st

**Comment by ghostdevv** [comment]
@jameswoodley Alright, I will see if I can take a look for you tomorrow

**Comment by jameswoodley** [comment]
That would be sensational, thanks!

**Comment by jakobrosenberg** [comment]
@jameswoodley could you try something like this in your root `_layout.svelte`

```html
<div data-routify="scroll-lock">
  <slot />
</div>
```

**Comment by jameswoodley** [comment]
Sweet, that's fixed the scrolling to the top.. Last issue with this is if I browse to https://castily.co/#contact for example, it doesn't scroll the section in to view.

Otherwise this is working great now, thanks for the help

**Comment by ghostdevv** [comment]
I can't seem to reproduce how are you doing it? @jameswoodley

**Comment by jameswoodley** [comment]
If you browse to the link I sent, it should scroll down to the contact form, but instead it stays at the top of the page

**Comment by ghostdevv** [comment]
@jameswoodley Do you have any javascript interfering?

**Comment by ghostdevv** [comment]
I feel like what jake said about it not scrolling because it's not loading the content statically? Maybe try variants of the onMount thing he suggested

**Comment by ghostdevv** [comment]
I tested this on a blank routify app and had the same issue, I solved it by putting the following code in the root `_layout.svelte`
```js
    import { afterPageLoad } from '@roxi/routify';
    $afterPageLoad((page) =>
        document.getElementById(location.hash.slice(1))?.scrollIntoView(),
    );
```

**Comment by jakobrosenberg** [comment]
If this fixes it, I think it's a much better approach than trying to fix it within Routify.

**Comment by ghostdevv** [comment]
This actually seems to be a issue with routify try updating to @latest and it should work

**Comment by jameswoodley** [comment]
Yup, awesome, can confirm I'm happy now. Can close this

**Comment by ghostdevv** [comment]
Amazing
