### ISSUE TITLE
Multiple Await build error

### ISSUE THREAD

**Issue by dustsucker** [roxiness/routify#312]
**bug description**
Multiple awaits with axios.get("ENDPOINT") handled by a svelte #await statement. Dev Runs fine but build throws: 
`/ Exporting 1 of 1 /index(node:18024) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createTextNode' of undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

It does not throw an error when there is only one #await. And the content of the #await statements changes nothing so in this file there are only 2 #awaits, and it fails if you reduce it to one #await it builds.

**package.json**
{
  "name": "svelte-app",
  "version": "1.0.0",
  "@comments scripts": {
    "dev": "develop with blazing fast rebuilds",
    "dev:features": "develop with features like SSR and serviceworker enabled",
    "build": "run build scripts below",
    "build:app": "build single page application (SPA)",
    "build:static": "Generate static pages",
    "serve": "serve content in 'dist' folder",
    "rollup": "run the rollup bundler",
    "nollup": "run the nollup no-bundler",
    "routify": "run routify"
  },
  "scripts": {
    "dev": "run-p routify nollup",
    "dev:ssr": "run-p routify rollup",
    "build": "run-s build:*",
    "build:app": "routify -b && rollup -c",
    "build:static": "spank",
    "serve": "spassr --ssr",
    "rollup": "rollup -cw",
    "nollup": "nollup -c",
    "routify": "routify"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^15.0.0",
    "@rollup/plugin-node-resolve": "^10.0.0",
    "@roxi/routify": "^2.8.5",
    "autoprefixer": "^10.2.0",
    "cross-env": "^7.0.2",
    "cssnano": "^4.1.10",
    "fs-extra": "^9.0.1",
    "nollup": "^0.13.13",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.2.2",
    "postcss-import": "^13.0.0",
    "rollup": "^2.33.1",
    "rollup-plugin-hot": "^0.1.1",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^6.1.0",
    "rollup-plugin-svelte-hot": "^0.11.1",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-workbox": "^5.2.1",
    "spank": "^1.4.0",
    "spassr": "^2.1.6",
    "svelte": "^3.29.4",
    "svelte-preprocess": "^4.6.1",
    "tailwindcss": "^2.0.2",
    "tossr": "^1.3.1"
  },
  "routify": {
    "extensions": "svelte,html,svx,md"
  },
  "spassr": {
    "assetsDir": [
      "dist",
      "assets"
    ],
    "script": "dist/build/main.js",
    "ssrOptions": {
      "inlineDynamicImports": true
    }
  },
  "spank": {
    "blacklist": [
      "/example/modal/basic/4"
    ]
  },
  "dependencies": {
    "@beyonk/svelte-carousel": "^2.8.0",
    "axios": "^0.21.1",
    "svelte-i18n": "^3.3.0"
  }
}

**version**
2.8.5

**screenshot**
Nope

**Comment by jakobrosenberg** [comment]
@Skillcrafter0307 you need to call the `$ready` helper after your async code has been resolved.

```javascript
asyncCode().then($ready)
```
or
```javascript
await asyncCode()
$ready()
```

Alternatively you can omit the async code on the server
```javascript
if (window.routify.inBrowser){
  asyncCode()
}

**Comment by dustsucker** [comment]
Okay thanks for the help, but it wasn't it. I fixed with updating all dependencies I don't know what exactly fixed it, but it could be the routify update.
