### ISSUE TITLE
Incomplete details on how to add Routify to an existing project

### ISSUE THREAD

**Issue by MrAmericanMike** [roxiness/routify#313]
So apparently following the guide at https://routify.dev/guide/installation/install-to-existing-project doesn't really cover all the aspects of adding Routify to an existing project. Unless things have changed on the basic sveltejs/template the rollup.config.js file that comes with that template is incompatible with what Routify needs to run correctly.
After completing all the steps and trying to run npm run dev different errors come up like:
`Error: UMD and IIFE output formats are not supported for code-splitting builds.`

After changing format to "esm" errors like:
`Error: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.`

After changing file to for example `dir: "dist/build"`  Voilà!!! It works....

But I wonder, what other steps are missing in the guide (adding a pages folder could be one?) but I guess that's more about reading how Routify works.

Starting with the suggested project as the guide encourage could be an option, but I think it's way better to have guides about how to add the different functionalities that Routify can handle instead of adding all of them as it makes it more complicate for someone starting to know what can be deleted from a project if we don't need X or Y feature.

**Comment by jakobrosenberg** [comment]
@MrAmericanMike I fully agree. We're currently working on a template system that will generate templates based on needs rather than adding all features to the starter.

**Comment by ghostdevv** [comment]
I will see if I can expand on the guide, thanks for the suggestion @MrAmericanMike

**Comment by ghostdevv** [comment]
Done!
