### ISSUE TITLE
Allow Metadata to Be Set From Inside Script Tags 

### ISSUE THREAD

**Issue by alteredorange** [roxiness/routify#315]
**The Problem**
Currently, metadata has to be set with a `<!-- routify:options my-meta-data="Hello world" -->`  outside of the svelte script tags. This makes it harder to see what metadata you've set for the page (because it isn't near the other, normal variables inside the script) and it makes it impossible to set variables to metadata.

**The Solution**
Allow metadata to be set inside the script tags. It looks like this might have been the case, as on the Routify site source code it sets titles like: 
```
   import { meta } from "@roxi/routify"; 
   meta.title` = "My Important Page"
```
Currently, this doesn't seem to work, I have to use the `<!-- routify:options  -->` tag to get anything to show up in metadata.

Importing meta and setting it inside the script tags seems to make much more sense, as that's how everything else works in Routify. Having a completely separate tag implementation for this one feature seems like overkill. 

Hopefully we could at least have the option of using either/or?  Thanks!

**Comment by jakobrosenberg** [comment]
@alteredorange metadata is data that's compiled at build time, not runtime. If we move it to runtime, it will no longer be accessible to Routify or other components without loading the respective component first. In short, it would defeat the purpose.

**Comment by alteredorange** [comment]
@jakobrosenberg makes sense. It just seems like it could still be set in the script tag (i.e. if meta is imported, that get's processed during build time?) Thanks for the help!

**Comment by jakobrosenberg** [comment]
Overlooked this one. We read data from comments when we parse the files. The reason it works is because comments don't interfere with your code and they get removed in production builds.

For Routify 3 we might add it as a feature. We should probably handle this in a discussion rather than an issue.

**Comment by premji012** [comment]
There is a meta named $$bundleId. How do i use it? 

I tried the following things. It didn't work
routify:options $$bundleId=123
routify:options $$bundleId="pages"

It didn't work. I want to have a static predefined bundleId for my use case

**Comment by jakobrosenberg** [comment]
@premji012 it's not possible to set your own bundle id. What's your use case for needing this? Maybe we can come up with a solution.
