### ISSUE TITLE
Local decorator not generating

### ISSUE THREAD

**Issue by legowhales** [roxiness/routify#316]
Hi,

I am having trouble using decorators in Routify 2.8.5.

If I use the BaseTransition as a decorator, everything works perfecty.
If I use a custom decorator imported in my local project, the component does not even generate: 
`<slot decorator={MyDecorator} />` is generating nothing.

I tried this with a brand new Routify template. 

**In pages/example/_reset.svelte**
```javascript
...
import { MyDecorator } from "./MyDecorator.svelte"
```
```svelte
...
<div class="main">
   <slot decorator={MyDecorator}>
      <!-- optional fallback -->
   </slot>
</div>
```

I only put `<slot/>` in ./MyDecorator.svelte to make things simple.

Thank you for your help!

![screen](https://user-images.githubusercontent.com/19142403/104709335-1a31b500-571f-11eb-9bb3-ef8098ea7db7.png)

**Comment by jakobrosenberg** [comment]
Hi @legowhales, are you getting any errors in your console?

**Comment by legowhales** [comment]
Hi, no error at all. Neither in the dev console nor in the browser.

**Comment by ghostdevv** [comment]
Were you able to fix this? @legowhales

**Comment by legowhales** [comment]
@ghostdevv Unfortunately no, I just skipped using decorators for now...

**Comment by ghostdevv** [comment]
I don't think I have used decorators before so this is just a stab in the dark, what if you tried instead of destructuring the import doing
```js
import MyDecorator from "./MyDecorator.svelte"
```

**Comment by jakobrosenberg** [comment]
I can't believe I missed that, but @ghostdevv is right. Svelte components are imported as defaults.

**Comment by legowhales** [comment]
Damn, you are right!! It is so obvious, I can't believe I didn't see it. Everything works perfectly, my bad 😞.
Thank's @ghostdevv and @jakobrosenberg.

**Comment by ghostdevv** [comment]
Np 😄
