### ISSUE TITLE
Form's preventDefault not working correctly

### ISSUE THREAD

**Issue by timoanttila** [roxiness/routify#317]
Created a new project for housing companies and wanted to restrict access so I built a login form for the project. Can't see anything before you are logged in. Used `on:submit|preventDefault={logMe}`, but after `npm run build` it does not prevent default which breaks my project. Everything works fine before build and transfer it to the main product server (I use the `dist` folder there and it should work the same way everywhere).

Is this a problem because I use components instead of pages? I have a similar login form component with vanilla Svelte which works fine after build. Does Routify do something differently?

Component is in `_layout.svelte` and `index.svelte` is not used without a login. Do I have to do all the checks later inside every page or should this work like this?

Checks in `_layout.svelte`:

```
{#if $user.token && $site > 0 && $info.home}
	<slot />
{:else}
	<Login />
{/if}
```

```
⠼ Exporting 1 of 1 /index[tossr] /index Waited for the event "app-loaded", but timed out after 5000 ms.
✔ Exported 1 pages (0 ignored) from total 1 pages in 5131 ms
```

Tried `build`, `build:static` and change from `{logMe}` to `{() => logMe()}`.

My login.svelte (component):

```
<script>
	import { api, info, site, user } from "./store";
	let username;
	let password;
	let data = {};
	async function logMe() {
		const res = await fetch($api, {
			method: "POST",
			body: JSON.stringify({
				req: "login",
				page: 1,
				name: username,
				pass: password,
			}),
			cors: true,
		});
		if (res.ok === true && parseInt(res.status) == 200) {
			data = await res.json();
			user.set(data.user);
			let temp = { ...$info, ...data.site };
			info.set(temp);
			site.set(data.site.home.id);
		}
	}
</script>

<form on:submit|preventDefault={logMe}>
	<div class="grid">
		<label class="block">
			<span class="block">Käyttäjätunnus</span>
			<input
				id="user"
				type="text"
				name="username"
				bind:value={username}
			/>
		</label>
		<label class="block">
			<span class="block">Salasana</span>
			<input
				id="pass"
				type="password"
				name="password"
				bind:value={password}
			/>
		</label>
	</div>
	<div id="action">
		<button class="btn" type="submit">Kirjaudu</button>
	</div>
</form>
```
My package.json:

```
{
  "name": "something",
  "version": "1.0.0",
  "@comments scripts": {
    "dev": "Something",
    "dev:features": "develop with features like SSR and serviceworker enabled",
    "build": "run build scripts below",
    "build:app": "build single page application (SPA)",
    "build:static": "Generate static pages",
    "serve": "serve content in 'dist' folder",
    "rollup": "run the rollup bundler",
    "nollup": "run the nollup no-bundler",
    "routify": "run routify"
  },
  "scripts": {
    "dev": "run-p routify nollup",
    "dev:ssr": "run-p routify rollup",
    "build": "run-s build:*",
    "build:app": "routify -b && rollup -c",
    "build:static": "spank",
    "serve": "spassr --ssr",
    "rollup": "rollup -cw",
    "nollup": "nollup -c",
    "routify": "routify"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.1",
    "@roxi/routify": "^2.8.5",
    "cross-env": "^7.0.3",
    "fs-extra": "^9.0.1",
    "nollup": "^0.14.4",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.2.4",
    "postcss-import": "^14.0.0",
    "rollup": "^2.36.1",
    "rollup-plugin-hot": "^0.1.1",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-svelte-hot": "^0.13.0",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-workbox": "^6.1.0",
    "spank": "^1.5.0",
    "spassr": "^2.1.6",
    "svelte": "^3.31.2",
    "svelte-preprocess": "^4.6.1",
    "tossr": "^1.3.1"
  },
  "routify": {
    "extensions": "svelte,html,svx,md"
  },
  "spassr": {
    "assetsDir": [
      "dist",
      "assets"
    ],
    "script": "dist/build/main.js",
    "ssrOptions": {
      "inlineDynamicImports": true
    }
  },
  "spank": {
    "blacklist": [
      "/example/modal/basic/4"
    ]
  }
}
```

**Comment by jakobrosenberg** [comment]
For sake of context: Routify generates a `routes.js` file by scanning your file structure and then uses this file to match the URL to a component. Routify doesn't modify your files or Svelte's behavior. Therefore your `preventDefault` should be unaffected by Routify.

In your case I'm guessing Spank/tossr times out because the page never renders. Routify is waiting for the page component to be loaded in your  `<slot />` before it emits `appLoaded` to tossr, but this never happens and thus the timeout.

The easiest fix is to add
```javascript
import { ready } from '@roxi/routify'
$ready()
```
to your `_layout.svelte`

The `$ready` helper is mainly intended to be used to delay rendering when waiting for async code, but should also be applicable to your situation.

**Comment by timoanttila** [comment]
> Routify is waiting for the page component to be loaded in your `<slot />` before it emits `appLoaded` to tossr, but this never happens and thus the timeout.

Thank you for the clarification. The best way in my case would be to make a login page where the visitor is redirected if not logged in. Then the whole app goes through even without login.

Thank you.

**Comment by jakobrosenberg** [comment]
That will also work. Your original approach is the one I prefer. 😅

I previously suggested that you add `$ready()` in your `_layout.svelte`, but it would actually make much more sense to call it in `Login.svelte`. This way you won't get premature page renders in `tossr`.
