### ISSUE TITLE
`Error: Route could not be found for ...` even though `_fallback.svelte` is present.

### ISSUE THREAD

**Issue by jamalmoir** [roxiness/routify#318]
**bug description**
I've just updated from `2.7.3` to `2.9.0` and now I'm getting this;

```
    Uncaught (in promise) Error: Route could not be found for "parent/12345/children/".
    at urlToRoute (urlToRoute.js:24)
    at runHooksBeforeUrlChange (navigator.js:109)
    at History.history.<computed> [as pushState] (navigator.js:52)
    at goto (helpers.js:313)
    at HTMLDivElement.click_handler (Item.svelte:39)
```
 
This where a `_fallback.svelte` should be loading, and in `2.7.3` it is.

My folder structure is `pages/parent/[id]/_fallback.svelte`
The URL giving the error is `/parent/12345/children/1234/children`

I would expect for it to load `_fallback.svelte` and then store the rest of the path in `$leftover`.

The earliest version that I experience this problem is the jump from `2.7.3` to `2.8.0`: 
https://github.com/roxiness/routify/compare/v2.7.6...v2.8.0

I downgraded back to `2.7.3` and it works as normal. I've checked the changelog and can't see anything that looks like it's related, so I assume this is not a deliberate change.

It seems there are some changes to `runtime/helps.js::resolvePath` in `2.8.0`, so I _suspect_ it has something to do with that.

**version**
Latest correctly working version: 2.7.3
Earliest broken version: 2.8.0

**Comment by jakobrosenberg** [comment]
Thanks @jamalmoir 

I assume this is the culprit
https://github.com/roxiness/routify/commit/3a695160e70ee2731c751b6349bed5c9130ac3f9

Since 2.8.0 Routify's `beforeUrlChange` provides info on the incoming route, which in your case breaks as you navigate to a non-existing route.

So the question is, should `_fallback.svelte` be considered a route or should `beforeUrlChange` return null for non-resolved URLs.

**Comment by jakobrosenberg** [comment]
I'm unable to replicate the issue as `_fallback.svelte` is being resolved correctly in my test. Do you have a repo I can see?

**Comment by jamalmoir** [comment]
@jakobrosenberg hmmm, I'll try to get something set up this week 👍

**Comment by ghostdevv** [comment]
Is there any updates on this? Is it solved? @jamalmoir

**Comment by jamalmoir** [comment]
Sorry I've been incredibly busy launching an app (that uses routify).

I haven't had time to set up an example repo yet. I'm currently making do with `2.7.3`.

I'll try to give a more useful response than this soon 😅

**Comment by ghostdevv** [comment]
Try updating to the latest version, I haven't had the issue you are having but updating may fix it

**Comment by reddec** [comment]
I guess I have similar problem - can't use goto:

```
caught (in promise) Error: Route could not be found for "blank".
    at urlToRoute (node_modules/@roxi/routify/runtime/utils/urlToRoute.js:23)
    at runHooksBeforeUrlChange (node_modules/@roxi/routify/runtime/navigator.js:124)
    at History.history.<computed> [as pushState] (node_modules/@roxi/routify/runtime/navigator.js:63)
```

```javascript
function openJournal() {
        $goto('/journal/:journal', {journal: journal.id})
}
```

![image](https://user-images.githubusercontent.com/6597086/107598899-fd26ce00-6c59-11eb-97e7-42b5d8ba8c80.png)

`"@roxi/routify": "^2.12.0",`

Tried without `goto` - just by `history.push(...)` - same problem

**Comment by jakobrosenberg** [comment]
@reddec are you trying to navigate to `blank`?

Your function directs to `journal`, but your error refers to `blank`.

**Comment by reddec** [comment]
@jakobrosenberg 
That's a problem (I also confused why `blank`): 

* openJournal - it's just a function for on:click (doesn't really matter): should navigate to journal (see screenshot of layout)
* same problem with `$redirect`
* same problem if doing manually `history.push` any URL

Even tried without function - just `$redirect` on load: same problem

**Comment by jakobrosenberg** [comment]
@reddec would you able to provide a minimal reproducible?

**Comment by reddec** [comment]
@jakobrosenberg yes, it reproducible

[mre.tar.gz](https://github.com/roxiness/routify/files/5963935/mre.tar.gz)

**Comment by reddec** [comment]
Thanks @jakobrosenberg ! 2.12.1 fixed it

**Comment by jakobrosenberg** [comment]
Great, @reddec.

@jamalmoir does this patch fix the issue for you?
