### ISSUE TITLE
Multiple page deploy

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#32]
If I link to a (sub)route on a deployed site, 

https://bestof2019.johanronsse.be/series

I will get a 404.

However, if I go from https://bestof2019.johanronsse.be/ to /series, it works.

Does this have to do with `sirv`?

Should I somehow redirect every request to index.html? Any suggestions on how to this? This might not have much to do with Routify but maybe how SPA's should work in general.

Feel free to close if you feel this is not relevant to Routify.

**Comment by Wolfr** [comment]
Sorry, this is just me being a newbie to SPAs.

Solution is to set up Apache to redirect to index.html:

````
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
````

Has nothing do with Routify.

**Comment by jakobrosenberg** [comment]
I'm gonna borrow your code and add it as an example for Apache.
