### ISSUE TITLE
Impossible to disable code splitting build

### ISSUE THREAD

**Issue by rsheasby** [roxiness/routify#320]
**Bug description**
Prior to 2.10.1, the default value for the code splitting option was false, thereby the -D option could be used to enable it. However, after 2.10.1, the default value was changed to true, but there is absolutely no way to set it back to false. `-D false` does nothing, as it was specified as an option without a parameter in the commander setup.

Is this an intentional breaking change? Semver would indicate that 2.8 -> 2.10 should not be breaking, but unfortunately it is. If it is intentional, the `-D` option should probably be removed or marked as deprecated since it no longer does anything. If it is not intentional, the option should either accept a parameter to allow setting it to false, or another "--no-dynamic-imports" or "--static-imports" should be added to disable it.

Although changing to a code splitting build in rollup is possible, it is not ideal for all applications.

**version**
Routify 2.10.1

**Comment by rsheasby** [comment]
I've submitted a basic PR to add the `--no-dynamic-imports`option, and I've confirmed that it does now work correctly, and does not interfere with the default value in any way.

**Comment by ghostdevv** [comment]
I am not sure the reason why the cli didn't get a option to reflect the defaults, it seems to be a six month old commit unless I'm reading it wrong: f0a8f5698a627483982269c7ecccb8fe1c8db9e2

You should be able to make a routify config file and bypass the lack of cli option till this is resolved!

**Comment by jakobrosenberg** [comment]
Thanks for the PR @rsheasby, can I ask if you're using a framework/bundler or a specific package which requires bundling? If so, I could possibly add `dynamicImports = false` to the detected defaults.

Example here for Meteor: https://github.com/roxiness/routify/blob/master/configs/meteor.config.js

**Comment by rsheasby** [comment]
No framework other than just regular Svelte with rollup.

**Comment by rsheasby** [comment]
Oh by the way, I just checked and I do in fact have a routify.config.js with the following content:
```
module.exports = {
    routifyDir: '.routify',
    dynamicImports: false
}
```
And yet it's still outputting a code split build, so it would seem the config file is also being ignored for this parameter.

EDIT: Note that the routifyDir is being properly set, it's only the dynamicImports that fails to work correctly.

EDIT 2: Note too that I've tested this again with rollup 2.10.3 and it still does not allow dynamicImports. Adding the newly changed `-D` flag is now the only way to disable it.

**Comment by jakobrosenberg** [comment]
@rsheasby I'll investigate this and have a fix out asap. (Routify 2.10.0 had a bug that prevented configs from being read)

**Comment by jakobrosenberg** [comment]
Tracked this down to `commanderjs` which sets  `dynamicImports` to true if the flag `--no-dynamic-imports`  is not used. Even if the default is set to false. Currently having some issues with `pnpm`, but will push a fix once sorted.

**Comment by jakobrosenberg** [comment]
This was hopefully fixed earlier today, but forgot to update this issue.

**Comment by rsheasby** [comment]
Awesome, yeah I've confirmed that the config file seems to once again be working in 2.10.5, and it's also possible to disable it using the `-D` flag.
