### ISSUE TITLE
Route could not be found for "http://localhost:5000/example/app"

### ISSUE THREAD

**Issue by amuller-maths** [roxiness/routify#323]
I installed the started template via `npx @roxi/routify init`

When in developpement mode orwhen serving a build, when clicking the submit button inside the login page accessed via the App link in the navigation bar, I get the following error :

    Uncaught (in promise) Error: Route could not be found for "http://localhost:5000/example/app".
        at urlToRoute (node_modules/@roxi/routify/runtime/utils/urlToRoute.js:26)
        at runHooksBeforeUrlChange (node_modules/@roxi/routify/runtime/navigator.js:114)
        at History.history.<computed> [as pushState] (node_modules/@roxi/routify/runtime/navigator.js:57)
        at goto (node_modules/@roxi/routify/runtime/helpers.js:334)
        at HTMLButtonElement.login (eval at <anonymous> (index6.js:16), <anonymous>:218:3)

and I stay on the login page.

**Comment by jakobrosenberg** [comment]
@amuller-maths could you try update routify to @latest and confirm that the issue persists?

**Comment by amuller-maths** [comment]
I can confirm that after updating the issue still persists.

There are also these warning messages : 

    <Pages> received an unexpected slot "default".
    console.<computed> @ index.js:80

    <Pages> was created with unknown prop 'scoped'
    console.<computed> @ index.js:80

    <Pages> was created with unknown prop 'scopedSync'
    console.<computed> @ index.js:80

**Comment by jakobrosenberg** [comment]
I'm unable to reproduce the issue on `v2.10.7`. What version are you using?

**Comment by amuller-maths** [comment]
I was using v2.10.5. 

There is no more issue for me since v.2.10.7. Thanks !
