### ISSUE TITLE
Help: VSCode setup to debug

### ISSUE THREAD

**Issue by dirajkumar** [roxiness/routify#324]
I'm new to routify. I couldn't find any resources which would help me set up my vscode to do live debugging. Any help would be appreciated.

**Comment by jakobrosenberg** [comment]
Routify doesn't require any specific tooling or steps for debugging, so you can debug it like any other node/js application.

In your terminal tab, create a new shell and select `Create JavaScript Debug Terminal`.

From there you can run `npm run dev` etc. with live debugging.

![image](https://user-images.githubusercontent.com/4153004/105624622-8f8a3d80-5e23-11eb-8a7e-c57a59146294.png)

![image](https://user-images.githubusercontent.com/4153004/105624569-0115bc00-5e23-11eb-912e-80f54f140d97.png)

**Comment by jakobrosenberg** [comment]
I'm closing this as it's not an issue with Routify. 

Feel free to continue the conversation in [discussions](https://github.com/roxiness/routify/discussions) or [discord](https://discord.gg/ntKJD5B). 🙂
