### ISSUE TITLE
Leftover console.log

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#33]
<img width="469" alt="Screenshot 2019-12-26 at 18 19 39" src="https://user-images.githubusercontent.com/12690/71484372-5b9dac80-280c-11ea-9062-7f44947fd1c2.png">

navigator.js has a leftover console.log.

**Comment by jakobrosenberg** [comment]
What version are you on? That log should be gone, but I could be mistaken.

**Comment by Wolfr** [comment]
"@sveltech/routify": "1.0.1-7",

**Comment by Wolfr** [comment]
I updated to -9 and it's gone.
