### ISSUE TITLE
Anchors with "_self" target attr aren't ignored during build

### ISSUE THREAD

**Issue by Robak08** [roxiness/routify#331]
As title states, I cannot get build proccess to work with anchors looking like 

```
<a target="_self" href="tel:123456789">
```

seems like adding target attr doesn't tag anchor as ignored, example error at exporting stage of build:

```
UnhandledPromiseRejectionWarning: Error: Path contains invalid characters: dist/index/tel:123456789
```

running on versions:
```
"@roxi/routify": "2.12.4",
 "svelte": "3.32.1",
```

**Comment by jakobrosenberg** [comment]
@Robak08 what version of `spank` are you using? This sounds like an old `spank` bug.

**Comment by Robak08** [comment]
@jakobrosenberg I'm using ``` "spank": "1.4.0"```. Update to latest resolved errors. Thank You for pointing that out!

**Comment by keithkelly31** [comment]
I am running into the same issue with a download link that I have.  It links to a pdf.  I have the target attribute, but it is still being picked up.

`<a
        download
        class="btn btn-primary"
        href="/flyer.pdf"
        target="_self"
      >
        Download Flyer
      </a>`

The error I receive is:
`[tossr] Unhandled promise rejection:
[tossr] [Error: ENOENT: no such file or directory, open 'C:\Users\user\Documents\GitHub\svelte\dist\flyer.pdf\index.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\user\\Documents\\GitHub\\svelte\\dist\\flyer.pdf\\index.html'
}`

svelte: 3.35.0
spank: 1.5.3
tossr: 1.4.2

**Comment by Robak08** [comment]
@keithkelly31 Not entirely sure if it will help, but You can try to use absolute path in href - and place pdf to assets dir or any other external dir.

**Comment by jakobrosenberg** [comment]
`_self` shouldn't have any effect AFAIK.

Have you tried the blacklist option?

I'm contemplating if I should add better error handling / resilience or an `anchorFilter` callback that lets you determine whether an anchor element should be processed.

**Comment by keithkelly31** [comment]
I couldn't find any documentation on a blacklist option.  How does that work?

The only thing I could find was using the target attribute to have Routify ignore the anchor.

**Comment by jakobrosenberg** [comment]
The blacklist feature is described in the `spank` repo.

https://github.com/roxiness/spank
