### ISSUE TITLE
The right way to implement i18n

### ISSUE THREAD

**Issue by Paradoxu** [roxiness/routify#332]
By following [this](https://phrase.com/blog/posts/how-to-localize-a-svelte-app-with-svelte-i18n/) I was able to implement i18n with a normal svelte App, but the same doesn't work when using routify, this what I tried:

```
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../.routify/routes";
  import { setupI18n, isLocaleLoaded, userLanguage } from './services/i18n';

  $: if (!$isLocaleLoaded) {
    setupI18n({ withLocale: userLanguage() });
  }
</script>

{#if $isLocaleLoaded}
  <Router {routes}  />
{/if}

<Router {routes} {config}  />
```

But I receive an error during the build with spank:

` UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported`

Which I assume it's similar to this same [issue](https://github.com/roxiness/spank/issues/9), I've read the [example](https://routify.dev/examples/i18n-basepaths#use-our-new-i18nurlsjs) in the Routify i18n section and as I understood I would have to split my pages folder in sub folders based on the languages I want to support, is that right? Example:

- pages
   - en
      - index.svelte
  - pt
     - index.svelte
  - it
     - index.svelte 

This seems a bit uggly since I would have to rewrite same components across different folders. How should I structure and implement i18n and use the the translations from the json files?

**Comment by jakobrosenberg** [comment]
Hi @Paradoxu, you don't need a module for each language.

Here's an example from our upcoming generated templates:

<details>
<summary>components/Lang.svelte</summary>



It may seem a little verbose as it also includes a language dropdown. The exported `urlTransform` should be imported in `App.svelte`

```svelte
<script context="module">
  import { writable, get } from "svelte/store";
  import { page } from "@roxi/routify";

  const languages = {
    en: { short: "en", long: "english", default: true },
    fr: { short: "fr", long: "french" },
    de: { short: "de", long: "german" },
  };

  // let's use a store for reactivity
  const language = writable(languages["en"]);

  const urlTransform = {
    apply: (url) => {
      /**
       * external URL
       * if the selected language is not the default language,
       * we want to use the language as an URL prefix
       */
      const lang = get(language);
      const prefix = !lang.default ? `/${lang.short}` : "";
      return prefix + url;
    },
    remove: (url) => {
      /**
       * internal URL
       * if the first url fragment matches a language,
       * we're gonna strip the fragment
       */
      const [, urlPrefix, ...rest] = url.split("/");
      if (languages[urlPrefix]) {
        language.set(languages[urlPrefix]);
        return [, ...rest].join("/");
      } else return url;
    },
  };

  export { languages, language, urlTransform };
</script>

<script>
  import { goto, url } from "@roxi/routify";
  const handleChange = () => {
    $goto($page.path);
  };
</script>

<select bind:value={$language} on:change={handleChange}>
  {#each Object.values(languages) as lang}
    <option value={lang}>{lang.long}</option>
  {/each}
</select>
```
</details>


<details>
<summary>pages/i18n-example.svelte</summary>

```svelte
<script>
  import { language } from "../components/Lang.svelte";
  $: lang = $language.short;
  const dict = {
    en: "Welcome",
    de: "Herzlich willkommen",
    fr: "Bienvenue",
  };
</script>

{#if lang === "en"}
  <h1>Internationalization</h1>
  <p>
    In this example we're using <code>urlTransform</code> to store and fetch the current language ID in/from the url. We
    could also do this with a dynamic folder in the root, eg. <code>src/pages/[language]</code>.
  </p>
  <p>
    How localized data should be stored and resolved is entirely up to you. For simplicity, we've kept it all in one
    file.
  </p>
{:else if lang === "de"}
  <h1>Internationalisierung</h1>
  <p>
    In diesem Beispiel verwenden wir <code>urlTransform</code>, um die aktuelle Sprach-ID in / aus der URL zu speichern
    und abzurufen. Wir könnten dies auch mit einem dynamischen Ordner im Stammverzeichnis tun, z.
    <code>src/pages/[language]</code>.
  </p>
  <p>
    Wie lokalisierte Daten gespeichert und aufgelöst werden sollen, liegt ganz bei Ihnen. Der Einfachheit halber haben
    wir alles in einer Datei gespeichert.
  </p>
{:else if lang === "fr"}
  <h1>Internationalisation</h1>
  <p>
    Dans cet exemple, nous utilisons <code>urlTransform</code> pour stocker et récupérer l'ID de langue actuel dans / depuis l'url.
    Nous pourrions également le faire avec un dossier dynamique à la racine, par exemple. <code>src/pages/[language]</code>.
  </p>
{/if}
```
</details>

Not sure if this solves your problem, but hopefully it's a start. 🙂

**Comment by Paradoxu** [comment]
> Hi @Paradoxu, you don't need a module for each language.
> 
> Here's an example from our upcoming generated templates:
> 
> components/Lang.svelte
> pages/i18n-example.svelte
> Not sure if this solves your problem, but hopefully it's a start. 🙂

I managed to solve by storing the `json` translations as `js` files and instead of using `fetch` to get the translation file based on the language, I import both of them and select which one to use based on the user preferences ... Not pretty, but there are only languages and not many translations, that way I was able to keep my initial structure, thank you!!!

**Comment by ulvidamirli** [comment]
@jakobrosenberg Thank you for the script. But I really didn't get it and can't apply it to my code. I am following [example from Routify website](https://routify.dev/examples/i18n-basepaths). Could you please give a solution based on that code? Any help is very much appreciated. And thank you for this beautiful framework. But I am struggling to understand tutorials.

My problem with more details: https://stackoverflow.com/questions/66306655/adding-and-preserving-i18n-basepath-on-routify
