### ISSUE TITLE
Svelte Stores causes rendering order mishaps

### ISSUE THREAD

**Issue by V-ed** [roxiness/routify#333]
## Bug description

Trying to have an "all routes needs a login, except few whitelisted one, such as an about page" type of application

Adding this to the layout :

```svelte
<script>
	[...]
	const whitelistedRoutes = ["/about"];
	
	$: isWhitelisted = whitelistedRoutes.some((route) => $isActive(route));
</script>

{#if isWhitelisted}
	<slot />
{:else}
	<h1>DO THE LOGIN</h1>
{/if}
```

works pretty well, but as soon as you add a store to any element referenced in this layout, going from a non-whitelisted page to a whitelisted page *might* flash the content of the non-whitelisted page very briefly (I'm talking about ~20 milliseconds here)

## Environment

I created a new project using the default `routify-starter` template, added a basically empty about page, and this code to the `src/pages/_layout.svelte` file :

```svelte
<!-- routify:options preload="proximity" -->
<script>
	import { isActive } from "@roxi/routify";
	import { test } from "../store";

	const whitelistedRoutes = ["/about"];

	$: isWhitelisted = whitelistedRoutes.some((route) => $isActive(route));
</script>

<nav>
	<a href="/">Home</a>
	<a href="/about">about</a>
</nav>

{#if isWhitelisted}
	<slot />
{:else}
	<h1>DO THE LOGIN</h1>
{/if}

{#if $test}
	<span>My store is active</span>
{/if}

```

with a basic store at `src/store.js` :

```js
import { writable } from "svelte/store";

export const test = writable(false);
```

## Live example

https://cranky-jepsen-7974d1.netlify.app/

Simply go back and forth between the `home` and `about` links, you should see the text / image of the `home` page appear briefly when going from the home page to the about page, despite the home page being "protected" by a "login"

This does not happen 100% of the time, so you might need to try to go back and forth more than once.

If the code in the above example :
```
import { test } from "../store";

[...]
{#if $test}
	<span>My store is active</span>
{/if}
```

wouldn't be there, I could not get a single time the content of the home page to show.

**Comment by jakobrosenberg** [comment]
Does this also happen if you check against `$layout.path` or `$page.path` instead of `$isActive`?

**Comment by V-ed** [comment]
*[discussion on discord](https://discord.com/channels/683709869626490889/734724447948243017/811960435372064779), I'll report here my findings with the help I'll get*

**Comment by V-ed** [comment]
After many different tests, a solution that works emerged : using decorators.

The basic idea is that the decorator handles the whitelisting aspect (and potentially the login render as well, making it a "Login decorator"), and the main layout would use this decorator.

Here's a basic sample that doesn't seem to have any flashing occuring :

```svelte
<!-- src/pages/_decorator.svelte -->
<script>
	import { ready, node } from "@roxi/routify";
	import { test } from "../store";

	const whitelistedRoutes = ["/about", "/contact", "/login"];

	$: isWhitelisted = whitelistedRoutes.some((route) =>
		$node.path.startsWith(route)
	);

	setTimeout($ready, 0);
</script>

{#if isWhitelisted}
	<slot />
{:else}
	<h1>DO THE LOGIN</h1>
{/if}

{#if $test}
	<span>My store is active</span>
{/if}
```

```svelte
<!-- src/pages/_layout.svelte -->
<!-- routify:options preload="proximity" -->
<script>
	import { isChangingPage } from "@roxi/routify";

	import Nav from "./_components/Nav.svelte";
	import decorator from "./_decorator.svelte";

	$: console.log("Is changing page", $isChangingPage);
</script>

<Nav />

<slot {decorator} />
```

The main fix here was to use `$node.path.startsWith(route)`, which seems to not have the race condition, but is only allowed in decorators to get the current node.

Note a particularity here : the decorator uses a `setTimeout($ready, 0);`, because this is a way to allow the whitelisted pages to be considered as ready when rendered. Using a reactive statement (eg. : `$: if (!isWhitelisted) $ready();`) would not fix the issue that whitelisted routes are never considered "fully rendered". If the `setTimeout($ready, 0);` line is commented out, you will see that whitelisted pages never log `Is changing page false` to the console, while non-whitelisted pages do.

**Comment by jakobrosenberg** [comment]
Happy this got solved. I'm closing the issue for now.

**Comment by V-ed** [comment]
Thanks a lot for the help @jakobrosenberg , it was really appreciated! I was wondering though, any plans on trying to tackle the `setTimeout` requirement for the page to be considered ready? This seems like a work around...

**Comment by jakobrosenberg** [comment]
I noticed you're calling `$ready()` unconditionally while `isWhitelisted` is set reactively. This means `$ready()` will always be called before `isWhitelisted`.

Could you try this?
```javascript
$: if (!isWhitelisted) $ready()
```

**Comment by V-ed** [comment]
> I noticed you're calling `$ready()` unconditionally while `isWhitelisted` is set reactively. This means `$ready()` will always be called before `isWhitelisted`.
> 
> Could you try this?
> 
> ```js
> $: if (!isWhitelisted) $ready()
> ```

Yes, that's actually the first thing I tried when you explained the decorators solution earlier, it unfortunately doesn't work :(
