### ISSUE TITLE
Release 2.11.1 broke $params when removing one param and adding another

### ISSUE THREAD

**Issue by KieranP** [roxiness/routify#334]
I just tried upgrading from 2.10.1 to the latest release (2.12.4) but navigation on my app broke. I decreased routify version until my app was working again. I found that 2.11.0 works and 2.11.1 breaks. The releases show only this change: deb2603e00758804041907dbac68259789790b19

In short, I have a paging system that uses before/after cursors. URLs look like this:
* /posts
* /posts?after=NDA
* /posts?before=NDE

I start on `/posts`, I click on next page button, routify `$goto('/posts, { after: 'NDA' })` is called, and the url changes to `/posts?after=NDA`, and routify $params returns `{after: "MjA"}`.

I then click on prev page button, routify `$goto('/posts, { before: 'NDE' })` is called, and the url changes to `/posts?before=NDE`, but the result of routify $params here is causing issues.

Under 2.11.0, I got `{before: "NDE"}` as expected. 

Under 2.11.1, I get `{after: "NDA", before: "NDE"}` , it keeps both params, even though only "before" should be present.

So in 2.11.1, even though the browser URL (window.location.search) is dropping the `after` param, routify $params is not dropping it, so my app can't tell if the user wants posts before NDE or after NDA.

What makes things worse is I then click the navigation header to go to all posts, the browser url changes to `/posts`, but the routify $params is STILL `{after: "NDA", before: "NDE"}`. The only way to reset it is to reload the page.

I hope this makes some sense. In short, 2.11.1 introduced a bug where $params returns stale data.

**Comment by jakobrosenberg** [comment]
Thanks @KieranP. I'll look into this.

**Comment by jakobrosenberg** [comment]
This should be fixed in v2.12.5

**Comment by KieranP** [comment]
@jakobrosenberg Confirmed fixed. Thanks
