### ISSUE TITLE
BasicTransition applying position: fixed to one of the animated elements

### ISSUE THREAD

**Issue by JakubBlaha** [roxiness/routify#335]
**Bug description**
I have noticed this when using the `TabsTransition` with a layout that contains a div with `overflow: hidden`, to make the website content the size of a mobile phone screen. The `TabsTransition` uses the Svelte's `fly` transition, which displaces the element. The incoming element got cut off properly by the `overflow: hidden`, but the element that was disappearing wasn't cut off. I have looked in the dev tools to see what happens during the animation and noticed that the element that is disappearing got a `position: fixed` property applied. This causes my problem. The `overflow: hidden` property is ignored and the element doesn't get cut off correctly.

To better see what we are aiming for and what happens, here is a screenshot of the application. The incoming element at the right gets cut off properly while the other one stays in the screen in it's whole beauty.

![image](https://user-images.githubusercontent.com/28687156/108635239-bb2e3100-747e-11eb-9f66-d5be7b5be8a7.png)

Here is the part of the `_layout.svelte` file responsible for these routes. (We are using Tailwind)

```html
<div class="overflow-hidden">
    <slot decorator={TabTransition} />
</div>
```

As one of the elements is cut off properly, I believe that the other one can be fixed too.

**Version**
```json
"@roxi/routify": "^2.12.4",
```

**Comment by jakobrosenberg** [comment]
Any idea how we should tackle this?

Without the `fixed` position, the incoming component will be animating under the outgoing component.

**Comment by JakubBlaha** [comment]
@jakobrosenberg If I understand correctly, the outgoing component would render under the incoming component on the z axis. Is there a reason why we cannot tweak this using `z-index` instead?

**Comment by jakobrosenberg** [comment]
Sorry, I meant without `fixed` (or `absolute`) it gets rendered vertically under the outgoing component. You can copy `BaseTransition.svelte` and `TabsTransition.svelte` to your own project and modify them to see if you can fix it.

I think the only way to handle this is by using `absolute` instead of `fixed`, but that introduces new, buy fixable problems.

If you're able to solve it, I'll be happy to implement your solution.

**Comment by stokesman** [comment]
Here's an [article about a solution using CSS Grid](https://imfeld.dev/writing/svelte_overlapping_transitions) that may work well.

**Comment by jakobrosenberg** [comment]
@stokesman that's really cool! Gonna have a look at that.

**Comment by jakobrosenberg** [comment]
@JakubBlaha does this fix it?

https://github.com/roxiness/routify/releases/tag/v2.15.2

**Comment by JakubBlaha** [comment]
@jakobrosenberg Yes, that does fix it. Perfect! Thanks,

**Comment by jakobrosenberg** [comment]
Great. Closing this for now. 🙂
