### ISSUE TITLE
The Routify.dev website is buggy

### ISSUE THREAD

**Issue by dp-IED** [roxiness/routify#336]
I'm new to svelte and have just heard about routify, so I was interested about the package but quickly realized that the site was buggy. The different components are moving up and down constantly, I'll try to attach a gif but it's really weird. I'm on Chrome's latest version, at the TOW it's 88.0.4324.182, on Windows 10. 

[Giphy](https://media.giphy.com/media/K1qQxrtERccLIzPk7s/giphy.gif)

**Comment by ghostdevv** [comment]
That's odd, I think it has something to do with the service worker. I wasn't able to reproduce this, can you try clearing cookies and browser cache and let me know if it persists @ColleSerre

**Comment by jakobrosenberg** [comment]
Could you also try the site in an incognito window? I suspect this might be caused by an aggressive ad blocker.

**Comment by dp-IED** [comment]
Yeah I'll try that and get back to you, by the way the issue persists on
MacOS (still with chrome though)

Le mar. 23 févr. 2021 à 08:23, Jakob Rosenberg <notifications@github.com> a
écrit :

**Comment by dp-IED** [comment]
Nope still does it in incognito windows

**Comment by dp-IED** [comment]
The problem seems to be coming from uBlock Origin, I've whitelisted the site and the problem no longer occurs
