### ISSUE TITLE
Prefetch

### ISSUE THREAD

**Issue by mathiasrw** [roxiness/routify#337]
**bug description**
Unknown url is being prefetch on default project setup.

I have a page named price. When I build the project the code tries to load this url

	/pricing__[[routify_url_options]]__%7B"validFor"%3A60%2C"timeout"%3A5000%2C"gracePeriod"%3A1000%2C"prefetch"%3A2%7D

It does this for every url endopint in the project.

I am not sure if its some hot module magic that has gone into the build or a prefetch not configured properly.

**package.json**

		"build": "run-s build:*",
		"build:app": "routify -b && rollup -c",
		"build:static": "spank",

**version**

		"svelte": "^3.29.4",
		"@roxi/routify": "^2.12.4",

**Comment by jakobrosenberg** [comment]
Are you calling prefetch from anywhere in your project? If not, could you test if this happens on `127.0.0.1` just to rule out a stale serviceworker.

**Comment by mathiasrw** [comment]
Ohh - I do prefetch!

```
	import {isActive, url, prefetch} from '@roxi/routify';

...

    <a href={$url(item.url)} use:prefetch>{linkName}</a>
```

----

Its inserted here

https://github.com/roxiness/routify/blob/a8bc49e7fe49fe6e3f7df81a05c66c6fd76e8e1d/runtime/Prefetcher.svelte#L40

and then used in https://github.com/roxiness/routify/blob/3f623763fa60624b6115269bf092a2b2eac8ef91/runtime/utils/index.js#L102-L111
to indicate that it had been prefetched. 

Hmm. wondering if it is because the prefetch should have added a `?` or a `#` after the pathname sending the info as a parameter so the intended url would be `/pricing#__[[routify_url_options]]__%7B"validFor"%3A60%2C"timeout"%3A5000%2C"gracePeriod"%3A1000%2C"prefetch"%3A2%7D`

**Comment by jakobrosenberg** [comment]
I'm very puzzled why it's not working for you and why the hashtag fixes it. The hashtag changes the resolved URL from `/pricing` to `/pricing#` so it shouldn't make any difference.

https://github.com/roxiness/routify/blob/master/runtime/utils/index.js#L103

**Comment by mathiasrw** [comment]
Hi @jakobrosenberg (danish?)

I must admit that I have not gotten into the full flow of the data. It might be that the original idea was to let the `__[[routify_url_options]]__%7B"validFor"%3A60%2C"timeout"%3A5000%2C"gracePeriod"%3A1000%2C"prefetch"%3A2%7D` part of the url be stripped before the actual request to the server was made. 

The fix with the `#` was so that the server would get a valid request to `/pricing`. I was not even aware that you can do hash based navigation. So regarding https://github.com/roxiness/routify/pull/339#issuecomment-786032647 - no hash based navigation. 

Actually, the current core will probably not work when its hashbased navigation. The server is not having invalid requests but it will probably break to have two hashes in the url.

**Comment by mathiasrw** [comment]
I updated https://github.com/roxiness/routify/pull/339 with how to replicate

**Comment by jakobrosenberg** [comment]
Thanks @mathiasrw. Much appreciated. I'll check it out asap.

And yes, I'm Danish. 🥓🥨😅

**Comment by ghostdevv** [comment]
Hey @mathiasrw is this still a issue? If so I don't quite follow how to reproduce, can you please let me know. If it's no longer a issue then please let me know/close the issue.

**Comment by jakobrosenberg** [comment]
This was resolved here IIRC. https://github.com/roxiness/routify/pull/339#issuecomment-789577219

Closing for now. 🙂
