### ISSUE TITLE
goto() not working

### ISSUE THREAD

**Issue by eriknyk** [roxiness/routify#34]
Hi, I'm using version: ^1.0.1-8

and a _layout.svelte like this:
```
<script>
  import { goto } from '@sveltech/routify'
  import { user } from '../store.js'

  if (user === null) {
    $goto('/login')
  }
</script>

{#if user !== null}
  <h2 data-focus>Home yeah!</h2>
{/if}
```
However, I can see that it redirect into url as expected to /login but it does not re-rendering the /login page contents, so the result is a blank page. if I hit F5 is the only way to get /login page rendered

Any thought?

Regards.

**Comment by jakobrosenberg** [comment]
I ran into the same issue with the Routify site. I've temporarily wrapped the goto in a setTimeout.

```html
<script>
    import { goto } from '@sveltech/routify'
    setTimeout(() => {        
        $goto('../docs/introduction')
    });
</script>
```

I'll see if I can find the issue and push a fix.

**Comment by jakobrosenberg** [comment]
This should be fixed in the latest release.

Had to move the eventlisteners out of the Svelte window and into the script block. Otherwise they wouldn't catch initial events.
