### ISSUE TITLE
Error in URL constructor when using {{useHash: true}}

### ISSUE THREAD

**Issue by sandreas** [roxiness/routify#340]
**bug description**
Error `URL constructor: #/player/d87b8f87-2ed1-48a7-b314 is not a valid URL.` when I try to use `$goto` with `config={{useHash: true}}`. I assume there are missing tests for this option.
```
$goto('./player/' + id);
...
<Router config={{useHash: true}} {routes}/>

...
Uncaught (in promise) TypeError: URL constructor: #/player/d87b8f87-2ed1-48a7-b314 is not a valid URL.
    parseUrl index.js:122
    urlToRoute urlToRoute.js:12
    runHooksBeforeUrlChange navigator.js:124
    eventName navigator.js:63
    goto helpers.js:291
    redirectTo index.svelte:46
 ```

**version**
´´´
npm list @roxi/routify svelte
svelte-app@1.0.0 
├── @roxi/routify@2.12.0 
└── svelte@3.32.2 
´´´

**meme**
https://thecodinglove.com/when-someone-forwards-me-a-ticket-and-its-for-a-css-bug
I hope you think its *good* ;-)

**Comment by jakobrosenberg** [comment]
```javascript
const id = 'foo'
$goto('./player/' + id)
```
This will look for a relative file called `player/foo.svelte` or `player/foo/index.svelte`.

If your dynamic page is called `player/[id].svelte` or `player/[id]/index.svelte`, this is probably what you want:
```javascript
$goto('./player/:id', {id})
```

The first parameter in $goto is the file path and the second parameter is a map of parameters.

If you prefer you can also use the native pushstate: `history.pushstate(null, null, '/path/to/player/' + id)`

**Comment by sandreas** [comment]
The suggested solution leads to  the same error...
```
$goto('./player/:id', {id: item.id})
```
Did you check / try to reproduce it? I think error happens before the file lookup. 

```
window.history.pushState(null, null, '/player/' + item.id)
```
is working fine. Thanks for pointing out, but I still think it is an issue, that should be investigated. 

What do you think?

**Comment by jakobrosenberg** [comment]
My bad. 😅

I saw that you used $goto to parse an URL and not a filepath and assumed that was the issue.

Alas I was not able to reproduce your issue. Could you try update to the latest version of Routify?

**Comment by sandreas** [comment]
> My bad.

Never mind. I already did and in version `2.12.8` it seems to be fixed. Thank you very much. Quick help, great project, this star is really earned :-)
