### ISSUE TITLE
Endless number of awaits with 100% CPU usage on first load of Routify app

### ISSUE THREAD

**Issue by mizzao** [roxiness/routify#341]
When I first open my app on a new domain (or in an incognito tab), the browser tab freezes with 100% CPU usage. **If I force close the tab and open it again, everything works as normal**: very strange.

If I pause execution while this is happening, it looks like there is some sort of infinite number of waiting promises, or infinite recursion happening. Here is what the call stack looks like:

![image](https://user-images.githubusercontent.com/2080084/109256779-ba6e0580-77c4-11eb-9a94-99bb46bb5db8.png)

## And here are the relevant functions that are getting called repeatedly. First, `pushstate`:

![image](https://user-images.githubusercontent.com/2080084/109256822-d376b680-77c4-11eb-8bf9-5be2ddc71532.png)

## then `updatePage`:

![image](https://user-images.githubusercontent.com/2080084/109256868-ea1d0d80-77c4-11eb-9a00-b9600e641b5b.png)

## and finally `preload()`: 

![image](https://user-images.githubusercontent.com/2080084/109256900-028d2800-77c5-11eb-961e-4d7487efbbd8.png)

**version**
Routify 2.12.7 with Svelte 3.32.1.

Again, this only happens on the first load, not subsequent ones.

@jakobrosenberg: happy to add this to our next live debugging session 😁

**Comment by mizzao** [comment]
Ah, here's a hint. My `App.svelte` displays a splash screen if the user isn't logged in, aka the first time the app is opened. And it looks like this:

```svelte
{#if $currentUser}
  <Router {routes} />
{:else}
  <Splash />
{/if}
```

If I just delete the `{#if}` and the splash screen, everything works fine. So maybe this is not a bug, if `<Router>` is not intended to be used this way, or perhaps it is a bug if `<Router>` can't be rendered dynamically.

The "fixed" way to do it is to put the `{#if}` inside the default `_layout.svelte` of the router. But maybe there is a way to fail more gracefully here.

**Comment by jakobrosenberg** [comment]
I'm not able to replicate your issue with
```html
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../.routify/routes";
  let show;
</script>

{#if show}
  <Router {routes} />
{:else}
  <button on:click={() => (show = true)}>show</button>
{/if}
```

What happens if you do 
```javascript
$: console.log($currentUser)
```
Does it log only once or twice or is it looping?

**Comment by lamualfa** [comment]
Same issue. But in my case, the error only occurs if i create a new page in `pages` directory and navigate to there without reloading the tab in HMR mode.

**Comment by jakobrosenberg** [comment]
@lamualfa have you tried updating all HMR related dependencies?

**Comment by lamualfa** [comment]
@jakobrosenberg I don't know. I just use the latest commit of the [Routify Starter](https://github.com/roxiness/routify-starter/).

![image](https://user-images.githubusercontent.com/39755201/111156358-38ede400-85c8-11eb-9b2d-1a36a41138f9.png)

<hr>

## How to get that error?

1. Clone the Routify Starter template using `npx degit roxiness/routify-starter routify-starter`
2. Goto the project directory: `cd routify-starter`
3. Prepare module: `pnpm i`
4. Run: `pnpm dev`
5. Add one link using `href` that doesn't exists ini `pages` directory

**Example**

**src/pages/example/_components/RoutifyIntro.svelte**

```svelte
<h1>Routify Starter</h1>

To see an example app, go to 
<a href="/example">/example</a>
<a href="/test">/Test</a> // Add this

<p>To delete the example app, simply delete the ./src/pages/example folder.</p>
```

6. and then open your browser, and goto `http://localhost:5000/`
7. back again to editor
8. Create new file with name `test.svelte` in `src/pages`
9. Add some code to that file
10. Back to your browser without refreshing the tab
11. Click `/test` link
12. You will get this error

**Comment by jakobrosenberg** [comment]
Thanks for the repro @lamualfa . I'm trying to crack this one.

**Comment by jakobrosenberg** [comment]
This should hopefully be fixed now. Thanks for the help on this one @mizzao and @lamualfa.
