### ISSUE TITLE
Allow for native case-insensitive routing

### ISSUE THREAD

**Issue by josesan9** [roxiness/routify#343]
Hi,

**Is your feature request related to a problem? Please describe.**
There is no built-in or documented solution to have routes be case-insensitive

**Describe the solution you'd like**
a way to configure case insensitivity in routify e.g. `<Router {routes} insensitive />`

**Describe alternatives you've considered**
I am currently using the solution provided by issue #93, which was much harder to find than it should have been.
If this solution is the "correct" or "desired" way of implementing case insensitivity, I believe it should be shown as part of the documentation so it is accessible to everyone.

**Comment by jakobrosenberg** [comment]
> If this solution is the "correct" or "desired" way of implementing case insensitivity, I believe it should be shown as part of the documentation so it is accessible to everyone.

Good point. Where would this make the most sense? In the FAQ, examples or...

FAQ seems like the best place since an entire example page for a one-liner seems like overkill.

```javascript
routes.forEach(r => r.regex = new RegExp(r.regex, 'i'))
```

This could also be handled through `urlTransform`
```html
<script>
  import { Router } from '@roxi/routify'
  const config = {
    urlTransform: {
      remove: url => url.toLowerCase()
    }
  }
</script>
<Router {config} />
  ```
  
  Maybe an example page would be better after all.

**Comment by ghostdevv** [comment]
So this has been added to the FAQ, I also made #359 as a feature request for a insensitive option which may get added
