### ISSUE TITLE
Reload component on click but path unchanged

### ISSUE THREAD

**Issue by arctica** [roxiness/routify#344]
Hi, I'm trying to make my page component reload when the user clicks in the navbar on the link to that same page (the /path does not change). It seems that Routify just ignores the navigation event and nothing really happens.

I've tried to force a "reload" via `on:click="{$goto('/example')}"` but that didn't seem to do the trick.

I can work around it by letting the browser fetch the page the normal way via target="_self" but that is ugly because there's a visual impact.

Any ideas how I can reload the page component?

**Comment by jakobrosenberg** [comment]
@arctica this sounds like something we should add.

As a workaround for now you can use `param-is-page` or `query-param-is-page` but that would pollute the URL a little.

**Comment by arctica** [comment]
@jakobrosenberg thank you for your reply and the workaround suggestion but I'd rather let the user refresh the page instead of adding random stuff to the URL. Hopefully a setting/parameter can be added to Routify to accommodate this usecase.

**Comment by jakobrosenberg** [comment]
I'm looking into the options available for implementing this. I'll keep you posted if I crack it.

**Comment by tonprince** [comment]
I am having a similar issue with the following page structure:
```
/Bookings/index.svelte
/Bookings/[bookingId].svelte
/Bookings/Edit.svelte
/Bookings/View.svelte
```

If the user opens the URL '/Bookings/122222' and is logged in as admin, the 'Edit' component is loaded, otherwise the 'View' component is used. The check is within the [bookingId] component, where depending on the logged-in user the correct component is displayed.

I want to offer the possibility that the admin can switch from edit mode to the view mode by calling the url:
/Bookings/[bookingId]?mode=view

When using $goto with the path and mode param nothing happens, the page is not refreshed. The same should happen when the admin opens the booking in the view mode, he should be able to switch to edit mode.  

Here is the content of the switch logic:
```
<script>
  import { params } from "@roxi/routify";
  import { userInfo, initializing, isAdmin } from "./../../FirebaseAuth.js";
  import Loader from "./../../Loader.svelte";
  import View from "./View.svelte";
  import Edit from "./Edit.svelte";
  let viewMode = $params.mode === "view";
</script>

{#if $initializing}
  <Loader />
{:else}
  {#await isAdmin($userInfo) then admin}
    {#if admin && !viewMode}
      <Edit />
    {:else}
      <View />
    {/if}
  {/await}
{/if}
```

Perhaps I am wrong and there is a better approach to handle this use-case, without polluting the url with view or edit path.

**Comment by tonprince** [comment]
I just added metadata query-param-is-page, that works fine :-)

**Comment by arctica** [comment]
Would it make sense to actually turn off the default "ignore navigation event if X not changed"?

I would expect the router to behave like the standard browser behavior where a click on a link causes a navigation action unless the URL has just a change in the #fragment part.

I'm not seeing much advantage in stopping these events from being processed as it is right now. Is there a good reason?

**Comment by jakobrosenberg** [comment]
>I'm not seeing much advantage in stopping these events from being processed as it is right now. Is there a good reason?

You would lose component state. By not forcing refresh on layouts unaffected by the URL change, you can create UIs that wouldn't be possible otherwise.

**Comment by arctica** [comment]
Hm,  maybe I'm missing something but shouldn't only components for the page specified by /path refresh and lose their state and for example the outer _layout not? That would be expected I would argue. Plus one can stop the navigation event from refreshing the component via beforeUrlChange - but one can't do the opposite it seems.

**Comment by jakobrosenberg** [comment]
How would something like this work?

```html
<script>
  import { page } from '@roxi/routify'
</script>

<button on:click={$page.reset()}>refresh page</button>
```

This way you can reset inner components and or their parent components: `$page.parent.reset()`

**Comment by jakobrosenberg** [comment]
> shouldn't only components for the page specified by /path refresh and lose their state

Imagine a component that lets you edit a 3D object. The camera position is stored in the components internal state, while the parameters are stored in the URL for easy sharing.

```javascript
// push object parameters to URL on changes
$: $goto(null, customization)
```
If the page refreshed each time you change the color or a decal etc. it would break the camera perspective and possibly even reinitialize it.

**Comment by arctica** [comment]
Yes I see what you are saying. Similar to google maps showing the current lat/long while one moves around on the map but obviously the map does not get reset each time. Makes sense but I'd still argue such application specific logic can be handled via beforeUrlChange. One app might want to refresh when the querystring changes, another might not want to. And it could even depend on the specific /page the user is currently on. You could also keep the current default behaviour and then if the user specifies a custom beforeUrlChange override that default.

Your suggested reset() method would work as well and could come in handy for other purposes than mine as well.

**Comment by mizzao** [comment]
Going from `2.12.12` to `2.13.0` breaks my app completely: nothing loads, browser tab is 100% CPU. This seems like it may have something to do with it?

**Comment by jakobrosenberg** [comment]
@mizzao, you're correct. I've released a patch to fix nollup compatibility.
