### ISSUE TITLE
SyntaxError: Unexpected token 'export' while running jest test cases

### ISSUE THREAD

**Issue by vikaspuri-goswami** [roxiness/routify#345]
SyntaxError: Unexpected token 'export' while running jest test cases. 

**bable.config.js**
```
module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        targets: {
          node: "current",
        },
      },
    ],
  ],
}
```

**Jest configuration in package.json**
```
"jest": {
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.svelte$": "svelte-jester"
    },
    "moduleFileExtensions": [
      "js",
      "svelte"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-dom/extend-expect"
    ],
    "testPathIgnorePatterns": [
      "dist"
    ]
  },
```
**Screenshot attached**
![jest error](https://user-images.githubusercontent.com/48320416/109959109-124cc500-7d0d-11eb-9a13-e88310f287f8.PNG)

**Comment by jakobrosenberg** [comment]
Can you set script to ESM somehow?

**Comment by vikaspuri-goswami** [comment]
@jakobrosenberg You can find the import statement in the first screenshot `import { goto } from "@roxi/routify"`.  We are using `jest src` in the `npm run test` command in pckage.json. Please let me know if you need anything else?

**Comment by jakobrosenberg** [comment]
If I'm reading the screenshot correctly, you haven't configured Jest to handle ESM.

**Comment by tmaxmax** [comment]
Same error here, is this looked upon?

**Comment by jakobrosenberg** [comment]
Does this help? https://github.com/roxiness/routify/issues/349

**Comment by vikaspuri-goswami** [comment]
We would need to ignore transform patterns for ESM. Below are the sample code for the reference.

1. Create array of ESM which we would need to ignore while transforming
2. Add full path of those modules in `transformIgnorePatterns`.
```
const esModules = ["@roxi"].join("|")

module.exports = {
  transform: {
    "^.+\\.js$": "babel-jest",
    "^.+\\.svelte$": "svelte-jester",
  },
  moduleFileExtensions: ["js", "svelte"],
  setupFilesAfterEnv: ["@testing-library/jest-dom/extend-expect"],
  testPathIgnorePatterns: ["dist"],
  transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
}
```

Let me know if any question, happy to help you.

**Comment by doylio** [comment]
Same issue here

**Comment by ghostdevv** [comment]
I think you need to configure Jest as Jake said to support esm. If you still having issues please reopen

**Comment by tobiasbueschel** [comment]
> I think you need to configure Jest as Jake said to support esm. If you still having issues please reopen

Thanks for this @vikaspuri-goswami!

Unfortunately, neither the `jest.config.ts` configuration to ignore the `routify` module nor the ESM approach worked for me. I still get the same error:
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/13087421/157404900-2ab97b1c-a363-401d-a7f9-13e6ae474cd6.png">

**Dependency versions used:**
```json
        "@roxi/routify": "^2.18.5",
        "@testing-library/jest-dom": "^5.16.2",
        "@testing-library/svelte": "^3.0.3",
        "@tsconfig/svelte": "^3.0.0",
        "jest": "^27.5.1",
        "svelte": "^3.46.4",
        "svelte-check": "^2.4.5",
        "svelte-jester": "^2.3.2",
        "svelte-preprocess": "^4.10.4",
        "ts-jest": "^27.1.3",
        "ts-node": "^10.7.0",
        "tslib": "^2.3.1",
        "typescript": "^4.6.2",
``` 

**jest.config.ts**
```ts
import type { Config } from '@jest/types';

const config: Config.InitialOptions = {
    preset: 'ts-jest',
    testEnvironment: 'jsdom',
    verbose: true,
    transform: {
        '^.+\\.svelte$': [
            'svelte-jester',
            {
                preprocess: true
            }
        ],
        '^.+\\.ts$': 'ts-jest',
        '^.+\\.js$': 'ts-jest',
        '.+\\.(css|styl|less|sass|scss)$': 'jest-css-modules-transform'
    },
    setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect'],
    moduleFileExtensions: ['js', 'ts', 'svelte'],
    transformIgnorePatterns: ['<rootDir>/node_modules/(?!@roxi)']
};

export default config;
```

I've also tried:
```json
"test": "NODE_OPTIONS=--experimental-vm-modules jest src",
```

I'll share back if I find a fix - if someone else has any suggestions in the meantime, would greatly appreciate it 🙏 

Thanks

cc @ghostdevv

**Comment by TimoReusch** [comment]
@tobiasbueschel I'm facing the same problem - have you found a solution meanwhile?

**Comment by ghostdevv** [comment]
I would recommend migrating to Vitest, for the most part it should be a drop in replacement for Jest as it supports the Jest mock syntax OOTB

**Comment by aarzootrehannagarro** [comment]
Any solution for this issue?
