### ISSUE TITLE
ParseError: \node_modules\@roxi\routify\lib\utils\util.js

### ISSUE THREAD

**Issue by moisesGarmendia** [roxiness/routify#348]
Hi, really like the way Routify works, hope to contribute at least translating the docs to spanish 😄 , I have a problem, so I hope you can help me 👍 

I'm running on Windows, it is a Virtual Machine from Amazon Workspaces with Windows Server 2016 Version 1607(OS Build 14393.4225). But do not think that this is affecting, just put it in case
Node version is: v14.15.5

I think the important part of the parseError occurs here:
ParseError: \node_modules\@roxi\routify\lib\utils\util.js
Error: ENOENT: no such file or directory, open 'D:\Users\moises.garmendia\Desktop\ERD\ERD.Client\node_modules\@roxi\routify\lib\utils\util.js'
I looked for the util.js class in the util folder but did not found it, no luck for me :(, after that, i try looking in this repo but there were no util.js in that folder :/, when I use rollup in treats it as an external dependency and does not work also.

**bug description**
Expect to parse correctly because 3 days ago when i touched the code was working :(

**package.json**
I'm running `npm run dev`, but Friday I got errors in runtime so i decided to use `npm run rollup` + `npm run serve` combo, and was working fine, slow, but working.

"scripts": {
    "dev": "run-p routify nollup",
    "dev:ssr": "run-p routify rollup",
    "build": "run-s build:*",
    "build:app": "routify -b && rollup -c",
    "build:static": "spank",
    "serve": "spassr --port 5020",
    "rollup": "rollup -cw",
    "nollup": "nollup -c",
    "routify": "routify",
    "start": "sirv public --single"
  }

**version**
"@roxi/routify": "^2.12.4", I use the version that was in the template, i init the project on February 11th. 

**screenshot**

![image](https://user-images.githubusercontent.com/78880943/110330582-8a540d00-7fe3-11eb-9c94-c79053bc4e8c.png)

Thanks in advance, I will uninstall Node and reinstall it but don't think that it will solve the issue. I tried deleting node_modules folder and package-lock.json and run `npm i` but did not work.

**Comment by moisesGarmendia** [comment]
I tried to update all the dependencies and devDependencies, but did not work.
I used the Routify template, and was working, later when I tried to move what I've done, it simply get crashed running `npm run dev`, I removed the component that I thought was making the issue, but nothing.
I even comment all the components but did not get any luck with this...
Reinstall Node also did not work.
I will try to pass to the template file by file, or even code by code even if it takes all day!, really like Routify, but if after all that I am going to try is not working, I'm afraid I will use another router :c
![image](https://user-images.githubusercontent.com/78880943/110344352-0275ff00-7ff3-11eb-84d1-67dc57974499.png)
I do not think is an issue related to nollup (or maybe not :o) since Rollup have the same problem but treats it different

**Comment by moisesGarmendia** [comment]
After copying and pasting the code I write, it seems that the problem was not Routify (Nice news), nor Nollup ( ok?... ), really I do not know what happen, I just can imagine that something get cached and made the issue, I'm new to front-end so, no clue of what was the problem here, but sure Nollup and Rollup got involved, because, ok, there is no util.js in util folder, but, why you expect to be a file called util.js in that folder?, too much to me, at least at my actual level.

Take care people, and @jakobrosenberg , I would not mind if you let me translate (to spanish) the docs of Routify X.x :), that way more people can get engage I think, blessings.

**Comment by jakobrosenberg** [comment]
@moisesGarmendia Happy you got it fixed. Would love Spanish translations!

Feel free to drop by our Discord 🙂
