### ISSUE TITLE
Bug - Uncaught (in promise) TypeError: fn is not a function

### ISSUE THREAD

**Issue by lamualfa** [roxiness/routify#351]
## Important

This error only occurs in Routify `v2.16.0`. I've tried Routify `v2.14.0`, but the error doesn't happen.

<hr>

## Bug Description

I get this error when click the back button of the browser. In other case, i got this error also when navigate to another page that contain `metatags` helper.

![image](https://user-images.githubusercontent.com/39755201/111654755-9fc70380-883b-11eb-8dd6-7d4b53d24cdf.png)

<hr>

## How to get this error?

1. Clone the Routify Starter template using `npx degit roxiness/routify-starter routify-starter`
2. Goto the project directory: `cd routify-starter`
3. Prepare module: `pnpm i`
4. Run: `pnpm dev`
5. Create new file with name `test.svelte` in `src/pages`
6. Put some code to that file. For me, i put this code:

```svelte
<script>
  import { onMount } from 'svelte';
  import { metatags } from '@roxi/routify';

  onMount(() => {
    new Promise((resolve) => setTimeout(resolve, 3000)).then(() => {
      $metatags.title = 'Hello world';
      $metatags.description = 'Lorem ipsum dolor suila vot';
    });
  });
</script>

<h1>Hello world</h1>
```

7. Add a link with the destination to `test.svelte` page:

**Example**

**`src/pages/example/_components/RoutifyIntro.svelte`**

```svelte
<h1>Routify Starter</h1>

To see an example app, go to 
<a href="/example">/example</a>
<a href="/test">/Test</a> // Add this

<p>To delete the example app, simply delete the ./src/pages/example folder.</p>
```

8. and then open your browser, and goto http://localhost:5000/.
9. Open your Browser Console (or Dev Tools).
10. Click Test link that was created before.
11. Click back button of your browser.
12. You will get this error in your browser console.

<hr>

## Environment

- Routify `v2.16.0`
- Svelte `v3.29.4`

**Comment by jakobrosenberg** [comment]
You mention it only happens in `2.16.0`, but the code you posted isn't compatible with prior versions.

Do you know if it only happens when you use `$metatags` as a store?

**Comment by lamualfa** [comment]
@jakobrosenberg Yeah I know that. You just released `v2.16.0` yesterday to add support for using `metatags` asynchronously. 

If you try the code above on a version below `v2.16.0` (e.g. `v2.14.0`), the error that appears will be different and was resolved yesterday on `v2.16.0`. That's why I confirmed that this error only occurs on `v2.16.0`.

**Comment by ghostdevv** [comment]
@lamualfa the reason it errors on anything below 2.16.x is because the code didn't exist then.

Anyways jake will look into this for ya soon

**Comment by jakobrosenberg** [comment]
My concern is, did we break something that was actually working before or is the issue limited to using `metatags` as a store?

**Comment by lamualfa** [comment]
First of all, I am sorry. It seems that the description I gave is unclear. Therefore I try to summarize.

<hr>

## Below `v2.16.0` (_this issue was not shown for this version_)

The problem only occurs in `metatags` that use the store. Meanwhile in this version Routify doesn't support `metatags` as store. So it can be concluded that the issue I created this time was not shown for this version.

<hr>

## `v2.16.0` and above

In this version Routify has been used `metatags` as a store. If you use this version and then use `metatags` as a store, you will get this error:

![image](https://user-images.githubusercontent.com/39755201/111654755-9fc70380-883b-11eb-8dd6-7d4b53d24cdf.png)

For more detail about on how to get this error i have explained above.

**Comment by ghostdevv** [comment]
This error only seems to happen after hmr occurs

**Comment by lamualfa** [comment]
@ghostdevv So is this a bug, or is there something wrong with the way I did it?

**Comment by ghostdevv** [comment]
@lamualfa From what I can tell `$metatags` will work fine in prod, it's being weird with `svelte-hmr` so you can just manually reload effected pages till we find out exactly what causes the hmr issue and fix it. But you shouldn't have any issues in production

Basically `svelte-hmr` just hot module reloads page data when changes are made, so you will see this error whenever you save a file in development mode, but to fix you can just reload the page manually

**Comment by lamualfa** [comment]
@ghostdevv Ok, thanks.

**Comment by lummie** [comment]
FYI I had this in dev (using vite for hmr) and in production. I set metatags.title in both a _layout.svelte AND the index.svelte. 
When I navigated between child pages after a few navigations I'd get the error (sometimes 2-3 navs)  
When I removed the setting metatags.title from the index.svelte, I couldn't reproduce the error. 

I'm guessing that setting this "registers" a destroy for the `<title>` tag every time it metatags.title is set but if it already exists still registers a destory, which fails as the tile was removed from the previous register when the component is destroyed?  
Not looked at the code, but that's my interpretation... 

on @roxi/routify v2.18.3

**Comment by ghostdevv** [comment]
The title tag is set with `document.title` @lummie - do you have the exact error? I will see if I can look into this for you

**Comment by lummie** [comment]
Well that's embarrassing, added setting or metatags.title back and can no longer re-replicate :( which is no help whatsoever. I must have changed something elsewhere too, but no idea what. Sorry to waste your time.

**Comment by ghostdevv** [comment]
@lummie No worries! Let me know if it happens again
