### ISSUE TITLE
Case Insensitive Routing

### ISSUE THREAD

**Issue by ghostdevv** [roxiness/routify#359]
**Is your feature request related to a problem? Please describe.**
A baked in way to have case insensitive routing

**Describe the solution you'd like**
Either a config option or a boolean passed down to the router for example:
```html
<Router insensitive />
```

**Describe alternatives you've considered**
There is of course ways to do this already but a built in one would be great

Note: when implemented ensure that no conflicts are caused, some file systems are insensitive so both `test.svelte` and `Test.svelte` could exist causing a conflict if case insensitive routing is used.

Based on https://github.com/roxiness/routify/issues/343

**Comment by jakobrosenberg** [comment]
We could make some premade urlTransformers to solve this. That way we keep the solution transparent and avoid added complexity.

```html
<script>
  import { Router } from '@roxi/routify'
  import { caseInsensitive } from '@roxi/routify/urlTransformers'

  const config = { urlTransform: caseInsensitive }
</script>

<Router {config} />

**Comment by ghostdevv** [comment]
@jakobrosenberg I was thinking something like `<Router insensitive />`, this wouldn't just be able to done via urlTransform I think since some file systems are case insensitive meaning you could have `ID.svelte` and `id.svelte` and just a url tranform could cause issues

**Comment by jakobrosenberg** [comment]
Good point, but if we're doing case insensitive routing, there would be no reason to use uppercase filenames.

**Comment by ghostdevv** [comment]
I know but it would still cause conflicts, maybe Routify should make some console warn when such conflicts are found?

**Comment by jakobrosenberg** [comment]
V3 feature?

**Comment by ghostdevv** [comment]
@jakobrosenberg Yes
