### ISSUE TITLE
404/fallback page rendering

### ISSUE THREAD

**Issue by shiftmeplease** [roxiness/routify#363]
#### fallback page rendering
hello, is there any options or ways to ssr 404/fallback page, so it will be a html file in dist?
So, it can be served in cases when route cannot be not found, not just redirect to __app.html

**Comment by jakobrosenberg** [comment]
This is somewhat of a paradox. To know if a page exists Routify has to be loaded, for Routify to be loaded, __app.html has to be loaded.

If you're using SSR the 404 will automatically be rendered.

For static site generation, where you're 100% sure that all your pages are prerendered, you can set the urlRewrite/forwarding of your server to a 404.html page.
