### ISSUE TITLE
Set Interval not ereased from js after ereasing from code

### ISSUE THREAD

**Issue by agussander** [roxiness/routify#366]
**bug description**
I've used `setInterval(()=>{any},any); ` inside a component. Then, if i delete it from the code, it keeps running. Even if i delete some part of the function it does, it keeps running too, so when replacing with another function, both will be executing (causing collides). 

**expected**
When deleting a setInterval function it is deleted from the generated code.

**example**
you can try adding this:
`setInterval(()=>{
count++;
console.log("count");
},1000);`

save it, then erase the content inside setInterval, or everything, and save again

**notes**
Im not an expert. I dont know if this problem is caused by an svelte's behavior or a routify's.
Not native English speaker to, so sory if any mistakes or misunderstandings.

**Comment by ghostdevv** [comment]
This wouldn't be a issue with routify, when using set interval you should be clearing the interval on destroy like this:
```html
<script>
    import { onDestroy } from 'svelte';
    
    const interval = setInterval(...);
    
    onDestroy(() => clearInterval(interval));
</script>
```

**Comment by jakobrosenberg** [comment]
This may actually be a bug in Svelte. I can't remember if Svelte is supposed to kill lingering `setInterval` and `setTimeout`s in destroyed components.

But as Ghost said, this isn't related to Routify.
