### ISSUE TITLE
Routify options redirect required index to be part of the string

### ISSUE THREAD

**Issue by vikaspuri-goswami** [roxiness/routify#368]
`<!-- routify:options redirect="/some/path" -->`

This feature required `index` to be part of the redirect syntax and resulting that, it will append `/index` in the URL, which is not required.

**Comment by jakobrosenberg** [comment]
Sorry for dragging my feet on this one. Can you verify that it works as expected in `2.18.2`

**Comment by vikaspuri-goswami** [comment]
@jakobrosenberg Thanks for your response. It works fine now. One more question, how could we use JavaScript variable in the redirect path?

**Comment by jakobrosenberg** [comment]
@vikaspuri-goswami you would have to use the runtime helper then. https://routify.dev/docs/helpers#goto

**Comment by vikaspuri-goswami** [comment]
Thank you @jakobrosenberg
