### ISSUE TITLE
layout and url typed as 'any' in typescript

### ISSUE THREAD

**Issue by allanvobraun** [roxiness/routify#371]
**bug description**
The layout and url properties from routify are wrongly typed as any. 

**package.json**
https://github.com/allanvobraun/svelte-base-project/blob/main/package.json

**version**
```
 "@roxi/routify": "^2.18.0",
"svelte": "^3.37.0",
"typescript": "^4.2.4"
```

**screenshot**
![image](https://user-images.githubusercontent.com/52121195/120121103-0475d700-c178-11eb-812e-752e2d8cc40a.png)
![image](https://user-images.githubusercontent.com/52121195/120121115-13f52000-c178-11eb-9fad-5d5b05df6299.png)

**Comment by ghostdevv** [comment]
I'll see if I can reproduce this, and if so I'll issue a fix

**Comment by allanvobraun** [comment]
Ok thx.

**Comment by ghostdevv** [comment]
@allanvobraun I haven't had a chance to try out the repository you linked yet, just at a guess (I haven't used TS with Svelte in a while), could it be that you aren't specifying `lang="ts"` in the script tag?

If this doesn't fix it lmk and I will take a look for you

**Comment by allanvobraun** [comment]
With lang="ts":
The code works, but the ide doesn't recognize the properties being exported from routify. This only happens with routify, in other libraries the ide identifies and shows the types of exported properties automatically. 
![image](https://user-images.githubusercontent.com/52121195/120550655-87db3680-c3cb-11eb-8176-3835f002d0ee.png)
![image](https://user-images.githubusercontent.com/52121195/120550688-9295cb80-c3cb-11eb-9b93-e3b16fc0345d.png)

**Comment by jakobrosenberg** [comment]
Is this an issue with Routify types in general or just $url and $layout?

**Comment by allanvobraun** [comment]
Any type under `module '@roxi/routify'` have this issue.
I haven't tried any other module under routify.

**Comment by ghostdevv** [comment]
So what IDE are you using? because things seem fine for me in Visual Studio Code.

This will probably be the Js doc not the typescript declarations kicking in in VSC, so would need to be on the same IDE as you to test.

**Comment by allanvobraun** [comment]
I'm using webstorm. I will test in vscode later.

**Comment by ghostdevv** [comment]
@allanvobraun Did you have any luck with this?

**Comment by allanvobraun** [comment]
Yes in vscode everything works, this really is a webstorm issue, thanks anyway!

**Comment by risalfajar** [comment]
Hello, any solution to make this works with Webstorm?

**Comment by ghostdevv** [comment]
Unfortunately none of us use webstorm so I am unable to come up with a solution

**Comment by jakobrosenberg** [comment]
It's possible that a plugin for Webstorm could fix this. I haven't used Webstorm in years, but I seem to remember they had an extension store.

**Comment by risalfajar** [comment]
@jakobrosenberg they do: https://plugins.jetbrains.com/webstorm
