### ISSUE TITLE
No reactive actions in static page

### ISSUE THREAD

**Issue by timoanttila** [roxiness/routify#372]
I normally use static pages which have some reactive functions, always `npm run build`. I have a checkout page which should show a different view depending on status. If url has `?id=1031`(return from external website), page should activate variable `done`, but in the static version, all checks fail and default message is showing.

`npm run dev` and `npm run dev:ssr` works as expected.

Problematic page:
https://github.com/TuspeDesign/Svelte-Foodis/blob/main/src/pages/kassa.svelte

Project:
https://github.com/TuspeDesign/Svelte-Foodis

Am I doing something wrong or how I can activate the done message?

**Comment by jakobrosenberg** [comment]
Any chance you can make a minimal reproducible example? I'm not sure I understand the bug you're describing.

**Comment by timoanttila** [comment]
https://github.com/TuspeDesign/Svelte-Foodis/blob/main/dist/kassa/index.html
When creating that page, there is that `<p>Ei tuotteita ostoskorissa. <a href="/">Palaa etusivulle</a>.</p>` for those who have nothing in cart (`npm run build` makes errors if just redirected to the front page). That text should only be seen if no content and `done` has no value.

When all information is collected, the user is redirected to an external website where payment is made. After that, the user goes to the backend and then back to the frontend. There is `?id=number` in url so I know everything went well and the order is ready. But after coming back there is only that "error text" and not the text which should be if `done` is active.

http://foodis.dataline.fi/kassa/?id=13 <= wrong message for id. Should be thanks in Finnish.

```
$: done = "";
$: if (window.location.search) {
	let item = window.location.search.substr(1).split("=");
	if (item[0] == "id") {
		done = parseInt(item[1]);
		cart.set({ total: 0, amount: 0, products: [] });
	} else done = "";
}
```

The code above should take control after coming back from the external website and activate `{#if done}` instead of failing all the if statements. Works fine `npm run dev`.
https://github.com/TuspeDesign/Svelte-Foodis/blob/main/src/pages/kassa.svelte

The checkout is kind of special and you need to know the address nearby or you just end up with a contact form.

**Comment by timoanttila** [comment]
I don't know what is the best way to fix that, but I changed kassa.svelte to /kassa/index.svelte and added a new file /kassa/valmis.svelte for ready messages. Not the ideal resolution, but I don't have time to wait.
