### ISSUE TITLE
Routify propagates url parameter changes into to-be-routed-out-of pages

### ISSUE THREAD

**Issue by haibane-tenshi** [roxiness/routify#373]
Example directory structure:
```
person/
    [id].svelte
    new.svelte
```

`[id].svelte` has

```
<script>
    export let id;

    // Note the `$:` - important for reactivity.
    $: promise = query_from_server(id);
</script>

{#await promise then data}
    <!--render data-->
{/await}
```

It is important that we react there to changes in `id`: otherwise navigating between `person/[id]` with different ids doesn't update the page. Everything works as expected until you try to navigate from `person/[id]` to `person/new`: it causes an error fallout on server.

I figured out the reason behind it. It seems that routify propagates change in `id` into `[id].svelte` before deinitializing it. Obviously `new.svelte` has no `id` parameter on its route so old valid `id` changed to `undefined` which causes issues with validation on queries (it requires at least some `id` to be present).

This behavior persists when navigating to any target under `person/` which isn't under `person/[id]/`. Navigating to other pages seems to work as expected.

**Comment by jakobrosenberg** [comment]
Hi @haibane-tenshi. The `export let` method of handling params is synchronous with URL changes. You can use the `$params` helper for properly propagated parameters.

This should be added to the docs.

**Comment by haibane-tenshi** [comment]
Oof. I totally read through parameter [Synchronicity](https://routify.dev/guide/introduction/parameters) and totally forgot about that one. Your advice works, thanks.

The worst part here is inconsistency. Routing from `/root/person/[id]` to `/root/person/test` triggers `id` change, but going from `/root/person/[id]` to `root` doesn't. That's what instantly got me thinking this is a bug. Also I didn't test it, but I wonder what happens when routing from `person/[id]` to `person/other/path/[id]`.

Docs have necessary info, but I feel like it just teaches you the wrong way. I remember reading through page and thinking "Oh, it's just svelte props". But this method comes with hidden footguns for common use. And its very easy to glance over last paragraph like I did.
I feel like it should tell you to use `$params` (it is almost certainly what user wants anyways) and only then mention option of using svelte props for special needs (I believe there already hooks for routing so I'm not even sure what those needs could be).

**Comment by jakobrosenberg** [comment]
@haibane-tenshi I totally agree. Routify 3 in its current shape deprecates the `export let` and asynchronous routes. This will most likely also be the case on release.

**Comment by haibane-tenshi** [comment]
Good to know. Guess, I'm closing the issue as the problem is resolved.
