### ISSUE TITLE
How to generate dynamic css link?

### ISSUE THREAD

**Issue by manutheblacker** [roxiness/routify#374]
I've started a new project with Routify, and I'm implementing an HTML template into my application.
I've been able to setup several multiples pages, when I create a page under a folder,
this new page created use the default __app.html, but into this one I'm using a static CSS file link,
how can I do to make link to this static CSS file dynamically, so he'll change from himself whenever the folder he is called from.

**Comment by jakobrosenberg** [comment]
Are you looking for something like this?

https://svelte.dev/tutorial/svelte-head

**Comment by manutheblacker** [comment]
Yes i searching something close to this

**Comment by manutheblacker** [comment]
I've figured out, I must import my CSS into App.svelte inside the style block like this 

![image](https://user-images.githubusercontent.com/25031292/120800163-8dee2600-c537-11eb-810b-4b95cb609816.png)

**Comment by manutheblacker** [comment]
I will close it.

**Comment by ghostdevv** [comment]
What bundler are you using @manutheblacker

**Comment by manutheblacker** [comment]
I'm using Rollup the default bundler

**Comment by manutheblacker** [comment]
Maybe this need to be added to the documentation for the newbie

**Comment by ghostdevv** [comment]
It's not really a routify thing so I doubt it would get added to the docs, at least it's sorted now :)

**Comment by manutheblacker** [comment]
thank you sha
