### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by ghost** [roxiness/routify#375]
So, routify is written in javascript. Can it be **completely**  rewritten in **Typescript**  so that we get benefits of Typescript ?

**Comment by jakobrosenberg** [comment]
I assume anything can be rewritten in TS. What benefits do you have in mind that's not already covered? Type completion should work out of the box.

**Comment by ghostdevv** [comment]
I already asked for this for the upcoming Routifty 3 but it's not currently guaranteed

**Comment by ghost** [comment]
@jakobrosenberg while having types guarantee that external typescript applications working with this library will have types, rewriting this library in typescript guarantees that there will be less bugs if any do exist.

**Comment by ghostdevv** [comment]
Why'd you close?
