### ISSUE TITLE
Test for page URLs

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#38]
It would be useful to be able to match a URL and adjust something based on the current URL. This could be useful to switch layouts in a centralized `_layout.svelte`: 

Example code:

````
<script>
    import { currentPageUrl } from '@sveltech/routify'   // Pseudo code, function does not exist!
</script>

{#if currentPageUrl.match(/intro/)}
    <!-- Render special layout -->
{:else}
    <!-- Render standard layout -->
{/if}
````

How would I test for page URLs with the current implementation?

**Comment by jakobrosenberg** [comment]
I think the isActive() helper should do the trick.
https://routify.now.sh/docs/helpers

````
<script>
    import { isActive } from '@sveltech/routify'
</script>

{#if $isActive('/intro/')}
    <!-- Render special layout -->
{:else}
    <!-- Render standard layout -->
{/if}
````

If you need the URL of the current component you can always use the url helper. ``$url()`` (shorthand for ``$url('./')``.

**Comment by Wolfr** [comment]
This works, this helps to clean up my code.

This does lead to a new problem which is that a URL to a page can be `/intro` whereas the browser might put a `/` behind this - thus having a difference between `/intro/` and `/intro`.

Here is an example, check the rendering difference between

https://bestof2019.johanronsse.be/

And after clicking “Intro” manually.

Code used in this case (for “short” pages we use a layout that centers the content, otherwise we use a very basic layout)

````
{#if (
    $isActive('/index') || $isActive('/disclaimer')
) }
    <div class="c-sticky-footer-layout">
        <div class="c-sticky-footer-layout__item">
            <Header />
        </div>
        <div class="c-sticky-footer-layout__item--grow">
            <div class="c-sticky-footer-layout__item-inner-center">
                <slot />
            </div>
        </div>
        <div class="c-sticky-footer-layout__item">
            <Footer />
        </div>
    </div>
{:else}
    <Header />
    <slot />
    <Footer />
{/if}
````

I also wanted to catch the 404 in my first “if” statement. I experimented with the $leftover variable but couldn't really make that work.

**Comment by jakobrosenberg** [comment]
That is very peculiar.  Any chance I could get you to ``console.log($url())`` on the page?

**Comment by jakobrosenberg** [comment]
I suspect that your layout might be rendered before @isActive is able to fetch the URL. I don't see how that should be possible or even how it should be an issue as $isActive is reactive.

**Comment by jakobrosenberg** [comment]
Additionally, the trailing slash shouldn't matter as the matching is done with ``currentPath.includes(path)``. CurrentPath may have a trailing slash, but path won't as it's parsed by the url helper.

**Comment by Wolfr** [comment]
If I log like this: `$: console.log($url());` you can see that all of the pages on https://bestof2019.johanronsse.be/ return `/` instead of their actual URL (deployed version has a console.log now)

**Comment by jakobrosenberg** [comment]
Solved on Discord.

For anyone running into this. Svelte didn't want a store in an if-else condition. Abstracting the condition and assigning it to a variable in the script tags solved it.
