### ISSUE TITLE
It seem page component called while it should to be leaved

### ISSUE THREAD

**Issue by hyuzea** [roxiness/routify#380]
https://github.com/yus-ham/routify-app-error-on-leave-page/blob/main/src/pages/user/%5Bid%5D/edit.svelte

![image](https://user-images.githubusercontent.com/3823496/121765738-67536f00-cb77-11eb-9ccf-8913be2233bb.png)

**Comment by jakobrosenberg** [comment]
Hi @sup-ham. Could your issue stem from using an equivalent of `export let` over `$params`?

> Synchronicity
Local parameters are directly synchronized with the address bar whereas global parameters are first propagated through the layout component chain. The propagation is to prevent race conditions between parameters and component state.

https://routify.dev/guide/introduction/parameters

**Comment by hyuzea** [comment]
here code I used to test
https://github.com/yus-ham/routify-app-error-on-leave-page/blob/main/src/pages/user/%5Bid%5D/edit.svelte 

```
{error({ id, 'url()': $url(), pathname: location.pathname })}
{error({ '$params.id': $params.id, 'url()': $url(), pathname: location.pathname })}
{error({ '$$props.id': $$props.id, 'url()': $url(), pathname: location.pathname })}
```


![image](https://user-images.githubusercontent.com/3823496/121785303-3f99f080-cbe3-11eb-9f66-94a5be1ed041.png)

**Comment by jakobrosenberg** [comment]
What happens if you omit the `$$props.id` line?

**Comment by hyuzea** [comment]
It same 
![image](https://user-images.githubusercontent.com/3823496/121811334-4f224380-cc8e-11eb-90c3-36aa7ea5d498.png)

**Comment by hyuzea** [comment]
Long time no check this issue. trying some research, and the work around is not to referencing  local params from markup, use global $params instead. 
I dont know whether should this to be fixed or just add some note to the docs


```
<!-- blogs/view/[slug].svelte -->
<script>
  import { params } from '@roxi/routify';
  export let slug;
  
  console.error('Local param in <script>: ', slug)
</script>

{ console.error('Local param in markup:', slug) } <!-- trigger calls to this component, may be `update()`  before leaving to ancestor page
{ console.error('Global param in markup:', $params.slug) }

<a href="/blogs">Go to /blogs</a>
```
![image](https://user-images.githubusercontent.com/3823496/175792335-5457ba82-5719-4307-8626-6e9b1e83b893.png)

**Comment by jakobrosenberg** [comment]
Hi @yus-ham . Would you interested in submitting a PR?

FWIW R3 handles these things far better.

**Comment by yus-ham** [comment]
@jakobrosenberg yes,  I think I will just add few notes
