### ISSUE TITLE
Correct way to implement filepond

### ISSUE THREAD

**Issue by RubenOAlvarado** [roxiness/routify#382]
I'm trying to add filepond svelte component to d'n'd images to my forms. But I had problems in dev environment running "npm run dev", it fails in some weird ways; and when I run npm run dev:ssr, it doesn't fail, but I can't drag the image. 
Is there a correct way to implement filepond? or how can I manage this issue?

Please help.

**Comment by jakobrosenberg** [comment]
Hi @RubenOAlvarado, are you getting any errors?

**Comment by RubenOAlvarado** [comment]
Hi, @jakobrosenberg. Yes it shows 'plugin is not a function' when I run "npm run dev", in ssr it does not show any error but the d'n'd it's left to work.

**Comment by jakobrosenberg** [comment]
Hmm, I can't tell what the cause could be, but if it works in `dev:ssr`, it's probably a nollup issue. You can try post on the nollup repo or use rollup or vite instead. For setting up a vite project, please refer to [stackmix](https://github.com/roxiness/stackmix).

**Comment by RubenOAlvarado** [comment]
Thanks, @jakobrosenberg I'll check it.
