### ISSUE TITLE
It is a way to have i18n like in WordPress?

### ISSUE THREAD

**Issue by manutheblacker** [roxiness/routify#383]
I'm building a project and I'm not able to setup correctly the i18n.

I've done a lot of search and unfortunately there is no way to do what I want.

Furthermore, I've been working with WordPress some years ago, if we want to i18n we use a function like this :

<?php echo __('text_that_must_translate'); ?>.

I'm still wondering if there is an alternative to this way into routify, doing like this way it will help me build fast my app and worry at the end about the i18N

**Comment by jakobrosenberg** [comment]
Hi @manutheblacker - sorry about the late reply.

Your example seems to be missing from your post. If you add it, I'll have a look.

**Comment by manutheblacker** [comment]
In WordPress, this is used : 
__( 'Post' ) & _e( 'Post' )
