### ISSUE TITLE
Cache Busting and Entry File Hashing

### ISSUE THREAD

**Issue by keithkelly31** [roxiness/routify#384]
**Is your feature request related to a problem? Please describe.**
I am having a problem with the SPA portion once the page is hydrated.  Since the bundle file is always named main.js users do not see updates I have made to the application due to browser caching.  

Any changes made show with the static build from spank, but then disappears when the SPA takes over.

If I change the `entryFileNames` option in the rollup config file, spank will fail because it is looking for /build/main.js.  I have tried to provide a spank config, but don't see how I can properly sync the hash generated in rollup to the script option in the spank config.

**Describe the solution you'd like**
I would like be able to change the `entryFileNames` in the rollup config to include a hash so the browser cache is busted.  This means that the file name would need to be injected into the __app.html (instead of hard coding the script tag) and pages built by spank.

**Describe alternatives you've considered**
I have tried appending the main.js file name in the __app.html file with a query string and version number.  This doesn't seem to solve the issue and actually introduced an issue where files in the <head> were doubled up.  It was worse with the `modulepreload` script tag because there were two instances of the app being loaded and both showing on the screen one under the other.

I have also tried several rollup html plugins that would inject file names into generated html, but that didn't help because they couldn't account for all of the files that spank is generating. 

I think that the best solution would be an option within routify / spank to hash the main.js filename and inject that properly into the generated html files.

**Additional context**
N/A

**Comment by jakobrosenberg** [comment]
That's a good point and sounds like something maybe Spank/Spassr should handle.

I think Vite does what you're requesting. If that works for you, I recommend giving `stackmix` a try.

**Comment by keithkelly31** [comment]
Vite did exactly what I needed.  The stackmix examples helped get things set up quickly.  

Thanks!
