### ISSUE TITLE
Code suggestion not working on  routify project

### ISSUE THREAD

**Issue by paradis-A** [roxiness/routify#385]
**First rule of bug posting**
**There are no rules!**

**bug description**
I know its weird. But vscode code suggestion not working when writing plain .js file. i.e. below
`
let x = 12345
//when typing x or anything code suggestion does not appear at all.
`

**package.json**
{
  "name": "svelte-app",
  "version": "1.0.0",
  "@comments scripts": {
    "dev": "develop with blazing fast rebuilds",
    "dev:features": "develop with features like SSR and serviceworker enabled",
    "build": "run build scripts below",
    "build:app": "build single page application (SPA)",
    "build:static": "Generate static pages",
    "serve": "serve content in 'dist' folder",
    "rollup": "run the rollup bundler",
    "nollup": "run the nollup no-bundler",
    "routify": "run routify"
  },
  "scripts": {
    "dev": "run-p routify nollup",
    "dev:ssr": "run-p routify rollup",
    "build": "run-s build:*",
    "build:app": "routify -b && rollup -c",
    "build:static": "spank",
    "serve": "spassr --ssr",
    "rollup": "rollup -cw",
    "nollup": "nollup -c --silent",
    "routify": "routify"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@roxi/routify": "^2.18.1",
    "attractions": "^3.3.0",
    "cross-env": "^7.0.3",
    "fs-extra": "^10.0.0",
    "nollup": "^0.16.4",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.2.14",
    "postcss-import": "^14.0.1",
    "rollup": "^2.47.0",
    "rollup-plugin-hot": "^0.1.1",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.1.0",
    "rollup-plugin-svelte-hot": "^1.0.0-7",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-workbox": "^5.2.1",
    "spank": "^1.7.0",
    "spassr": "^2.6.0",
    "svelte": "^3.38.3",
    "svelte-preprocess": "^4.7.3",
    "tossr": "^1.4.2"
  },
  "routify": {
    "extensions": "svelte,html,svx,md"
  },
  "spassr": {},
  "spank": {
    "blacklist": [
      "/example/modal/basic/4"
    ]
  },
  "dependencies": {
    "@types/parse": "^2.18.8",
    "acebase": "^1.0.0",
    "acebase-client": "^1.2.2",
    "axios": "^0.21.1",
    "bootstrap": "^5.0.2",
    "client": "^0.0.1",
    "faye": "^1.4.0",
    "parse": "^3.3.0",
    "sass": "^1.35.2",
    "sockette": "^2.0.6",
    "sveltestrap": "^5.4.0",
    "wretch": "^1.7.5"
  }
}
![routify weird error](https://user-images.githubusercontent.com/42695235/127100342-d8908ca5-2dce-4409-927e-fa63462f5023.jpg)

Routify version: "@roxi/routify": "^2.18.1"

![routify weird error](https://user-images.githubusercontent.com/42695235/127100370-226bd6e0-ad94-43e0-ad1c-dbada13f94b2.jpg)

This only happens with routify project. Svelte Starter template works.

**Comment by jakobrosenberg** [comment]
Have you tried restarting VSCode? Routify shouldn't affect your code completion at all, it's just an npm package.

**Comment by paradis-A** [comment]
I tried restarting several times include svelte server language. The problem still persist.
But somehow updating the vs-code extension "JavaScript and TypeScript Nightly" fixed my issue.
