### ISSUE TITLE
How to use goto in a Svelte module? "goto is not a function"

### ISSUE THREAD

**Issue by ferulisses** [roxiness/routify#388]
Hi,

I'm coding a module with some functions to be used elsewhere and I'm having trouble to use goto, here some example:

functions.svelte
```
<script context="module">
    import { goto } from "@roxi/routify";

export function doSomething() {
    console.log("did it");
    goto("/newpage");
}
</script>
```

After that, I import the function in my App:
```
<script>
   import { doSomething } from "./functions.svelte";

  doSomething();
</script>
```

When running, I get the error "goto is not a function"

What is the proper way to do this?

**Comment by ghostdevv** [comment]
goto is a store, so it's:
```html
<script context="module">
    import { goto } from "@roxi/routify";

    export function doSomething() {
        console.log("did it");
        $goto("/newpage"); 
    }
</script>
```

**Comment by ferulisses** [comment]
This was what I thought, but this syntax give me the error:
```
Cannot reference store value inside <script context="module">
```

**Comment by ghostdevv** [comment]
@ferulisses You'd need to remove the context = module part. You could move it to a js file however goto only works in the context of a Routify app so it would error. I would suggest changing goto to something like `window.location.href = '/newpage';` or using the goto inside of the page (this is what I usually do) instead of externally

**Comment by ferulisses** [comment]
Hum, I tried using window.location.href, but it loses data on stores (unless saved on browser, what I'm not inclined to do), guess I will need to move goto to the page. 

Thanks anyway.

**Comment by jakobrosenberg** [comment]
@ferulisses if you don't need dynamic redirects, you can also use this:

- `redirect` redirects before component is loaded
- `rewrite` same as redirect, but preserves the URL

```html
<!-- Redirect example. Same for rewrite.-->

<!-- routify:options redirect="/some/path" -->
<!-- routify:options redirect={"path": "/some/path", "params": {"id": "1"} -->
```

You can also create guards with `beforeUrlChange`.

For `context="module"` guards you will have to wait for Routify 3, which we hope to release a preview of very soon.
