### ISSUE TITLE
A Problem   with route hash 

### ISSUE THREAD

**Issue by devhormiga** [roxiness/routify#391]
Hello I have a problem.
I try to use the hash based routes.
the typical ones where we use an ID in a **div** and then in the \<a href="#id">*tag

but it didn't work for me with routify

I have tried different things

in my app.svelte:
`<Router config = {{useHash: true}} {routes} />
`when I do it the links stop working, if I set it to false, they work.

then he left ne true and put the links like this

`<a href={$url('que')} target="_self"> What is it? </a>
`but this works in my local environment, but taking it to production doesn't work ...

some help?
Thank you so much

**Comment by jakobrosenberg** [comment]
Hey @devhormiga this issue completely went under my radar. So sorry about that. Is this still an issue?
