### ISSUE TITLE
{route} remembers previous parameters in a sessions

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#4]
maybe a feature?

I created a breadcrumb from a nested path. The breadrumb shows the different parts when route.params.XXX is present. When a deeper path is visited, and navigating back to a less deep path, the navigation is ok but the breadcrumb also shows the deeper path as route rembered this value.

**Comment by jakobrosenberg** [comment]
Could you give a realworld example with this? The old autism is acting up.

**Comment by tombroens** [comment]
https://github.com/tombroens/sveltefileroutertest

got to localhost:5000/123/456/432432/344

then click the breadcrumb, it should trim to the path, but previous visited params keep the breadcrumb to keep history.

**Comment by jakobrosenberg** [comment]
This should accomplish what you're looking for

**passing cached parameters to every component in the tree**
```html
<!-- src/pages/_layout.svelte -->
<script>
  export let route  
  $: cachedParams = {...cachedParams || {}, ...route.params}
</script>

<slot scoped={{cachedParams}} />
```
```html
<!-- nested_component.svelte -->
<script>
export let cachedParams
let {org, group, program, course} = cachedParams
</script>


```
Let me know if this example works for you


If you want the history, you can also pass history to every component in the tree
```html
<!-- src/pages/_layout.svelte -->
<script>
  export let route
  $: routeHistory = [route, ...(routeHistory || [])]
</script>

<slot scoped={{routeHistory}} />
```

**Comment by tombroens** [comment]
Sorry, I was not clear enough. I seems the params are caching at the moment, but that was what I was NOT expecting. I was expecting that every click on a <a> in the breadcrum would lead to a stateless router and the params would be cleared and filled again with the new URL. Now pressing a <a> keeps the params as they where, so also the deeper nested ones.

If I do a refresh than the params are cleared.

**Comment by jakobrosenberg** [comment]
Ah, I hear ya. You need reactive variables then.

Just change ``let to $:``
```html
<script>
  export let route; //current route;

  $: org = route.params.org;
  $: group = route.params.group;
  $: prog = route.params.program;
  $: course = route.params.course;

  let title = "";
  let top_title = "";

  function onRouteChange() {
    if (course) {
      title = course + " [course]";
      top_title = prog + " [program]";
    } else if (prog) {
      title = prog + " [program]";
      top_title = group + " [group]";
    } else if (group) {
      title = group + " [group]";
      top_title = org + " [organisation]";
    } else {
      title = org + " [organisation]";
    }
  }

  $: route && onRouteChange()
</script>
```

**Comment by tombroens** [comment]
Aahhh yes great....! Thanks for the help.
