### ISSUE TITLE
Params helper doesn't exist

### ISSUE THREAD

**Issue by rleija703** [roxiness/routify#40]
I'm trying to import the `params` helper util but it doesn't seem to be working

```
Error: 'params' is not exported by node_modules/@sveltech/routify/runtime/index.js
```

**Comment by rleija703** [comment]
I saw your Repo, and the helper function `params` does exist. Just re-installed it and it's there. Odd.

**Comment by jakobrosenberg** [comment]
Any chance you installed Routify in dev mode the first time?

**Comment by rleija703** [comment]
I ran the first time
`npm i --save-dev @sveltech/routify`

Second time I ran: (this one worked)
`npm i --save-dev @sveltech/routify@next`

**Comment by jakobrosenberg** [comment]
Ah, that would explain it. I thought I'd deleted the non @next version.
