### ISSUE TITLE
Navigating a folder with only a parameterized [id].svelte, without parameter gives error.

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#41]
TypeError: regexUrl.match(...) is nullnavigator.js:82:13
    urlToRoute navigator.js:82
    updatePage navigator.js:24
    instance$1 Router.svelte:14
    init index.mjs:1350
    Router bundle.js:1394
    create_fragment$8 bundle.js:2797
    init index.mjs:1364
    App bundle.js:2839
    app main.js:3
    <anoniem> bundle.js:2856

--> would expect it to hit the fallback?

**Comment by jakobrosenberg** [comment]
Good catch. I just tried it and while I'm getting a different error, I'm getting an error all the same.

I'm stuck between using a _fallback.svelte and an _error.svelte

**Comment by jakobrosenberg** [comment]
This should be fixed in the latest release. Let me know if this is not the case.

**Comment by jakobrosenberg** [comment]
I was too quick to call success on this one.

**Comment by jakobrosenberg** [comment]
Should be fixed  this time.
