### ISSUE TITLE
Q: current route info / redirect

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#42]
* In the svelte-filerouter we got the reactive route property. Is there also something to use in routify??

* when using $goto my page refreshes, is using a <a href> the preferred way to do a local redirect?

**Comment by jakobrosenberg** [comment]
You can use ``import { context } from "@sveltech/routify"`` and call it with ``$context``.

Please note that the helper is currently undocumented as we could introduce breaking changes down the road. We will however try not to.
