### ISSUE TITLE
helpers outside of page

### ISSUE THREAD

**Issue by ptone** [roxiness/routify#43]
This may just be a docs issue, but I got stuck for a while in trying to use the helpers from a component that wasn't a page.

I am using material, and have a nav drawer component used in my app.svelte

I can use the helpers from a page, or component reference from a page, but not from a component directly referenced from app.svelte - I get a `Uncaught TypeError: Cannot read property 'subscribe' of undefined`

**Comment by jakobrosenberg** [comment]
Helpers are contextual to their parent layout/page and thus don't work outside this scope.

At the top of my there are a few solutions
1. Use the ``src/pages/_layout.svelte`` for your main layout. **recommended**
2. Import Routify into ``src/main.js``. The ``src/`pages/_layout.svelte`` would become the new entrypoint. You could optionally (and possibly pointlessly) then import ``src/App.svelte`` into your layout.
3. Create a helper store in App.svelte with setContext() and update it from a layout. **not recommended**
4. It's possible, that we could create non-context helpers, but it would be added complexity and bundle size to support something that seems like an anti-pattern. Of course, if there's a strong argument for using helpers outside the Router that would be taken into consideration.

What are your thoughts on this?

**Comment by jakobrosenberg** [comment]
Closed for now. Can be reopened if anyone has anything to add.
