### ISSUE TITLE
Q: availablity of parameters in _layout

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#48]
I navigate to: /org/1234

It loads the _layout which is in org/[orgid] folder + the index.svelte. In the index it has availability of orgid while in _layout it hasn't.

I would expect it to be available to _layout's in the 'dynamic' folder??

**Comment by jakobrosenberg** [comment]
Good point. _layout.svelte would be more appropriate than index.svelte.

I'll see if I can push a fix for this. In the meantime I hope the $params helper will suffice.

**Comment by tombroens** [comment]
I would expect both files to have this parameter?

And yes $params.orgid provides the info ;-).

**Comment by jakobrosenberg** [comment]
This should be working now.

The way it's intended is that if a page has a ``[parameter]``, the parameter is passed to the page as a prop. In the case of a folder, the parameter is passed to the ``_layout.svelte`` (which for all intends and purposes could be considered ``_folder.svelte``).

**Comment by jakobrosenberg** [comment]
Closing this for now. Feel free to reopen it if you need.
