### ISSUE TITLE
include queryparameters in route object

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#5]
would it be nice to have the queryparameters in the route object similarly to parameters?

/:path1/ --> /hello/?name=world

route.parameters.path1 = hello
route.queryparameters.name = world

**Comment by jakobrosenberg** [comment]
I'm not sure we can add anything that doesn't already exist within a package like query-string. It would just be syntax sugar if the same can be achieved with ``queryString.parse(location.search)``

On the other hand, I like when batteries are included...

If there's no downside to it, I guess we could implement something like that. The current url helper would change from ``url(path, params)`` to ``url(path, params, query)`` and ``route.query`` could hold the current query.

**Comment by jakobrosenberg** [comment]
This is in the 1.5 beta which should be released as stable tomorrow. Documentation will follow.
