### ISSUE TITLE
No animations for extra elements in App.svelte

### ISSUE THREAD

**Issue by Tommertom** [roxiness/routify#51]
Hi

Additional elements in `App.svelte` do not seem to animate.

If I take the starter template and replace `App.svelte` with the following:

```
<script>
  import { Router } from "@sveltech/routify";
  import { routes } from "@sveltech/routify/tmp/routes";

  import { fade } from "svelte/transition";
</script>

<!-- src/App.svelte -->
<Router {routes} />
<div transition:fade={{ duration: 1500 }}>
  This is not animating, but showing
</div>
```

Then the additional div is not animating, but showing. 

I was trying this case for a cookie warning that should animate into the screen for the user, irrespective of the route the user enters the app. Either way, strange it shows, but not animates.

Animations work in other parts of the app (within the routes, so it seems).

**Comment by jakobrosenberg** [comment]
Should it be in an #if to work? On the phone so can't check.

**Comment by rixo** [comment]
You probably need to add `intro: true` to your `new App(...)`:

```js
const app = new App({
  target: document.body,
  intro: true,
})
```

> By default intro transitions will not play on first render. You can modify this behaviour by setting intro: true when you [create a component](https://svelte.dev/docs#Client-side_component_API). ([docs](https://svelte.dev/docs#transition_fn))

**Comment by Tommertom** [comment]
Thx @rixo .

Works like a charm.

I am playing with a move from another router which apparently doesn't need this setting.
