### ISSUE TITLE
isActive returning null

### ISSUE THREAD

**Issue by ptone** [roxiness/routify#54]
When I was on 1.0.1-15 I was having an issue with isActive returning true if the current path ended with something that matched the test, eg .../.../index  returned true as did .../index at the same time.

This can be seen at this preserved container:
https://frontend-debug-avzcrpvnta-uc.a.run.app/cars

and this commit:
https://github.com/ptone/firerest-demo/tree/4cd2d8c947892f3b81931192d9b04e62163835f3

HOWEVER, when going back to that commit and deleting package-lock and node_modules and re-installing, I  can't reproduce this :(

With this commit
https://github.com/ptone/firerest-demo/commit/e5cd4e4855a544c34ec41df90e0866b1dfd187aa

I updated to v23

And I first saw the "null" behavior
(but note the caveat above about being unable to revert and reproduce the "simultaneous active" issue)

https://cars-demo.ptone.dev/

The current nav component:
https://github.com/ptone/firerest-demo/blob/16e85cd4eb88238df211c5b7ba64090b38bda78c/webapp/src/pages/_components/AppNav.svelte

**Comment by etnilo-indra** [comment]
I am having the same issue.

**Comment by jakobrosenberg** [comment]
Doing some rewriting on the file scanner, but should hopefully have a fix released within the next few hours.

**Comment by jakobrosenberg** [comment]
The isActive helper has been fixed in v1.0.1-24

Thanks for the feedback @ptone @etnilo-indra 👍

**Comment by ptone** [comment]
I know this is closed, but just wanted to tag in with verification - this fixed my issue. Thanks!

**Comment by jakobrosenberg** [comment]
Much appreciated @ptone
