### ISSUE TITLE
Cannot find module 'picomatch'

### ISSUE THREAD

**Issue by Gibbu** [roxiness/routify#56]
While Routify is installed trying to update or add new packages will cause this error when running `npm run dev`:
![error](https://i.imgur.com/YFLqm1U.jpg)

__package.json__:
![package.json](https://i.imgur.com/jd4kPSz.jpg)

**Comment by jakobrosenberg** [comment]
Sorry about that @Gibbu 

This has been fixed in the most recent version. You can update it with ``npm i -D @sveltech/routify@next``

**Comment by Gibbu** [comment]
Legend! 👍
