### ISSUE TITLE
Can't anchor jump/scroll

### ISSUE THREAD

**Issue by Gibbu** [roxiness/routify#57]
```html
<a href="#jump">Jump</a>
<div style="padding-bottom: 2000px"></div>
<div id="jump">Jump</div>
```
Clicking the `a` tag will not snap the window to the `div` with the id.
But reloading while the hash is in the url will snap.

**Comment by jakobrosenberg** [comment]
Thanks for catching this. This is the first time I've seen this, but it makes sense as we listen in on the ``<a>`` clicks. I'll see if I can come up with a fix for this.

**Comment by jakobrosenberg** [comment]
The obstacle is how to handle it without burning the hash-based-routing bridge.

https://github.com/sveltech/routify/issues/22

The best approach is probably to just implement hash for its intended purpose for now. Down the road we can disable it for projects that use hash based routing.

**Comment by jakobrosenberg** [comment]
Fixed in the most recent release.

Scroll can now be enabled with ``routify -s`` or ``routify --scroll``. For smooth scroll use ``routify -s smooth``.

This will be added to the documentation.

**Comment by Gibbu** [comment]
Do I use `npx routify -s smooth` to enabled it? If so It just returns this and doesn't seem to do anything.
![image](https://user-images.githubusercontent.com/20338746/72216366-008de880-3574-11ea-9adf-669ab6c876db.png)

**Comment by jakobrosenberg** [comment]
What version are you on?

**Comment by Gibbu** [comment]
1.0.1-29

**Comment by jakobrosenberg** [comment]
Any chance I can see your ``package.json`` and ``rollup.config.js``.

**Comment by Gibbu** [comment]
Of course.
![image](https://user-images.githubusercontent.com/20338746/72216409-9f1a4980-3574-11ea-95c5-b4b8ea58c377.png)

```js
import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import {routify} from '@sveltech/routify';

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/build/bundle.css');
			}
		}),
		routify(),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};

function serve() {
	let started = false;

	return {
		writeBundle() {
			if (!started) {
				started = true;

				require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
					stdio: ['ignore', 'inherit', 'inherit'],
					shell: true
				});
			}
		}
	};
}
```

**Comment by jakobrosenberg** [comment]
Found the culprit. My advice was for package.json, but you're bundling with rollup.config.js.

Your config needs to go into rollup.config.js instead.

```javascript
	plugins: [
                ...
                routify( { scroll: 'smooth' } ),
                ...
```

Let me know if that does the trick.

**Comment by Gibbu** [comment]
That did the trick. Huge thanks! 👍

**Comment by jakobrosenberg** [comment]
You're most welcome. Happy that did it, cause I had to run after posting. 😋

**Comment by Gibbu** [comment]
Sorry to keep annoying you about this mate.
The `on:hashchange` event doesn't fire on `<svelte:window />` 
```html
<script>
  function hashChanged()  {
    console.log('hash was changed');
  }
</script>

<svelte:window on:hashchange={hashChanged} />
```
[package.json](https://hastebin.com/dijuzugeki.json) | [rollup.config.js](https://hastebin.com/ukusuzexod.js)

**Comment by jakobrosenberg** [comment]
No problem. We want smooth sailing.

We're intercepting all calls from ``<a>`` to prevent a reload of the window. This means we have to dispatch a ``hashchange`` event manually. The question is, when do we do that? Every time the URL changes or only when the hash changes?

Can I ask what you need the event for? Knowing this, might provide some context to a solution.

**Comment by Gibbu** [comment]
I'm pretty much doing what Svelte does with their [docs](https://svelte.dev/docs). If you scroll down the nav will disappear and won't appear until you scroll up. At the moment when a user clicks a anchor and is above the nav will appear. It's not overly needed

**Comment by jakobrosenberg** [comment]
That's not done with the hashchange, but the scroll position of the main content.

I've done a very simple example of it here.
https://svelte.dev/repl/051cd352ce284d15b55c91c8b30fa32f?version=3.16.7

There are a few Svelte plugins intended for this, which can track the direction of your scrolling and show the navigation once you start scrolling up.
