### ISSUE TITLE
Install of 1.0.1-26  via npm has multiple failures on windows <-> unix related issues

### ISSUE THREAD

**Issue by nmcfarl** [roxiness/routify#58]
I found that in order to install` npm i -d @sveltech/routify@next` on my **Mac** I had to do a
`npm i --no-bin-links  @sveltech/routify@next` and manually link npm-cli.js to routify as I was getting this error with the wrong kinda slash for unix: 

> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path /Users/me/repos/testapp/node_modules/@sveltech/routify/plugins\cli.js
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/me/repos/testapp/node_modules/@sveltech/routify/plugins\cli.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

After that step I ended up doing a 

` dos2unix node_modules/@sveltech/routify/plugins/cli.js`

because of this error

> env: node\r: No such file or directory

**Comment by jakobrosenberg** [comment]
Thanks for filing this @nmcfarl 

@rixo what do you think? Is this a simple chmod or line ending issue?

**Comment by jakobrosenberg** [comment]
End of line sequence has been changed to ``LF``.

Would you check if this fixes the problem?

**Comment by nmcfarl** [comment]
This solves the second problem -- I can now run cli.js ˚ once linked routify.  Which is awesome!

------------

But I still am getting the wrong slash error below , so I have to install with --no-bin-links 

> npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/me/repos/testapp/node_modules/@sveltech/routify/plugins\cli.js'

**Comment by jakobrosenberg** [comment]
Great that we're a bit further!

I have no idea where the backslash is coming from. This is from  ``package.json``:
```javascript
  "bin": {
    "routify": "./plugins/cli.js"
  },
```

@rixo any ideas what could cause the backslash error?

**Comment by jakobrosenberg** [comment]
Closing this for now. Will reopen if anyone has anything to add to the issue.
