### ISSUE TITLE
Routes is not defined

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#59]
When upgrading from 1.0.1-20 to 1.0.1-27

Error:

`Uncaught ReferenceError: routes is not defined`

```
<!-- src/App.svelte -->
<script>
  import { Router } from "@sveltech/routify";
  import { routes } from "@sveltech/routify/tmp/routes";
</script>

<Router {routes} />
```

Code is exactly like in the reference template: https://github.com/sveltech/routify-starter/blob/master/src/App.svelte

Did the implementation logic change?

**Comment by Wolfr** [comment]
Related, I switched to `1.0.1-25` and locally this worked, but if I deploy to now.sh, it shows this routes error as well.

https://kanamaster.wolfr.now.sh/

**Comment by jakobrosenberg** [comment]
Either the import path is incorrect or the routes did not generate. Did you see any errors in the console?

**Comment by jakobrosenberg** [comment]
I assume this was sorted on Discord. If not, feel free to reopen.
