### ISSUE TITLE
Only First Component is Being Rendered

### ISSUE THREAD

**Issue by dhkatz** [roxiness/routify#6]
For whatever reason, only the first component passed to the Router is being displayed. I'm a little confused because obviously this isn't a problem with the example site you have up.

For example, the `Router` receives the `[Layout, Index]` components but then the internal `Route` component used by `Router` only renders `Layout`.

I did a bit of investigating but I'm really not sure what's happening.

Inside of `Route.svelte` was the only potential problem area I found

https://github.com/jakobrosenberg/svelte-filerouter/blob/0c46e3f9c8cb6d60ceeb020724550b3ba419d9d6/src/Route.svelte#L11-L12

https://github.com/jakobrosenberg/svelte-filerouter/blob/0c46e3f9c8cb6d60ceeb020724550b3ba419d9d6/src/Route.svelte#L20-L24

The `component` prop seems to only ever be the first component in the `components` array and never changes.

If I get rid of the `component` prop and instead add the following the the markup it seems to render all components properly:

```html
{#each components as component}
  <svelte:component this={component} {...props} let:scoped={layoutScope}>
    {#if components.length && demandObject(layoutScope)}
      <svelte:self {...childProps} {layoutScope} />
    {/if}
  </svelte:component>
{/each}
```

**Comment by jakobrosenberg** [comment]
Hi @dhkatz that sounds very strange. By using {#each} you're rendering nested svelte files as siblings rather than as children.

Can I see a sample project or at least some of your file structure? Ie. 
```
src/
  App.svelte
  pages/
    _layout.svelte
    index.svelte 
```


Also, did you remember the ``<slot>`` element in _layout.svelte files?
