### ISSUE TITLE
Error after renamed folder `pages` to `routes`

### ISSUE THREAD

**Issue by hyuzea** [roxiness/routify#61]
seem two lines of  pages paths source logged but the build work properly.
Is it a warning log? it might shouldn't no red colored text ?
  
![image](https://user-images.githubusercontent.com/3823496/72223751-fc2df380-35a4-11ea-8bb0-0244de579bda.png)

**Comment by jakobrosenberg** [comment]
That's an error log. Any chance you've got two implementations? One in package.json and on in Rollup?

**Comment by hyuzea** [comment]
just added line in rollup
```
     routify({
      dynamicImport: true,
      pages: './src/routes',
    }),
```

**Comment by jakobrosenberg** [comment]
You need to remove one of the implementations or you will have two instances running simultaneously.

You should not run ``run-p watch:routify watch:rollup`` if you're already running Routify through Rollup.

**Comment by hyuzea** [comment]
Yes thankyou Mr! It help me
