### ISSUE TITLE
Support for Cordova

### ISSUE THREAD

**Issue by sido420** [roxiness/routify#63]
Apologies in advance if I am asking at the wrong place.

I was planning to try svelte+sapper for my new app(s). However, I'd like to use same codebase for both web app and Cordova based app for the same project. 

Is this something supported by Sapper.js itself or I have to use a project like `routify` to make use of the same codebase for SSR and Cordova app?

**Comment by jakobrosenberg** [comment]
It sounds like you would have to use both Sapper and Routify for what you want to achieve.

Theoretically it should be possible to use the same codebase for both Routify and Sapper, but it would probably require a bit of wiring.

Are you making apps that would benefit from SSR?

**Comment by sido420** [comment]
>> Are you making apps that would benefit from SSR?
Yes. There may be some public pages for search engines.

I will test routify and Sapper and find out if I can make them work together easily or not. 

In the meantime, if you can write some instructions here (or a doc page) on how to use both simultaneously that would be great.

**Comment by jakobrosenberg** [comment]
We're still behind on documenting new features, concepts, helpers and guides. Maintaining documentation on integration with a moving target, of which we have no control, is out of the current scope.

That said, here's what I would do.

1. Create a routify project with ``npx @sveltech/routify@next init``
2. Update ``package.json``. Example: ``watch:routify": "routify -p path/to/sappers/routes"``
3. Symlink or copy a dir in the public dirs and use this dir for all static content.

Notes:
A) ``segment`` has no effect in Routify.
B) Routify is a SPA. Anything SSR related will have no effect in Routify.

**Important**
Maintaining routes for two different routers is not something we encourage. Even if possible. Instead please consider
- Google crawls and indexes SPAs now.
- certain static content can be served from the ``public`` folder.
- static site generation is on the roadmap for Routify
