### ISSUE TITLE
onMount being called twice

### ISSUE THREAD

**Issue by fabiohvp** [roxiness/routify#66]
After the first time you enter a page onMount always is fired twice.

Simple test scenario:
src/page/index.svelte   (add link to /about)
src/page/about.svelte   (add link to index and console.log something inside onMount)

go to your index and click /about link, then click /index link and now everytime you enter /about again onMount will be fired twice

**Comment by jakobrosenberg** [comment]
I squashed a related bug today. Pushing the release now. Should be up in a few minutes.

Please let me know if this solves the double mount.

**Comment by fabiohvp** [comment]
Fixed!
thanks
