### ISSUE TITLE
Deploy to now fails with "could not resolve '../tmp/config'" error

### ISSUE THREAD

**Issue by richcorbs** [roxiness/routify#67]
My app runs locally but deploying to "now" fails with `Could not resolve '../tmp/config'`.

![Screen Shot 2020-01-20 at 2 34 35 PM](https://user-images.githubusercontent.com/437167/72759211-3e04fe00-3b92-11ea-9429-a7d83abdff45.png)

**Comment by richcorbs** [comment]
My error. I wasn't deploying properly.

**Comment by jakobrosenberg** [comment]
Happy you got it solved. Can I ask what was wrong? Could be handy if I see a similar post.

**Comment by richcorbs** [comment]
I hadn't run `npm run build` and I wasn't deploying from within the `public` directory.

The `buildnow` script in `package.json` from the starter app was what moved me in the right direction.
