### ISSUE TITLE
Print out the full URL for open graph tags

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#68]
If I wanted to print out the full current URL, how would I do that?

`<meta property="og:url" content="CURRENT_URL_HERE" />`

**Comment by jakobrosenberg** [comment]
A combination of ``window.location.href`` and ``<svelte:head>`` might do the trick.

https://svelte.dev/tutorial/svelte-head

I have to admit I haven't experimented with this at all.

**Comment by Wolfr** [comment]
I will :)

Verstuurd vanaf mijn iPhone

**Comment by Wolfr** [comment]
I did that, and that seems to work!
