### ISSUE TITLE
Match Exact Using isActive Helper 

### ISSUE THREAD

**Issue by joelhickok** [roxiness/routify#70]
It would be useful if the `isActive` helper facilitated exact matches of the path argument, as well as base path matches.  One way to do this could be with some other property on the `<a>` element, or another way is to let the developer use a handler function with the path to return their own result.  I'm trying to do this using the helper, but for now am forced to use my own function.

I am trying to match a nest result for active classes and my base path is always active.

Example:
```js
// applies the class all the time, even for nested-routes
class:active={$isActive(`/edit/${id}`)} 

// applies the class on address route and base route
class:active={$isActive(`/edit/${id}/address`)}
```

I noticed this dead-end code block in helpers.js with the `// ABSOLUTE PATH` comment:
```js
export function _url(context, route) {
  return function url(path, params, preserveIndex) {
    path = path || './'

    if (!preserveIndex) path = path.replace(/index$/, '')

    if (path.match(/^\.\.?\//)) {
      //RELATIVE PATH
      // get component's dir
      // let dir = context.path.replace(/[^\/]+$/, '')
      let dir = context.path
      // traverse through parents if needed
      const traverse = path.match(/\.\.\//g) || []
      traverse.forEach(() => {
        dir = dir.replace(/\/[^\/]+\/?$/, '')
      })

      // strip leading periods and slashes
      path = path.replace(/^[\.\/]+/, '')
      dir = dir.replace(/\/$/, '') + '/'
      path = dir + path
    } else if (path.match(/^\//)) {
      // ABSOLUTE PATH
        console.log('You reached the absolute path block.')
    }

    params = Object.assign({}, route.params, context.params, params)
    for (const [key, value] of Object.entries(params)) {
      path = path.replace(`:${key}`, value)
    }
    return path
  }
}
```

**Comment by jakobrosenberg** [comment]
Without seeing your file structure, I'm guessing this is what you're looking for.

```javascript
$isActive("./index") //only returns true for "/current/path" and "/current/path/index"
$isActive("./") //returns true for "/current/path" and all its descendants.
```

Checking against ``./index`` makes sure you're not getting any recursive matches. It also works if there's no ``/index`` in the URL as it's checking against the current page file and not the URL.

Regarding having ``$isActive`` return true for two different routes, you could do that with:
``class:active={$isActive(routeA) || $isActive(routeB)}``

**Comment by joelhickok** [comment]
Thank you!  I did not realize referencing index would produce that result... `isActive` seems to work fine now.  

Not sure if the docs reflect this, but might be useful for new adopters of the library in the future to see a couple more examples of what would work and would *not* work.

I am enjoying your library immensely over other Svelte router options I've tried out.  Thank you for your work!

**Comment by jakobrosenberg** [comment]
@joelhickok I know. I'm only getting further and further behind on the docs at the current pace. 😂
