### ISSUE TITLE
Routify-starter

### ISSUE THREAD

**Issue by jakobrosenberg** [roxiness/routify#77]
Goals
------
1. (on default build) Apps should have static page generation with SSR fallback. **done**
2. (on default build) On first visit, apps should be cached in the background. **wip**
3. (on default build) On subsequent visits, apps should be served from browser cache. **wip** 
2. Anyone can deploy a fullfledged SSR/prerendered app to netlify with ``npx @sveltech/routify init`` -> ``npm run deploy netlify`` **done**
3. File structure should be semantic and easy to grasp for both novices and experts.

## Ideas for file structure
<details>
  <summary>Flat</summary>

  > ## Flat
  > - **app/** *(src code for client)*
  > - **assets/** *(__app.html, images, css etc)*
  > - **server/** *(src code for server)*
  > - **dist/** *(generated app)*
  > - **deployments/** *(scripts for deploying to netlify etc.)*
</details>

<details>
  <summary>Nested</summary>

> ## Nested
> - **app/** *(src code for client)*
>   - **assets/** *(__app.html, images, css etc)*
> - **server/** *(src code for server)*
>   - **dist/** *(generated app)*
>   - **deployments/** *(scripts for deploying to netlify etc.)*
</details>

<details>
  <summary>Nested exploded</summary>

> ## Nested (exploded)
> - **app/** *(src code for client)*
>   - **assets/** *(__app.html, images, css etc)*
>   - **pages/** 
>   - **components/** 
>   - **main.js** 
> - **server/** *(src code for server)*
>   - **dist/** *(generated app)*
>   - **deployments/** *(scripts for deploying to netlify etc.)*
>     - **netlify/**
</details>

Thoughts
------------
1. A server folder can be confusing and even though it's use is optional, it could give the impression that this is a starter template for a server.
2. Abstracting the server and scripts to npm modules makes it harder to reason about and impossible to modify
3. The server folder could be built through an npm script and thus avoid cluttering till you actually need it
  a. This would require the server to depend on a dist folder outside its own folder. Could this be an issue/confusing?
  b. Risk of overwriting?
4. Nested folders feels like a clean separation of concern and their internal structure feels right as well.

Any feedback would be very appreciated.

**Comment by Wolfr** [comment]
My 2 cents - anything that can keep it closer to the default svelte-template folder structure would help.

**Comment by rixo** [comment]
I strongly prefer flat, because it makes more obvious the different functions of each directory.

I especially dislike `server/dist` because it makes me wonder if there can be other generated files folders hidden in some deeper directory.

Also, I think that deployment and server are 2 distinct concerns, so it makes sense to have a directory for deployment at root level. I think I would call the folder `deploy` though. More punchy!

> a. This would require the server to depend on a dist folder outside its own folder. Could this be an issue/confusing?

I don't think so. It's standard practice for the server to serve static content from an "outside" directory, typically `public` or `static`.

> A server folder can be confusing and even though it's use is optional, it could give the impression that this is a starter template for a server.

Yes.

> The server folder could be built through an npm script and thus avoid cluttering till you actually need it

Seems complicated. Maybe 2 templates, or 2 branches of the starter template? I like 2 branches, but I guess some people might be confused by this.

What about something like `npx routify init-ssr` or something, that would create the `server` directory and update the npm scripts?

**Comment by jakobrosenberg** [comment]
@Wolfr I agree. Being a minimally modified Svelte template was always a goal and I still see the value of it. The solution might be, like @rixo suggested, to create two repos.

@rixo. Yes, the ``dist`` folder doesn't belong anywhere but the root. That's what I ended up with in the split branch of the starter as well. https://github.com/sveltech/routify-starter/blob/split/rollup.config.js

I think SSR should be doable, even without a server folder. A bigger boilerplate/starter would be for those asking how to do auth as well as handle async data.

Should we just create two boilerplates?
**Minimal** based on the default Svelte template and 
**Basic** Small express backend with two endpoints ``login => (req, res) => req.body.user === 'admin`` and ``posts => ...`` or something similar.

**Comment by Wolfr** [comment]
Can agree with @rixo to prefer flat file structures.

About what the folder for deploys is called, `dist` or `deploy` works for me (not a weird name like in Sapper: `__sapper__/export`). I prefer `dist` because it's that way in many of my other projects. But deploy is good as well.

@jakobrosenberg My comment on your idea for "Basic" (with endpoints) is that when I would want to use a setup that has SSR I don't necessarily want to make an "app" as in something with a login.

So if I need the Basic template to get SSR but I always need to clean out app-like parts, it will work against what I want to achieve. I'll share a private link in Discord to give you some more context. 

Maintaining 2 templates sounds like a chore (for the Routify maintainers, you guys) and also makes it harder to explain to new people how to use Routify.

Please take my comments with a grain of salt, I am new to "SSR" discussions.

**Comment by jakobrosenberg** [comment]
@Wolfr The minimal template should be able to handle SSR as well. There will be a few options in the deploy folder which you can call like so ``npm run deploy netlify``

I've even contemplated simply moving ``netlify.toml`` to the root folder, but once you deploy a project it creates a ``.netlify`` folder and on top of that it also needs a functions folder. The functions folder could be stored in the @sveltech/routify module. That would however lose the transparency of what's going on.

As for the Basic template, that is for the questions I get about how to handle authentication and fetching data. ``Basic`` might not be the best name however.

**Comment by Wolfr** [comment]
What about `Authenticated-app` template?

As for Netlify, just like Now.sh, those are easy to work with if you need a fast deploy, but I am thinking about how intertwined instructions to work with those should be with this project.

Providing instructions on how to deploy with those or even providing related files in the basic templates seems to me to be sort of out of the scope of a router imo, once you have a distributable package, the distribution is the same as any other Svelte project. The fact you have to redirect to index.html is general SPA knowledge.

And there are many hosts out there so I don't see the logic in “promoting” one or the other.  That's just my 2 cents. The reasoning behind this is that I see many junior devs defaulting to Netlify and when they have to do a real deployment, or run into problems, now they have no idea how their server works.

**Comment by jakobrosenberg** [comment]
I think we're ditching the custom server aspect of it. At least for now.

As for netlify, it simply boils down to what works. My first attempts with SSR and one click deployments were with Now, AWS and Express. They all had their kinks. Netlify just worked. I'd love to have a few CLI deployment options which people can either use, extend or use as inspiration.

That said, I'd hate to force training wheels where they aren't required, but I don't think that's what we're doing by extending the CLI with an optional deployment command (even if it can be called through ``package.json``)

**Comment by jakobrosenberg** [comment]
## Thoughts on deployments

### shortcomings
**Netlify** Static files randomly disappear when 404 redirect is enabled. (will hopefully be solved by the Netlify team.)

**Now** Requires a specific file structure. (``./package.json`` with a build script (even a dummy script) and an ``./api`` and ``./public`` folder, for lambda functions and static content.)

### Challenge
The question is, how should we orchestrate the structure? Dumping now.json in the project root is not an option as it needs two adjacent directories, one of which we already use for source.


### Options
<details>
<Summary>A (Include in template)</Summary>

Rename the current ``./public`` to ``./template``
```
template/
  public/
  api/
  now.json
  netlify.toml
  package.json

dist/ (copy of the template merged with the generated app and prerendered pages)
  api/
  public/
  netlify.toml
  now.json
  package.json
```

**Pros**
 - Falls in line with what we're already doing. We just move one step down the tree to include build scripts and lambda functions in the template.

**Cons**
- Deployment scripts can't be run from where they're written. Instead they have to be executed in the dist folder.
</details>

----------

<details>
<Summary>B (put in dist)</Summary>

```
dist/
  public/ (generated)
  api/
  netlify.toml
  now.json
  package.json
```
**Pros**
Deployment scripts can be run from where they're written.
**Cons**
Puts template in a dist folder.
</details>

----------

<details>
<Summary>C (Same, but rename dist -> template)</Summary>

```
template/
  public/ (generated)
  api/
  netlify.toml
  now.json
  package.json
```
**Pros**
Deployment scripts can be run from where they're written.
**Cons**
Hides dist in a template.
</details>

----------

<details>
<Summary>D (Abstract deployments)</Summary>


**Pros**
It's clean and out of the way
**Cons**
Hard to reason about
Not easy to customize
</details>


----------

<details>
<Summary>E (create a separate deployment folder)</Summary>


**Pros**
Has some semantic value
**Cons**
Spreads out the build steps
Clutters root folder
</details>


**Note**
We could end up in a situation where we have different deployment services with unique requirements for file structure. If this happens, we have to pick favorites or abstract the deployment configs into their own folders. Ie. ``deploy/netlify`` (seems familiar?)

**Comment by Wolfr** [comment]
You asked but I am not familiar enough with Netlify and Now to give thoughts on this.

**Comment by jakobrosenberg** [comment]
@Wolfr Sorry, I didn't really pose a clear question in my last post. I meant to ask if there were any file structures you felt strongly for or against from an aesthetic point of view. (Technically the structure makes little difference)

**A**
``` 
dist/
src/
template/
  public/  
```
**E**
```
dist/
src/
public/
deploy/
```

I was leaning towards A, but I think it's gonna be E. It keeps the default Svelte template structure intact and maintains a clear separation between ``source``, ``output``, ``statics`` and ``deployments``. _(The name ``deploy`` might semantically narrow down what we and the user can use this folder for. Would something like ``scripts``, ``actions`` or ``.routify`` be better?)_

While digressing on semantics, ``public`` is conventionally the exposed folder, ie. the one you serve. In our case it's strictly for static files. If we rename it to ``static`` we could avoid a lot of confusion. Not just from those coming from the Svelte template, but for anyone who assumes that the public folder is the exposed folder.
