### ISSUE TITLE
A route with a number as file name doesn't work

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#80]
If you make routes like 1.svelte, 2.svelte, 3.svelte in `/pages`, they do not render content.

**Comment by jakobrosenberg** [comment]
I just tried 3.svelte. Worked instantly. Could you try rename them to see if it's actually the number keeping them from being rendered?

**Comment by Wolfr** [comment]
I was working on anther project last night, now I tried to recreate this bug in an existing project (Kana Master):

* Make 3.svelte in the root of pages: ✓ works
* Make a folder called `x` and put 3.svelte in it: ✓ works
* Make a folder called `x` and put 1.svelte, 2.svelte, 3.svelte in it: ✓ works
* Make a folder called `x`, put a folder called `x` in it and put 1.svelte, 2.svelte, 3.svelte in it:: ✓ works
  * But it has to be noted that when you go to `x/x`, you get the route that belongs to, in the case of this app, [language]/[detail.svelte], whereas one would except it would return a 404.

So we can close this, but I will log a new bug around this last thing.
