### ISSUE TITLE
[npm i -d ]ENOENT: no such file or directory, chmod [Error]

### ISSUE THREAD

**Issue by dewott-technologies** [roxiness/routify#81]
I've tried to install the component via the npm but got this error: 

ENOENT: no such file or directory, chmod '/Users/macbook/Desktop/Software/DEV/Front End/Tools/testing-svelte/nested-empty-pages/node_modules/@sveltech/routify/plugins\cli.js'

Any help ?

**Comment by jakobrosenberg** [comment]
@dewott-technologies Are you on Mac or Linux?

@rixo any ideas here?

**Comment by rixo** [comment]
It is a Mac. I thought it was the final backslash in `..\cli.js` that it chokes on. You know where it might come from?

**Comment by jakobrosenberg** [comment]
Npm has a habit of adding a backslash when it resolves paths on Windows.

Why, I don't know, because this is the definition from package.json
```json
"bin": {
    "routify": "./plugins/cli.js"
  },
```

Could you share the ``/Users/macbook/Desktop/Software/DEV/Front End/Tools/testing-svelte/nested-empty-pages/node_modules/@sveltech/routify/package.json`` file?

**Comment by rixo** [comment]
@dewott-technologies And can you share the precise npm install command that you ran, please?

**Comment by dewott-technologies** [comment]
> @dewott-technologies Are you on Mac or Linux?
> 
> @rixo any ideas here?

I'm on mac

**Comment by dewott-technologies** [comment]
> Npm has a habit of adding a backslash when it resolves paths on Windows.
> 
> Why, I don't know, because this is the definition from package.json
> 
> ```json
> "bin": {
>     "routify": "./plugins/cli.js"
>   },
> ```
> 
> Could you share the `/Users/macbook/Desktop/Software/DEV/Front End/Tools/testing-svelte/nested-empty-pages/node_modules/@sveltech/routify/package.json` file?

it doesn't install it .... 

From error log: '' -> if desired i could attach the log file here
891 warn TODO@0.0.1 No repository field.
892 warn TODO@0.0.1 No license field.
893 verbose stack Error: ENOENT: no such file or directory, chmod '/Users/macbook/Desktop/Software/DEV/FrontEnd/Tools/testing-svelte/nested-empty-pages/node_modules/@sveltech/routify/plugins\cli.js'
894 verbose cwd /Users/macbook/Desktop/Software/DEV/FrontEnd/Tools/testing-svelte/nested-empty-pages
895 verbose Darwin 19.2.0
896 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@sveltech/routify@next"
897 verbose node v12.13.0
898 verbose npm  v6.12.0
899 error code ENOENT
900 error syscall chmod
901 error path /Users/macbook/Desktop/Software/DEV/FrontEnd/Tools/testing-svelte/nested-empty-pages/node_modules/@sveltech/routify/plugins\cli.js
902 error errno -2
903 error enoent ENOENT: no such file or directory, chmod '/Users/macbook/Desktop/Software/DEV/FrontEnd/Tools/testing-svelte/nested-empty-pages/node_modules/@sveltech/routify/plugins\cli.js'
904 error enoent This is related to npm not being able to find a file.
905 verbose exit [ -2, true ] ''

**Comment by dewott-technologies** [comment]
something i want to share also is that this project its build using svelte and sapper with webpack. 
I've also tried to remove the space at [Front End]: "/Users/macbook/Desktop/Software/DEV/Front End/Tools/...."

**Comment by dewott-technologies** [comment]
> @dewott-technologies And can you share the precise npm install command that you ran, please?

1. npx degit "sveltejs/sapper-template#rollup"
2. npm i
3. npm i @sveltech/routify@next && sudo npm install --save @sveltech/routify@next
4. npm audit

also tried adding a .npmignore file as was suggested in this post: https://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod

**Comment by dewott-technologies** [comment]
> /plugins\cli.js

I'm not sure why when installing the path becomes "\" instead of "/" [/plugins\cli.js] I think this is the issue, it creates a wrong path ....  or maybe Im wrong

Any ideas why ?

**Comment by jakobrosenberg** [comment]
Could you try run ``npx @sveltech/routify@next init`` in an empty folder and see if it works? It might narrow down what the issue could be.

**Comment by quantuminformation** [comment]
same issue found

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/nikos/WebstormProjects/svelte-fullstack-starter/node_modules/@sveltech/routify/plugins\cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/nikos/WebstormProjects/svelte-fullstack-starter/node_modules/@sveltech/routify/plugins\cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by quantuminformation** [comment]
tried to run `npm i -D @sveltech/routify` it here

https://github.com/QuantumInformation/svelte-fullstack-starter

**Comment by jakobrosenberg** [comment]
Do you get the same result with ``npx @sveltech/routify init``?
