### ISSUE TITLE
Server routes

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#84]
Is there an opinion on implementing something lke Server Routes (See [Sapper docs](https://sapper.svelte.dev/docs#Server_routes)) in Routify?

I was looking at some interesting source code (see this blog [post](https://lacourt.dev/2019/06/29)) to check out how I could generate an RSS feed and XML sitemap, some features I would like if I would run a full website using Routify.

**Comment by jakobrosenberg** [comment]
I'd like to support the functionality, but I don't want Routify to be married to a server.

If we do it, it should be a separate module which you can add to your project, by importing it to ``src/main.js``. Kind of like how you add Routify to ``App.svelte``.

**Comment by jakobrosenberg** [comment]
Closing this. We can reopen it later if it becomes relevant.
