### ISSUE TITLE
tutorial video

### ISSUE THREAD

**Issue by jkdoshi** [roxiness/routify#88]
I see that Routify perfectly solves the routing problem for Svelte using Svelte's own "build-time" philosophy. It's the best way to do routing if one can't use Sapper for some reason.

I have publish a 45 minute tutorial video screencast on Routify [here](https://www.youtube.com/watch?v=AGLUJlOC6f0)

Would it be appropriate to include a link to it in README.md on GitHub and/or routify.now.sh documentation?

**Comment by jakobrosenberg** [comment]
Hi @jkdoshi That sounds like a great idea. I'm on holidays, so I might not have time till next week.

Btw, if you'd like to make a part 2, the new routify starter template is configured for SSR, prerendering, decorators, transitions etc. I'll be happy to help if you have questions.

**Comment by jkdoshi** [comment]
@jakobrosenberg - Thanks a lot for including my video in the documentation (upon your return from vacation).

And yes, I'll definitely do part 2 of my video. I will learn these features you mentioned, and try to teach them in my video.

I do have some questions:

1. Is it possible to generate a service-worker for offline and caching from Routify?
1. Is it possible to tweak/alter routes using JS code at runtime? This would be helpful for adding aliases or general route rewriting.
1. I know there's a beforeUrlChange hook/callback. Are there hooks/callbacks for *after* Url Change but before route component is mounted? I am talking about the "preload" method of Sapper.

**Comment by jakobrosenberg** [comment]
1. We're still working on this. You can however do this manually by iterating the imported routes.

2. That's possible. In fact it's always been a goal, but we have no documentation on it.

3. AFAIR preload is a solution for handling async data in Sapper. Normally SSR serves the pages instantly and doesn't wait for any async data to be loaded. To fix this, we have introduced ``$ready``. Once ``$ready`` is present in a component, the page won't be rendered till ``$ready()`` is called.

**Comment by jkdoshi** [comment]
@jakobrosenberg hope you enjoyed the holiday. I read up on $ready as well as saw the aliasing example in your starter template. Still trying to figure out how to generate service worker.

In the meanwhile, can you include a link to the video tutorial (https://www.youtube.com/watch?v=AGLUJlOC6f0) in the README and the documentation at routify.now.sh?

**Comment by jakobrosenberg** [comment]
Hi @jkdoshi, sorry I haven't gotten around to it yet. It's still on the list. Service workers have yet to be implemented on our side, so that's something you'll have to do manually for now.

**Comment by jkdoshi** [comment]
@jakobrosenberg can I help in any way? Service workers are the last remaining piece after which Routify can become a real alternative to Sapper. If you give me some directions, may be I can implement it.

**Comment by jakobrosenberg** [comment]
@jkdoshi we'll take all the help we can get.

The service worker basically has to accept a list of URL objects and cache them. An URL object could look like this
```javascript
{
  url: '/index-2b0521e9.js',
  priority: 2,
  duration: 3600,
  provide: 'urlWithCacheFallback'
}
```

**priority** would be the order of which to cache the URLs
**provide** would take the following enums: 
- cache
- cacheThenUrl
- urlWithCacheFallback

I don't know if this is something you're up for. If you have questions, feel free to post them here or come join us on discord. 😀 https://discord.gg/wmHFxDA

@rixo @Wolfr any thoughts on service workers?

**Comment by Wolfr** [comment]
No experience with this but as we were experimenting with PWA’s, support sounds exciting!

Verstuurd vanaf mijn iPhone

**Comment by jakobrosenberg** [comment]
This was added to the README a while back.
