### ISSUE TITLE
Feature request: route aliases

### ISSUE THREAD

**Issue by Perturbatio** [roxiness/routify#89]
It would be good to be able to alias your routes to a keyed string so that you can generate a url to your page component regardless of where it sits relative to your current page.

I imagine it would achieve the same type of functionality as Laravel's names routes:
https://laravel.com/docs/6.x/routing#named-routes

This means you can refactor the route urls (i.e. move your page components around wherever you want) and refer to them by their alias when generating the links.

an example *might* be something like:

```html
<script>
import {pageAlias} from '@sveltech/routify'

pageAlias(this, 'users.index')
</script>
```

```html
<script>
import {urlAlias} from '@sveltech/routify'
</script>
<a href="$urlAlias('users.index')">Users</a>
```

**Comment by jakobrosenberg** [comment]
The old Svelte-filerouter had this feature, but we removed it for Routify as the alias was autogenerated and thus could result in conflicting aliases.

A solution could be

``about.svelte``
```html
<!-- routify-options name="about" -->
```

``other-file.svelte``
```html
<script>
  import { url } from '@sveltech/routify'
</script>

<a href={ $url('about') }>About</a>
```

**Comment by Perturbatio** [comment]
That seems reasonable so long as there's no confusion to the user when generating the url i.e. a page called about in two locations, how do you link to the correct one?

*maybe* something like 
```html
<a href={ $url('name:about') }>About</a>
``` 
?

I sort of prefer the word alias because it's clearer (to me) that I mean the aliased route rather than the page named 'about'

**Comment by jakobrosenberg** [comment]
While there may be duplicate filenames in a project, all aliases should be unique.

Currently the $url helper only resolves relative paths, meaning a non slash/period prefixed path could be handled as a name. (this is what svelte-filerouter did)

**Comment by Perturbatio** [comment]
I get that, what I meant was if I have a project which has two pages called 'about' and one is aliased to 'about' and the other is not, if I try to create a relative link to the unaliased page from the same level, which one will be linked?

```
pages
    about (aliased)
    system
        about (unaliased)
        configuration (links to 'about' using $url('about'))
```
about is obviously not the best example for a page name, but it's not uncommon to have multiple pages/routes named the same thing in different locations.

obviously you can get around this but doing some nice namespacing when naming routes but it might produce unexpected behaviour for some developers

**Comment by jakobrosenberg** [comment]
>  if I try to create a relative link to the unaliased page from the same level, which one will be linked?

In your example you're using ``$url('about')``. This would be a named path rather than a relative path.

If you used a relative path, ``$url("../about")``, the unaliased page would be linked.

**Comment by Perturbatio** [comment]
I get that intention, however *currently* routify allows me to use `$url('about')` to link to what /i presume you intend to be `$url('./about')` this means that anyone currently just using the string without the './' prefix will need to update these links.

Not a major issue, but it does change existing functionality.

**Comment by jakobrosenberg** [comment]
The ``$url`` helper currently resolves relative and absolute paths. It may not throw an error if you use it with a named path, but in this case it just won't do anything and its use thus redundant. 

In other words, there isn't really any existing functionality to break. Even if we add named paths, we wouldn't have to break the current nothing-happens-functionality if the named path doesn't exist.

**Comment by Perturbatio** [comment]
ok, I didn't realise you weren't supposed to use the $url helper without a relative or absolute prefix i.e. I've been doing 'index' instead if './index' and it's been doing relative urls in the same level for me just fine, it's easy for me to fix my code, I'm just concerned (only a little :) ) that some users may have larger projects where this has been done.

It's not really an issue for me if you adopt the policy of all urls having a path prefix.

**Comment by jakobrosenberg** [comment]
Are the relative paths you're getting relative to the current URL or to the filestructure? If relative to the current URL, then that's just the normal browser behavior and $url would have no effect on the provided path.

I added named paths to Routify, but the documentation has not been updated yet.

To use a named(aliased) path, insert this in your page.
``<!-- routify:option name="my-page-name" -->``

To link to the page, use ``$url('my-page-name')``

If a page by the specified name doesn't exist, the string will simply be returned.

**Comment by Perturbatio** [comment]
I think I'd have to experiment with the app to confirm what I did, but like I said, it's not a big deal for me to rework since I've only done a few routes thus far.

Thanks for implementing the route names btw :)

I'll be using that very soon.

**Comment by jakobrosenberg** [comment]
Happy to help 🙂

By the way, how would you feel about named modules? Say you had the following file structure:
```
index.svelte
blog.svelte
shop/
  products/
    layout.svelte //represents the folder and has the name "products"
    index.svelte
    [id].svelte
```

Then you could do something like ``$url('products/:id', { id })``

**Comment by Perturbatio** [comment]
That's pretty much the structure I'm using anyway so looks fine :)

  | sites
 -- | [siteId].svelte
 -- | index.svelte
  | _fallback.svelte
  | _layout.svelte
  | index.svelte
  | logout.svelte

When you say `//represents the folder and has the name "products"` 
do you mean it auto-inherits the name from the parent folder as an implicit name?, or do you explicitly declare ` <!-- routify:option name="products" -->` in the .svelte file?

**Comment by jakobrosenberg** [comment]
Sorry, that was a bit ambiguous. You specify the name in the .svelte file.

**Comment by Perturbatio** [comment]
This sounds potentially useful to me.

If we were to do a full entity manager here, would I be able to do something like the following?:
```
shop/
  products/
    layout.svelte //represents the folder and has the name "products"
    index.svelte
    [id].svelte
    add.svelte
    [id].edit.svelte // $url('products/:id/edit', { id })
    [id].some_action.svelte // $url('products/:id/some_action', { id })
```

**Comment by jakobrosenberg** [comment]
You would need to use [id] as a folder.

```
shop/
  products/
    layout.svelte //represents the folder and has the name "products"
    index.svelte
    add.svelte
    [id]/
      index.svelte
      edit.svelte // $url('products/:id/edit', { id })
      some_action.svelte // $url('products/:id/some_action', { id })
```

**Comment by Perturbatio** [comment]
fair enough, that'd work (might be a useful example for the docs)

**Comment by nowylie** [comment]
@jakobrosenberg is this *named modules* functionality available now? I've been looking to jump from Vue to Svelte for a project and using named routes in Vue can become extremely verbose with a routing structure like this. I think the functionality you propose would make life **significantly** easier.

**Comment by jakobrosenberg** [comment]
Hi @nowylie, yes it is available now.

It's mentioned in the documentation for the $url helper, though I admit it's not very obvious.
https://routify.dev/docs/helpers
