### ISSUE TITLE
request@2.88.2: request has been deprecated

### ISSUE THREAD

**Issue by Valexr** [roxiness/routify#90]
~ yarn upgrade
warning @sveltech/routify > @sveltech/ssr > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by jakobrosenberg** [comment]
Should this issue be posted in the JSDOM repo?

**Comment by rixo** [comment]
@jakobrosenberg Yup. Plus this one should probably be transferred to `@sveltech/ssr`.

**Comment by jakobrosenberg** [comment]
As there's nothing I can do about the dependencies of JSDOM, I'm closing this.
