### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#91]
Is Routify MIT? It says it is ISC in package.json, but is it because this is the default?

On the new site we mention MIT, but what is the license really?

**Comment by rixo** [comment]
What should it be? Any experience with this?

**Comment by Wolfr** [comment]
I prefer MIT for everything, which is quite short and not so complicated. Basically do with it what you want but we are not responsible.

One would except a LICENSE.md in the root of the repo, and a clear mention of the license in the README. 

https://opensource.org/licenses/MIT

**Comment by rixo** [comment]
> The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.
https://choosealicense.com/licenses/isc/

So I would keep ISC, personally (and will probably use this in the future for my own projects). But apparently it doesn't change a thing except the length of the text.

But yeah, we need to add a LICENCE (typically not markdown) file and a mention in the README. And since we're not sure which one it will be, @jakobrosenberg will have to do it himself!

Found another interesting article on how to write the copyright notice: https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/

**Comment by jakobrosenberg** [comment]
Ugh. More root clutter. (¬_¬ )

I guess our license is ISC (by default), but I can go either way on this.

**Comment by Wolfr** [comment]
ISC is fine, I prefer MIT, but they are similar and not worth glossing over. If we make a decision I can apply it.

@jakobrosenberg I believe we should also have a CONTRIBUTING.md... sorry for the clutter. But these are signs of a well-maintained OSS project with policies and licenses in place.

**Comment by rixo** [comment]
> Ugh. More root clutter. (¬_¬ )

Ah ah, you must learn to love the bomb man, it's not going anywhere! And, to be fair, _those_ (LICENCE, README, CONTRIBUTING...) are not the ones we'd really want out of root...

> I guess our license is ISC (by default), but I can go either way on this.

We're all OK with going either way, so we need the Grand Wizard to pick only one. That's you, @jakobrosenberg.

**Comment by Wolfr** [comment]
Svelte is ISC licensed just doesn't have the same ring to it as MIT. An MIT
license is just more well known. But maybe that's just me.

**Comment by Wolfr** [comment]
Hi Jakob, hope you are back among the living. Any decision on this?

**Comment by jakobrosenberg** [comment]
@Wolfr Sorry about the delay. I'm not good with making unclear decisions. I'm gonna say stick with ISC unless you prefer MIT, in which case we go with MIT.

**Comment by Wolfr** [comment]
Prefer MIT because of <aforementioned reasons>. So let's go with that.
