### ISSUE TITLE
SSR demo?

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#92]
Is there a demo somewhere where the SSR is working?

https://routify-starter.now.sh/example/ seems to be rendering in SPA style.

**Comment by jakobrosenberg** [comment]
This one has SSR in the API example.

example.routify.dev

**Comment by Wolfr** [comment]
Great, I checked it and it generates the .html pages, I didn't see that working before, also checked it out in routify-site-2020 and generating the .html pages seems to work as well there.
