### ISSUE TITLE
Route comparison is case sensitive

### ISSUE THREAD

**Issue by fabiohvp** [roxiness/routify#93]
A suggestion is to add an option to use case insensitive

**Comment by japfohl** [comment]
Quick fix until this get implemented is to add the following to your `App.svelte`:

``` JavaScript
routes.forEach(r => {
  r.regex = new RegExp(r.regex, 'i');
});
```

**Comment by jakobrosenberg** [comment]
@fabiohvp sorry to leave you hanging like that. Not sure how this issue went unnoticed.
