### ISSUE TITLE
Init command?

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#96]
What's the point of the `init` command as specified in CLI options?

https://routify.now.sh/docs/config

Just wondering, if I run it in an empty directory, it doesn't seem to do anything.

```
   npx routify init
   npx: installed 1 in 3.776s
```

Or am I supposed to install routify as a command line tool somehow?

**Comment by jakobrosenberg** [comment]
The best way about this would be to update the docs to ``npx @sveltech/routfiy init``.

``npx routify init`` may only work within an existing project.

**Comment by Wolfr** [comment]
I added it to the docs in progress here.

https://www.notion.so/Basics-1f27abe7653c4228baa00ddb14aec6af
