### ISSUE TITLE
Build doesn't finish

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#97]
For https://github.com/sveltech/routify-site-2020 when I run `npm run build` I get output that ends with

```
[routify] Exporting to: dist
[routify] Generated 18 static pages
[routify] Export finished
[routify] Run "npm run preview-build" to see the result
```

If I run the same in a private project I get :

```
[routify] Exporting to: dist
```

Then nothing more. So it is breaking at some point.

Any pointers where to start debugging or to get more debug output welcome.

I can send the project over, it's a private repo.

Edit: Found the relevant part in `exporter.js`, now, looking for pointers on how I can run a local version of routify in my project so I can give it  a go myself.

**Comment by Wolfr** [comment]
I found the relevant code in `exporter.js`.

Nowm just wondering how would I combine my site with a local version of routify? How do I point to a local version of an npm module? Then I can give this a go.

**Comment by jakobrosenberg** [comment]
If you send the private repo, I can have a look.

Also, are you using the latest version of Routify?

**Comment by Wolfr** [comment]
I tried to give you access but Github seemed to be acting up, did you receive something?

**Comment by jakobrosenberg** [comment]
Sorry, no. Try again?

**Comment by Wolfr** [comment]
I upgraded to routify 1.0.5 and it works now.
